import { describe, expect, it } from "vitest";

import { isAutoGeneratedStepTitle, nextStepNamePatch, stepDisplayTitle } from "../lib/notebook-step-title";

describe("isAutoGeneratedStepTitle", () => {
  it("タイトルが空文字なら自動生成扱い（記号名で埋めてよい）", () => {
    expect(isAutoGeneratedStepTitle("", undefined)).toBe(true);
    expect(isAutoGeneratedStepTitle("", "v")).toBe(true);
  });

  it("タイトルが直前のresultSymbolと一致していれば自動生成扱い", () => {
    expect(isAutoGeneratedStepTitle("v", "v")).toBe(true);
  });

  it("プリセットの翻訳済みタイトルのように記号と異なる文言は自動生成扱いしない", () => {
    expect(isAutoGeneratedStepTitle("速さ v", "v")).toBe(false);
  });

  it("resultSymbolが未設定でもタイトルが非空なら自動生成扱いしない（人間が書いた可能性がある）", () => {
    expect(isAutoGeneratedStepTitle("Velocity", undefined)).toBe(false);
  });
});

describe("stepDisplayTitle", () => {
  it("タイトルが入っていればそのまま使う", () => {
    expect(stepDisplayTitle("速さ v", "d/t")).toBe("速さ v");
  });

  it("タイトルが空（または空白のみ）なら式を見出しに使う", () => {
    // 記号を消したときにtitleが一時的に空になるので、見出しが空欄になってはいけない。
    expect(stepDisplayTitle("", "d/t")).toBe("d/t");
    expect(stepDisplayTitle("   ", " d/t ")).toBe("d/t");
  });
});

describe("nextStepNamePatch", () => {
  it("タイトルが記号から自動生成されたものなら、新しい記号に追従する", () => {
    expect(nextStepNamePatch({ title: "v", resultSymbol: "v" }, "w", "d/t")).toEqual({ resultSymbol: "w", expression: "d/t", title: "w" });
  });

  it("人間が書いた／プリセットの翻訳済みタイトルには触れない", () => {
    expect(nextStepNamePatch({ title: "速さ v", resultSymbol: "v" }, "w", "d/t")).toEqual({ resultSymbol: "w", expression: "d/t" });
  });

  // CodeRabbitが指摘した実際のバグ。記号を消したときにタイトルを残すと、自動生成の目印
  // （title===resultSymbol）が失われ、次に別の記号を入れてもタイトルが古い記号のまま固定される。
  it("記号を消したときも自動生成のタイトルを空へ戻す（次の記号に追従できるようにするため）", () => {
    const afterClear = nextStepNamePatch({ title: "v", resultSymbol: "v" }, "", "d/t");
    expect(afterClear).toEqual({ resultSymbol: undefined, expression: "d/t", title: "" });
    // 続けて別の記号を入れたときに、古い記号"v"ではなく新しい記号に追従すること。
    const afterRename = nextStepNamePatch({ title: afterClear.title ?? "", resultSymbol: afterClear.resultSymbol }, "w", "d/t");
    expect(afterRename.title).toBe("w");
  });

  it("記号を消しても、人間が書いたタイトルは消さない", () => {
    expect(nextStepNamePatch({ title: "速さ v", resultSymbol: "v" }, "", "d/t")).toEqual({ resultSymbol: undefined, expression: "d/t" });
  });
});
