import { describe, expect, it } from "vitest";

import { isAutoGeneratedStepTitle } from "../lib/notebook-step-title";

describe("isAutoGeneratedStepTitle", () => {
  it("タイトルが空文字なら自動生成扱い（記号名で埋めてよい）", () => {
    expect(isAutoGeneratedStepTitle("", undefined)).toBe(true);
    expect(isAutoGeneratedStepTitle("", "v")).toBe(true);
  });

  it("タイトルが直前のresultSymbolと一致していれば自動生成扱い", () => {
    expect(isAutoGeneratedStepTitle("v", "v")).toBe(true);
  });

  it("プリセットの翻訳済みタイトルのように記号と異なる文言は自動生成扱いしない", () => {
    expect(isAutoGeneratedStepTitle("速さ v", "v")).toBe(false);
  });

  it("resultSymbolが未設定でもタイトルが非空なら自動生成扱いしない（人間が書いた可能性がある）", () => {
    expect(isAutoGeneratedStepTitle("Velocity", undefined)).toBe(false);
  });
});
