import { describe, expect, it } from "vitest";

import { buildNotebookExportHtml } from "../lib/notebook-export-html";
import { type NotebookExportModel } from "../lib/notebook-export-model";

const OPTIONS = {
  katexCss: "/* katex css marker */",
  katexJs: "/* katex js marker */",
  lang: "ja",
  headings: { formulas: "Formulas", inputs: "Inputs", steps: "Steps" },
  footer: "Generated by si-unit-calculator",
};

function baseModel(overrides: Partial<NotebookExportModel> = {}): NotebookExportModel {
  return {
    title: "落下運動",
    description: "自由落下の基本公式",
    formulas: [{ explanation: "速度の式", latex: "v = g t" }],
    constants: [{ text: "g = 9.8 m/s^2" }],
    steps: [{ title: "速度", expression: "g*t", resultText: "9.8 m/s", isError: false }],
    ...overrides,
  };
}

describe("buildNotebookExportHtml", () => {
  it("html要素のlangに渡された言語を出す（内容が日本語なのにlang=\"en\"だと読み上げ・ハイフネーションが崩れる）", () => {
    expect(buildNotebookExportHtml(baseModel(), OPTIONS)).toContain('<html lang="ja">');
    expect(buildNotebookExportHtml(baseModel(), { ...OPTIONS, lang: "pt-BR" })).toContain('<html lang="pt-BR">');
  });

  it("langもエスケープする（属性から抜け出せないようにする）", () => {
    const html = buildNotebookExportHtml(baseModel(), { ...OPTIONS, lang: '"><script>alert(1)</script>' });
    expect(html).not.toContain("<script>alert(1)</script>");
    expect(html).toContain("&quot;&gt;&lt;script&gt;");
  });

  it("完全なHTMLドキュメントを返し、タイトル・説明・定数・手順を含む", () => {
    const html = buildNotebookExportHtml(baseModel(), OPTIONS);
    expect(html).toContain("<!DOCTYPE html>");
    expect(html).toContain("<html");
    expect(html).toContain('<meta charset="utf-8"');
    expect(html).toContain("落下運動");
    expect(html).toContain("自由落下の基本公式");
    expect(html).toContain("g = 9.8 m/s^2");
    expect(html).toContain("速度");
    expect(html).toContain("g*t");
    expect(html).toContain("9.8 m/s");
  });

  it("descriptionが空文字なら説明ブロック自体を出さない", () => {
    const html = buildNotebookExportHtml(baseModel({ description: "" }), OPTIONS);
    expect(html).not.toContain('class="description"');
  });

  it("formulasが空配列なら数式セクション自体を出さない", () => {
    const html = buildNotebookExportHtml(baseModel({ formulas: [] }), OPTIONS);
    expect(html).not.toContain('class="formulas"');
  });

  it("手順のtitleが空文字ならタイトル行を出さない", () => {
    const html = buildNotebookExportHtml(
      baseModel({ steps: [{ title: "", expression: "g*t", resultText: "9.8 m/s", isError: false }] }),
      OPTIONS,
    );
    expect(html).not.toContain('class="step-title"');
  });

  it("formulaのexplanationが空文字ならその行を出さない", () => {
    const html = buildNotebookExportHtml(baseModel({ formulas: [{ explanation: "", latex: "v = g t" }] }), OPTIONS);
    expect(html).not.toContain('class="formula-explanation"');
  });

  it("タイトル中の<script>タグはHTMLエスケープされ、生きたscriptタグとして出力されない", () => {
    const html = buildNotebookExportHtml(baseModel({ title: "<script>alert(1)</script>" }), OPTIONS);
    expect(html).not.toContain("<script>alert(1)</script>");
    expect(html).toContain("&lt;script&gt;alert(1)&lt;/script&gt;");
  });

  it("&, <, >, \", ' を含むテキストフィールドはすべてエスケープされる", () => {
    const html = buildNotebookExportHtml(
      baseModel({
        description: `A & B < C > D "E" 'F'`,
        constants: [{ text: `x & y < z > "q" 'r'` }],
        steps: [{ title: "T&<>\"'", expression: "a&b", resultText: "1<2", isError: false }],
      }),
      OPTIONS,
    );
    expect(html).toContain("A &amp; B &lt; C &gt; D &quot;E&quot; &#39;F&#39;");
    expect(html).toContain("x &amp; y &lt; z &gt; &quot;q&quot; &#39;r&#39;");
    expect(html).toContain("T&amp;&lt;&gt;&quot;&#39;");
    expect(html).toContain("a&amp;b");
    expect(html).toContain("1&lt;2");
    // 生のアンパサンド・不等号がテキストとして残らないこと（属性やタグを壊せないことの確認）。
    expect(html).not.toContain(`A & B < C`);
  });

  it("バックスラッシュ・ダブルクォート・</script>を含むlatexが埋め込まれても、scriptブロックが早期終了せずlatexを復元できる", () => {
    const tricky = String.raw`\frac{1}{2}\alpha "quoted" </script> tail`;
    const html = buildNotebookExportHtml(baseModel({ formulas: [{ explanation: "", latex: tricky }] }), OPTIONS);

    // "<"を含む文字列はユニコードエスケープされているはずなので、生の"</script"はkatex.render呼び出し内に現れない。
    // 逆に言えば、ドキュメント中の実際のscript終了タグは元々あるべき数だけ（katexJs用1つ+formula用1つ=2つ）のはず。
    const scriptCloseCount = (html.match(/<\/script>/g) ?? []).length;
    expect(scriptCloseCount).toBe(2);

    // katex.render呼び出しに渡す文字列リテラルからJSON.parseで元のlatexを復元できることを確認する
    // （スクリプトが壊れていれば、この抽出・パースが失敗するか値が食い違う）。
    const match = html.match(/katex\.render\(([\s\S]*?), document\.getElementById/);
    expect(match).not.toBeNull();
    const literal = match![1];
    // JSON.stringifyされた文字列は<にエスケープされているため、JSON.parseで元に戻せば
    // 復元されたlatex文字列は"<"を含む形（tricky自体）に一致するはず。
    const restored = JSON.parse(literal);
    expect(restored).toBe(tricky);
  });

  it("isErrorがtrueの手順は通常の手順と異なるクラスで出力される", () => {
    const html = buildNotebookExportHtml(
      baseModel({
        steps: [
          { title: "正常", expression: "1+1", resultText: "2", isError: false },
          { title: "エラー", expression: "1/0", resultText: "エラー", isError: true },
        ],
      }),
      OPTIONS,
    );
    expect(html).toContain('class="step-card"');
    expect(html).toContain('class="step-card step-card-error"');
  });

  it("渡したkatexCss・katexJs・見出し・フッターがすべて出力に含まれる", () => {
    const html = buildNotebookExportHtml(baseModel(), OPTIONS);
    expect(html).toContain(OPTIONS.katexCss);
    expect(html).toContain(OPTIONS.katexJs);
    expect(html).toContain(OPTIONS.headings.formulas);
    expect(html).toContain(OPTIONS.headings.inputs);
    expect(html).toContain(OPTIONS.headings.steps);
    expect(html).toContain(OPTIONS.footer);
  });

  it("数式・定数・手順が全て空でも例外を投げず有効なドキュメントを返す", () => {
    const html = buildNotebookExportHtml(
      { title: "空のノート", description: "", formulas: [], constants: [], steps: [] },
      OPTIONS,
    );
    expect(html).toContain("<!DOCTYPE html>");
    expect(html).toContain("空のノート");
    expect(html).not.toContain('class="formulas"');
    expect(html).not.toContain('class="description"');
  });
});
