const path = require("path");
const fs = require("fs");
const { withAppBuildGradle, withDangerousMod } = require("@expo/config-plugins");

// ローカルで Play 提出用の release AAB を署名してビルドできるようにする。
//
// prebuild が生成する release buildType は `signingConfig signingConfigs.debug` を指していて、
// そのままビルドしたAABは**デバッグ鍵で署名される**。Playは既存アプリと署名鍵が違うAABを
// 受け付けないので、アップロードした時点で弾かれる。
//
// 鍵と3つのパスワードは `credentials.json`（.gitignore 済み）から読む。
// `eas credentials -p android` の「credentials.json: Upload/Download」で落ちてくる形式。
//
// **credentials.json が無いときは何もしない。** EASビルドのアップロードにはこのファイルを
// 含めない（.gitignore 済み＝EASのarchiveにも入らない）ので、EAS側が注入する署名設定を
// このプラグインが壊すことはない。

const marker = "// si-calculator: local release signing from credentials.json";
const DEBUG_SIGNING_LINE = "            signingConfig signingConfigs.debug\n";
const RELEASE_SIGNING_LINE =
  '            signingConfig rootProject.file("keystore.properties").exists() ? signingConfigs.release : signingConfigs.debug\n';

const readCredentials = (projectRoot) => {
  const file = path.join(projectRoot, "credentials.json");
  if (!fs.existsSync(file)) return null;
  const ks = JSON.parse(fs.readFileSync(file, "utf8"))?.android?.keystore;
  if (!ks?.keystorePath || !ks.keystorePassword || !ks.keyAlias || !ks.keyPassword) {
    throw new Error(
      "credentials.json の android.keystore に keystorePath / keystorePassword / keyAlias / keyPassword が揃っていません。",
    );
  }
  return ks;
};

module.exports = function withLocalReleaseSigning(config) {
  // 1) gradle から読む keystore.properties を android/ 直下に書き出す。
  //    パスワードを build.gradle に直書きしないのと、prebuild のたびに作り直すため。
  config = withDangerousMod(config, [
    "android",
    (config) => {
      const projectRoot = config.modRequest.projectRoot;
      const target = path.join(config.modRequest.platformProjectRoot, "keystore.properties");
      const ks = readCredentials(projectRoot);
      if (!ks) {
        // 前回のローカルビルドの残りが居座らないように消す。
        if (fs.existsSync(target)) fs.rmSync(target);
        return config;
      }
      const storeFile = path.resolve(projectRoot, ks.keystorePath);
      if (!fs.existsSync(storeFile)) {
        throw new Error(`credentials.json の keystorePath が指すファイルがありません: ${storeFile}`);
      }
      // .properties は ISO-8859-1 で読まれ、`\` はエスケープの開始として食われる
      // （`C:\Work` が `C:Work` になってパスが壊れる）。Windowsのパス区切りは `/` に
      // 直して `\` を消す——Java の File は `/` 区切りを受け付ける。値の中の `:` と `=`
      // は区切りが最初の1つだけなのでエスケープ不要。残る `\` だけ念のため潰す。
      const escapeBackslash = (value) => String(value).split("\\").join("\\\\");
      const toSlash = (value) => String(value).split("\\").join("/");
      fs.writeFileSync(
        target,
        [
          "# Generated by plugins/withLocalReleaseSigning.js - do not edit by hand.",
          `storeFile=${escapeBackslash(toSlash(storeFile))}`,
          `storePassword=${escapeBackslash(ks.keystorePassword)}`,
          `keyAlias=${escapeBackslash(ks.keyAlias)}`,
          `keyPassword=${escapeBackslash(ks.keyPassword)}`,
          "",
        ].join("\n"),
        "latin1",
      );
      return config;
    },
  ]);

  config = withAppBuildGradle(config, (config) => {
    if (config.modResults.language !== "groovy") {
      throw new Error("withLocalReleaseSigning requires a Groovy app/build.gradle");
    }
    let contents = config.modResults.contents;
    if (contents.includes(marker)) return config;

    // 2) 先に buildTypes の release を差し替える。**signingConfigs へ release ブロックを
    //    入れる前に行うこと**——先に入れると、そのブロックの `release {` に検索が先に
    //    当たって buildTypes の debug 側を書き換えてしまう（実際に踏んだ）。
    //    正規表現は使わず、buildTypes ブロック以降に範囲を限ってから最初の1件だけ置換する。
    const buildTypesAt = contents.indexOf("    buildTypes {");
    if (buildTypesAt < 0) throw new Error("withLocalReleaseSigning could not find the buildTypes block");
    const head = contents.slice(0, buildTypesAt);
    const buildTypes = contents.slice(buildTypesAt);
    const releaseAt = buildTypes.indexOf("        release {");
    if (releaseAt < 0) throw new Error("withLocalReleaseSigning could not find the release buildType");
    const releaseBody = buildTypes.slice(releaseAt);
    if (!releaseBody.includes(DEBUG_SIGNING_LINE)) {
      throw new Error("withLocalReleaseSigning could not find the release signingConfig line");
    }
    contents =
      head + buildTypes.slice(0, releaseAt) + releaseBody.replace(DEBUG_SIGNING_LINE, RELEASE_SIGNING_LINE);

    // 3) そのうえで signingConfigs に release を足す。
    const signingHeader = "    signingConfigs {\n";
    const signingAt = contents.indexOf(signingHeader);
    if (signingAt < 0) throw new Error("withLocalReleaseSigning could not find the signingConfigs block");
    const insertAt = signingAt + signingHeader.length;
    const releaseSigningConfig = [
      `        ${marker}`,
      "        release {",
      "            def props = new Properties()",
      '            def f = rootProject.file("keystore.properties")',
      "            if (f.exists()) {",
      "                f.withInputStream { props.load(it) }",
      "                storeFile file(props['storeFile'])",
      "                storePassword props['storePassword']",
      "                keyAlias props['keyAlias']",
      "                keyPassword props['keyPassword']",
      "            }",
      "        }",
      "",
    ].join("\n");
    contents = contents.slice(0, insertAt) + releaseSigningConfig + contents.slice(insertAt);

    config.modResults.contents = contents;
    return config;
  });

  return config;
};
