const path = require("path");
const fs = require("fs");
const { withDangerousMod } = require("@expo/config-plugins");

// release ビルドから SYSTEM_ALERT_WINDOW（他のアプリの上に重ねて表示）を外す。
//
// この権限は依存が足しているのではなく、**prebuild が生成する
// android/app/src/main/AndroidManifest.xml が自分で宣言している**（Expoの
// テンプレート由来。React Native の開発メニューのためのもの）。
// このアプリは実行時に一度も使っていないのに、**Playの掲載ページの権限一覧に出る**。
//
// **`android.permissions: []` では消えない。** あれは「追加で足さない」の指定で、
// 既に書かれている宣言を取り消す働きは無い。
//
// **消すのは release だけ。** debug 側は残す——RNの開発メニュー・デバッグ用の
// オーバーレイがこの権限を前提にしている可能性があり、日々のデバッグの経路を
// 壊す方が損失が大きい（Playに出るのは release だけなので、消す価値があるのも
// release だけ）。build type のソースセットのマニフェストは main より優先されるので、
// ここに `tools:node="remove"` を置けば merge の結果から外れる。
//
// **android/ は .gitignore 済みの生成物**なので、生成された main のマニフェストを
// 直に書き換えても次の prebuild で戻る。この上書きを残すために config plugin にしてある。
//
// なお `READ_EXTERNAL_STORAGE` / `WRITE_EXTERNAL_STORAGE` も同じ main のマニフェストに
// 居るが、こちらは maxSdkVersion 32 が付いていて（Android 13以降には要求されない）、
// ファイルの取り込み・共有で実際に使う経路があるので残している。

const MANIFEST = [
  "<!-- Generated by plugins/withoutReleaseOverlayPermission.js - do not edit by hand. -->",
  '<manifest xmlns:android="http://schemas.android.com/apk/res/android" xmlns:tools="http://schemas.android.com/tools">',
  '  <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW" tools:node="remove" />',
  "</manifest>",
  "",
].join("\n");

module.exports = function withoutReleaseOverlayPermission(config) {
  return withDangerousMod(config, [
    "android",
    (config) => {
      const dir = path.join(config.modRequest.platformProjectRoot, "app", "src", "release");
      fs.mkdirSync(dir, { recursive: true });
      fs.writeFileSync(path.join(dir, "AndroidManifest.xml"), MANIFEST, "utf8");
      return config;
    },
  ]);
};
