/**
 * 計算ノートの手順の「名前＝式」欄（例: "v=d/t"）を編集したとき、表示タイトルを自動追従
 * させてよいかどうかを判定する。
 *
 * なぜ必要か: プリセットの手順は「速さ v」のような6言語に翻訳済みの表示用タイトルを持つ。
 * 一方、ユーザーが名前欄に記号（例: "v"）を打つと、以前はそのタイトルを問答無用で記号名
 * （"v"だけ）に置き換えていた。値を編集するついでに名前欄へ触れただけでプリセットの表示用
 * タイトルが記号名に潰れてしまう、実質的なデータ破壊だった。
 *
 * これを防ぐため、タイトルが「以前この仕組みで記号から自動生成されたものだった」場合
 * （＝タイトルが空、または直前のresultSymbolと一致している）だけ追従させ、それ以外
 * （人間が書いた／プリセットの翻訳済みタイトル）はそのまま保つ。
 */
export function isAutoGeneratedStepTitle(previousTitle: string, previousResultSymbol: string | undefined): boolean {
  return previousTitle === "" || previousTitle === (previousResultSymbol ?? "");
}

/**
 * 手順の表示タイトル。未入力なら式そのものを見出しに使う。
 *
 * なぜ必要か: isAutoGeneratedStepTitle の仕組みでは「自動生成されたタイトル」の状態を
 * title と resultSymbol の一致で表すため、記号を消したときはタイトルも空に戻す必要がある
 * （残すと記号だけ消えて古い記号名のタイトルが固定されてしまう）。その結果 title が一時的に
 * 空になり得るので、表示・コピー・保存のすべてでこの同じフォールバックを通す。3箇所に
 * 同じ式を書くと片方だけ直したときにずれるため関数にまとめている。
 */
export function stepDisplayTitle(title: string, expression: string): string {
  return title.trim() || expression.trim();
}

/**
 * 「名前＝式」欄を書き換えたときに手順へ当てる差分。
 *
 * なぜ関数にするか: 編集画面（app/(tabs)/constants.tsx）と詳細画面
 * （components/notebooks/notebook-detail.tsx）の両方が同じ判断をする必要があり、片方だけ直すと
 * 挙動が分岐して気付けない。判定を目で追える形の純関数にしておけば、テストが実際の分岐を
 * 通せる（画面側で組み立てていると、テストは同じ手順を手で再現するだけになり退行を検出できない）。
 *
 * 名前を消したとき（name=""）もタイトルを空へ戻すのが要点。記号だけ消してタイトルを残すと
 * 自動生成の目印（title===resultSymbol）が失われ、次に別の記号を入れてももう自動生成扱いに
 * ならず、タイトルが古い記号のまま固定されてしまう。
 */
export function nextStepNamePatch(
  step: { title: string; resultSymbol?: string },
  name: string,
  expression: string,
): { resultSymbol: string | undefined; expression: string; title?: string } {
  const patch: { resultSymbol: string | undefined; expression: string; title?: string } = { resultSymbol: name || undefined, expression };
  if (isAutoGeneratedStepTitle(step.title, step.resultSymbol)) patch.title = name;
  return patch;
}
