/**
 * 計算ノートの手順の「名前＝式」欄（例: "v=d/t"）を編集したとき、表示タイトルを自動追従
 * させてよいかどうかを判定する。
 *
 * なぜ必要か: プリセットの手順は「速さ v」のような6言語に翻訳済みの表示用タイトルを持つ。
 * 一方、ユーザーが名前欄に記号（例: "v"）を打つと、以前はそのタイトルを問答無用で記号名
 * （"v"だけ）に置き換えていた。値を編集するついでに名前欄へ触れただけでプリセットの表示用
 * タイトルが記号名に潰れてしまう、実質的なデータ破壊だった。
 *
 * これを防ぐため、タイトルが「以前この仕組みで記号から自動生成されたものだった」場合
 * （＝タイトルが空、または直前のresultSymbolと一致している）だけ追従させ、それ以外
 * （人間が書いた／プリセットの翻訳済みタイトル）はそのまま保つ。
 */
export function isAutoGeneratedStepTitle(previousTitle: string, previousResultSymbol: string | undefined): boolean {
  return previousTitle === "" || previousTitle === (previousResultSymbol ?? "");
}
