import type { LocalizedText } from "./i18n";

export type SampleCategory = "basic" | "motion" | "mechanics" | "energy" | "electric" | "math" | "ratio";

export type SampleCalculation = {
  id: string;
  category: SampleCategory;
  title: LocalizedText;
  description: LocalizedText;
  expression: string;
  targetUnit: string;
};

export const SAMPLE_CATEGORIES: Array<{ id: SampleCategory; label: LocalizedText }> = [
  { id: "basic", label: { en: "Basics", ja: "基本", es: "Básico", "pt-BR": "Básico", de: "Grundlagen", fr: "Base" } },
  { id: "motion", label: { en: "Speed", ja: "距離・速度", es: "Velocidad", "pt-BR": "Velocidade", de: "Geschwindigkeit", fr: "Vitesse" } },
  { id: "mechanics", label: { en: "Force & pressure", ja: "力・圧力", es: "Fuerza y presión", "pt-BR": "Força e pressão", de: "Kraft & Druck", fr: "Force et pression" } },
  { id: "energy", label: { en: "Energy", ja: "エネルギー", es: "Energía", "pt-BR": "Energia", de: "Energie", fr: "Énergie" } },
  { id: "electric", label: { en: "Electric", ja: "電気", es: "Eléctrico", "pt-BR": "Elétrico", de: "Elektrizität", fr: "Électricité" } },
  { id: "math", label: { en: "Angles & math", ja: "角度・関数", es: "Ángulos y funciones", "pt-BR": "Ângulos e funções", de: "Winkel & Funktionen", fr: "Angles et fonctions" } },
  { id: "ratio", label: { en: "Ratios", ja: "割合", es: "Proporciones", "pt-BR": "Razões", de: "Verhältnisse", fr: "Rapports" } },
];

export const SAMPLE_CALCULATIONS: SampleCalculation[] = [
  { id: "length-add", category: "basic", title: { en: "Add lengths", ja: "長さを足す", es: "Sumar longitudes", "pt-BR": "Somar comprimentos", de: "Längen addieren", fr: "Additionner des longueurs" }, description: { en: "Normalize mixed lengths to SI before adding", ja: "異なる長さの単位をSIでそろえて加算", es: "Convierte longitudes distintas al SI antes de sumarlas", "pt-BR": "Converte comprimentos diferentes para o SI antes de somar", de: "Verschiedene Längeneinheiten vor der Addition auf SI umrechnen", fr: "Convertir des longueurs différentes en unités SI avant de les additionner" }, expression: "5cm + 1mm", targetUnit: "cm" },
  { id: "area", category: "basic", title: { en: "Find an area", ja: "面積を求める", es: "Calcular un área", "pt-BR": "Calcular uma área", de: "Fläche berechnen", fr: "Calculer une aire" }, description: { en: "Length × length gives area", ja: "長さ × 長さで面積へ", es: "Longitud × longitud da el área", "pt-BR": "Comprimento × comprimento resulta em área", de: "Länge × Länge ergibt die Fläche", fr: "Longueur × longueur donne l'aire" }, expression: "3cm × 20mm", targetUnit: "cm²" },
  { id: "speed", category: "motion", title: { en: "Find speed", ja: "速度を求める", es: "Calcular la velocidad", "pt-BR": "Calcular a velocidade", de: "Geschwindigkeit berechnen", fr: "Calculer la vitesse" }, description: { en: "Distance ÷ time = speed", ja: "距離 ÷ 時間 = 速度", es: "Distancia ÷ tiempo = velocidad", "pt-BR": "Distância ÷ tempo = velocidade", de: "Strecke ÷ Zeit = Geschwindigkeit", fr: "Distance ÷ temps = vitesse" }, expression: "1km ÷ 1min", targetUnit: "km/h" },
  { id: "kine", category: "motion", title: { en: "Convert kine", ja: "kineを換算", es: "Convertir kine", "pt-BR": "Converter kine", de: "Kine umrechnen", fr: "Convertir le kine" }, description: { en: "Convert the CGS speed unit to SI speed", ja: "CGS速度単位をSI速度へ", es: "Convierte la unidad de velocidad CGS al SI", "pt-BR": "Converte a unidade de velocidade CGS para o SI", de: "CGS-Geschwindigkeitseinheit in SI umrechnen", fr: "Convertir l'unité de vitesse CGS en unité SI" }, expression: "100kine", targetUnit: "km/h" },
  { id: "distance", category: "motion", title: { en: "Find distance", ja: "距離を求める", es: "Calcular la distancia", "pt-BR": "Calcular a distância", de: "Strecke berechnen", fr: "Calculer la distance" }, description: { en: "Speed × time = distance", ja: "速度 × 時間 = 距離", es: "Velocidad × tiempo = distancia", "pt-BR": "Velocidade × tempo = distância", de: "Geschwindigkeit × Zeit = Strecke", fr: "Vitesse × temps = distance" }, expression: "10m/s × 2min", targetUnit: "km" },
  { id: "time", category: "motion", title: { en: "Find time", ja: "時間を求める", es: "Calcular el tiempo", "pt-BR": "Calcular o tempo", de: "Zeit berechnen", fr: "Calculer le temps" }, description: { en: "Distance ÷ speed = time", ja: "距離 ÷ 速度 = 時間", es: "Distancia ÷ velocidad = tiempo", "pt-BR": "Distância ÷ velocidade = tempo", de: "Strecke ÷ Geschwindigkeit = Zeit", fr: "Distance ÷ vitesse = temps" }, expression: "1km ÷ 5m/s", targetUnit: "min" },
  { id: "sine-degrees", category: "math", title: { en: "Sine in degrees", ja: "度数法の正弦", es: "Seno en grados", "pt-BR": "Seno em graus", de: "Sinus in Grad", fr: "Sinus en degrés" }, description: { en: "Calculate the dimensionless sine of 30 degrees", ja: "30度のsinを無次元値として計算", es: "Calcula el seno adimensional de 30 grados", "pt-BR": "Calcula o seno adimensional de 30 graus", de: "Den dimensionslosen Sinus von 30 Grad berechnen", fr: "Calculer le sinus (sans dimension) de 30 degrés" }, expression: "sin(30deg)", targetUnit: "" },
  { id: "atan2-angle", category: "math", title: { en: "Find an angle from two sides", ja: "2辺から角度を求める", es: "Calcular un ángulo a partir de dos lados", "pt-BR": "Calcular um ângulo a partir de dois lados", de: "Winkel aus zwei Seiten berechnen", fr: "Calculer un angle à partir de deux côtés" }, description: { en: "Use atan2 with two values of the same dimension", ja: "atan2で同じ次元の2辺から角度を出す", es: "Usa atan2 con dos valores de la misma dimensión", "pt-BR": "Use atan2 com dois valores da mesma dimensão", de: "atan2 mit zwei Werten derselben Dimension verwenden", fr: "Utiliser atan2 avec deux valeurs de même dimension" }, expression: "atan2(1m, 1m)", targetUnit: "deg" },
  { id: "logarithm", category: "math", title: { en: "Base-10 logarithm", ja: "常用対数", es: "Logaritmo en base 10", "pt-BR": "Logaritmo na base 10", de: "Zehnerlogarithmus", fr: "Logarithme en base 10" }, description: { en: "Calculate the base-10 logarithm of 1000", ja: "1000の常用対数を計算", es: "Calcula el logaritmo en base 10 de 1000", "pt-BR": "Calcula o logaritmo na base 10 de 1000", de: "Den Zehnerlogarithmus von 1000 berechnen", fr: "Calculer le logarithme en base 10 de 1000" }, expression: "log(1000)", targetUnit: "" },
  { id: "square-root-area", category: "math", title: { en: "Square root of area", ja: "面積の平方根", es: "Raíz cuadrada de un área", "pt-BR": "Raiz quadrada de uma área", de: "Quadratwurzel einer Fläche", fr: "Racine carrée d'une aire" }, description: { en: "Find a side length from an area", ja: "面積から一辺の長さを求める", es: "Calcula la longitud de un lado a partir de un área", "pt-BR": "Calcula o comprimento de um lado a partir de uma área", de: "Eine Seitenlänge aus einer Fläche berechnen", fr: "Calculer la longueur d'un côté à partir d'une aire" }, expression: "sqrt(144cm²)", targetUnit: "cm" },
  { id: "power-length", category: "math", title: { en: "Power of length", ja: "長さのべき乗", es: "Potencia de una longitud", "pt-BR": "Potência de um comprimento", de: "Potenz einer Länge", fr: "Puissance d'une longueur" }, description: { en: "Find volume by cubing a length", ja: "長さの3乗から体積を求める", es: "Calcula el volumen elevando una longitud al cubo", "pt-BR": "Calcula o volume elevando um comprimento ao cubo", de: "Das Volumen durch Kubieren einer Länge berechnen", fr: "Calculer le volume en élevant une longueur au cube" }, expression: "(2m)^3", targetUnit: "m³" },
  { id: "force", category: "mechanics", title: { en: "Find force", ja: "力を求める", es: "Calcular la fuerza", "pt-BR": "Calcular a força", de: "Kraft berechnen", fr: "Calculer la force" }, description: { en: "Mass × acceleration = force", ja: "質量 × 加速度 = 力", es: "Masa × aceleración = fuerza", "pt-BR": "Massa × aceleração = força", de: "Masse × Beschleunigung = Kraft", fr: "Masse × accélération = force" }, expression: "2kg × 9.8m/s²", targetUnit: "N" },
  { id: "standard-gravity", category: "mechanics", title: { en: "Convert standard gravity", ja: "標準重力を換算", es: "Convertir la gravedad estándar", "pt-BR": "Converter a gravidade padrão", de: "Normfallbeschleunigung umrechnen", fr: "Convertir la gravité standard" }, description: { en: "Convert 1G to Gal for gravimetry", ja: "1G を地球物理で用いる Gal へ", es: "Convierte 1G a Gal para gravimetría", "pt-BR": "Converte 1G para Gal para gravimetria", de: "1G für die Gravimetrie in Gal umrechnen", fr: "Convertir 1G en Gal pour la gravimétrie" }, expression: "1G", targetUnit: "Gal" },
  { id: "pressure", category: "mechanics", title: { en: "Find pressure", ja: "圧力を求める", es: "Calcular la presión", "pt-BR": "Calcular a pressão", de: "Druck berechnen", fr: "Calculer la pression" }, description: { en: "Force ÷ area = pressure", ja: "力 ÷ 面積 = 圧力", es: "Fuerza ÷ área = presión", "pt-BR": "Força ÷ área = pressão", de: "Kraft ÷ Fläche = Druck", fr: "Force ÷ aire = pression" }, expression: "100N ÷ 0.01m²", targetUnit: "kPa" },
  { id: "work", category: "energy", title: { en: "Find energy", ja: "仕事を求める", es: "Calcular la energía", "pt-BR": "Calcular a energia", de: "Energie berechnen", fr: "Calculer l'énergie" }, description: { en: "Force × distance = energy", ja: "力 × 距離 = エネルギー", es: "Fuerza × distancia = energía", "pt-BR": "Força × distância = energia", de: "Kraft × Strecke = Energie", fr: "Force × distance = énergie" }, expression: "250N × 4m", targetUnit: "kJ" },
  { id: "power", category: "energy", title: { en: "Find power", ja: "仕事率を求める", es: "Calcular la potencia", "pt-BR": "Calcular a potência", de: "Leistung berechnen", fr: "Calculer la puissance" }, description: { en: "Energy ÷ time = power", ja: "エネルギー ÷ 時間 = 電力", es: "Energía ÷ tiempo = potencia", "pt-BR": "Energia ÷ tempo = potência", de: "Energie ÷ Zeit = Leistung", fr: "Énergie ÷ temps = puissance" }, expression: "1200J ÷ 2min", targetUnit: "W" },
  { id: "electric-power", category: "electric", title: { en: "Electric power", ja: "電力を求める", es: "Potencia eléctrica", "pt-BR": "Potência elétrica", de: "Elektrische Leistung", fr: "Puissance électrique" }, description: { en: "Voltage × current = power", ja: "電圧 × 電流 = 電力", es: "Voltaje × corriente = potencia", "pt-BR": "Tensão × corrente = potência", de: "Spannung × Stromstärke = Leistung", fr: "Tension × courant = puissance" }, expression: "12V × 2A", targetUnit: "W" },
  { id: "percentage", category: "ratio", title: { en: "Convert to a percentage", ja: "割合を百分率へ", es: "Convertir a porcentaje", "pt-BR": "Converter para porcentagem", de: "In Prozent umrechnen", fr: "Convertir en pourcentage" }, description: { en: "Display a dimensionless value as %", ja: "無次元値を % で表示", es: "Muestra un valor adimensional como %", "pt-BR": "Exibe um valor adimensional como %", de: "Einen dimensionslosen Wert als % anzeigen", fr: "Afficher une valeur sans dimension en %" }, expression: "0.125", targetUnit: "%" },
];
