import type { LocalizedText } from "./i18n";

export type SampleCategory = "basic" | "motion" | "mechanics" | "energy" | "electric" | "math" | "ratio" | "exam" | "lab";

export type SampleCalculation = {
  id: string;
  category: SampleCategory;
  title: LocalizedText;
  description: LocalizedText;
  expression: string;
  targetUnit: string;
};

export const SAMPLE_CATEGORIES: Array<{ id: SampleCategory; label: LocalizedText }> = [
  { id: "basic", label: { en: "Basics", ja: "基本", es: "Básico", "pt-BR": "Básico", de: "Grundlagen", fr: "Base" } },
  { id: "motion", label: { en: "Speed", ja: "距離・速度", es: "Velocidad", "pt-BR": "Velocidade", de: "Geschwindigkeit", fr: "Vitesse" } },
  { id: "mechanics", label: { en: "Force & pressure", ja: "力・圧力", es: "Fuerza y presión", "pt-BR": "Força e pressão", de: "Kraft & Druck", fr: "Force et pression" } },
  { id: "energy", label: { en: "Energy", ja: "エネルギー", es: "Energía", "pt-BR": "Energia", de: "Energie", fr: "Énergie" } },
  { id: "electric", label: { en: "Electric", ja: "電気", es: "Eléctrico", "pt-BR": "Elétrico", de: "Elektrizität", fr: "Électricité" } },
  { id: "math", label: { en: "Angles & math", ja: "角度・関数", es: "Ángulos y funciones", "pt-BR": "Ângulos e funções", de: "Winkel & Funktionen", fr: "Angles et fonctions" } },
  { id: "ratio", label: { en: "Ratios", ja: "割合", es: "Proporciones", "pt-BR": "Razões", de: "Verhältnisse", fr: "Rapports" } },
  // 試験対策と実験レポートは、言語ごとに**その国で実際に受ける試験・提出物の名前**でラベルを出す。
  // 直訳（"Exam prep"を各言語へ）にすると、独語圏のKlausur・仏語圏のTP・西語圏のEBAUのように
  // 現地で通っている呼び名から外れて、対象の受験者に「自分向け」と伝わらなくなる。
  { id: "exam", label: { en: "Exam prep", ja: "試験対策（電験・電工）", es: "Preparación (EBAU)", "pt-BR": "Preparação (ENEM)", de: "Klausur & Prüfung", fr: "Révisions (physique-chimie)" } },
  { id: "lab", label: { en: "Lab reports", ja: "実験レポート", es: "Informe de laboratorio", "pt-BR": "Relatório de laboratório", de: "Laborbericht", fr: "Compte rendu de TP" } },
];

export const SAMPLE_CALCULATIONS: SampleCalculation[] = [
  { id: "length-add", category: "basic", title: { en: "Add lengths", ja: "長さを足す", es: "Sumar longitudes", "pt-BR": "Somar comprimentos", de: "Längen addieren", fr: "Additionner des longueurs" }, description: { en: "Normalize mixed lengths to SI before adding", ja: "異なる長さの単位をSIでそろえて加算", es: "Convierte longitudes distintas al SI antes de sumarlas", "pt-BR": "Converte comprimentos diferentes para o SI antes de somar", de: "Verschiedene Längeneinheiten vor der Addition auf SI umrechnen", fr: "Convertir des longueurs différentes en unités SI avant de les additionner" }, expression: "5cm + 1mm", targetUnit: "cm" },
  { id: "area", category: "basic", title: { en: "Find an area", ja: "面積を求める", es: "Calcular un área", "pt-BR": "Calcular uma área", de: "Fläche berechnen", fr: "Calculer une aire" }, description: { en: "Length × length gives area", ja: "長さ × 長さで面積へ", es: "Longitud × longitud da el área", "pt-BR": "Comprimento × comprimento resulta em área", de: "Länge × Länge ergibt die Fläche", fr: "Longueur × longueur donne l'aire" }, expression: "3cm × 20mm", targetUnit: "cm²" },
  { id: "speed", category: "motion", title: { en: "Find speed", ja: "速度を求める", es: "Calcular la velocidad", "pt-BR": "Calcular a velocidade", de: "Geschwindigkeit berechnen", fr: "Calculer la vitesse" }, description: { en: "Distance ÷ time = speed", ja: "距離 ÷ 時間 = 速度", es: "Distancia ÷ tiempo = velocidad", "pt-BR": "Distância ÷ tempo = velocidade", de: "Strecke ÷ Zeit = Geschwindigkeit", fr: "Distance ÷ temps = vitesse" }, expression: "1km ÷ 1min", targetUnit: "km/h" },
  { id: "kine", category: "motion", title: { en: "Convert kine", ja: "kineを換算", es: "Convertir kine", "pt-BR": "Converter kine", de: "Kine umrechnen", fr: "Convertir le kine" }, description: { en: "Convert the CGS speed unit to SI speed", ja: "CGS速度単位をSI速度へ", es: "Convierte la unidad de velocidad CGS al SI", "pt-BR": "Converte a unidade de velocidade CGS para o SI", de: "CGS-Geschwindigkeitseinheit in SI umrechnen", fr: "Convertir l'unité de vitesse CGS en unité SI" }, expression: "100kine", targetUnit: "km/h" },
  { id: "distance", category: "motion", title: { en: "Find distance", ja: "距離を求める", es: "Calcular la distancia", "pt-BR": "Calcular a distância", de: "Strecke berechnen", fr: "Calculer la distance" }, description: { en: "Speed × time = distance", ja: "速度 × 時間 = 距離", es: "Velocidad × tiempo = distancia", "pt-BR": "Velocidade × tempo = distância", de: "Geschwindigkeit × Zeit = Strecke", fr: "Vitesse × temps = distance" }, expression: "10m/s × 2min", targetUnit: "km" },
  { id: "time", category: "motion", title: { en: "Find time", ja: "時間を求める", es: "Calcular el tiempo", "pt-BR": "Calcular o tempo", de: "Zeit berechnen", fr: "Calculer le temps" }, description: { en: "Distance ÷ speed = time", ja: "距離 ÷ 速度 = 時間", es: "Distancia ÷ velocidad = tiempo", "pt-BR": "Distância ÷ velocidade = tempo", de: "Strecke ÷ Geschwindigkeit = Zeit", fr: "Distance ÷ vitesse = temps" }, expression: "1km ÷ 5m/s", targetUnit: "min" },
  { id: "sine-degrees", category: "math", title: { en: "Sine in degrees", ja: "度数法の正弦", es: "Seno en grados", "pt-BR": "Seno em graus", de: "Sinus in Grad", fr: "Sinus en degrés" }, description: { en: "Calculate the dimensionless sine of 30 degrees", ja: "30度のsinを無次元値として計算", es: "Calcula el seno adimensional de 30 grados", "pt-BR": "Calcula o seno adimensional de 30 graus", de: "Den dimensionslosen Sinus von 30 Grad berechnen", fr: "Calculer le sinus (sans dimension) de 30 degrés" }, expression: "sin(30deg)", targetUnit: "" },
  { id: "atan2-angle", category: "math", title: { en: "Find an angle from two sides", ja: "2辺から角度を求める", es: "Calcular un ángulo a partir de dos lados", "pt-BR": "Calcular um ângulo a partir de dois lados", de: "Winkel aus zwei Seiten berechnen", fr: "Calculer un angle à partir de deux côtés" }, description: { en: "Use atan2 with two values of the same dimension", ja: "atan2で同じ次元の2辺から角度を出す", es: "Usa atan2 con dos valores de la misma dimensión", "pt-BR": "Use atan2 com dois valores da mesma dimensão", de: "atan2 mit zwei Werten derselben Dimension verwenden", fr: "Utiliser atan2 avec deux valeurs de même dimension" }, expression: "atan2(1m, 1m)", targetUnit: "deg" },
  { id: "logarithm", category: "math", title: { en: "Base-10 logarithm", ja: "常用対数", es: "Logaritmo en base 10", "pt-BR": "Logaritmo na base 10", de: "Zehnerlogarithmus", fr: "Logarithme en base 10" }, description: { en: "Calculate the base-10 logarithm of 1000", ja: "1000の常用対数を計算", es: "Calcula el logaritmo en base 10 de 1000", "pt-BR": "Calcula o logaritmo na base 10 de 1000", de: "Den Zehnerlogarithmus von 1000 berechnen", fr: "Calculer le logarithme en base 10 de 1000" }, expression: "log(1000)", targetUnit: "" },
  { id: "square-root-area", category: "math", title: { en: "Square root of area", ja: "面積の平方根", es: "Raíz cuadrada de un área", "pt-BR": "Raiz quadrada de uma área", de: "Quadratwurzel einer Fläche", fr: "Racine carrée d'une aire" }, description: { en: "Find a side length from an area", ja: "面積から一辺の長さを求める", es: "Calcula la longitud de un lado a partir de un área", "pt-BR": "Calcula o comprimento de um lado a partir de uma área", de: "Eine Seitenlänge aus einer Fläche berechnen", fr: "Calculer la longueur d'un côté à partir d'une aire" }, expression: "sqrt(144cm²)", targetUnit: "cm" },
  { id: "power-length", category: "math", title: { en: "Power of length", ja: "長さのべき乗", es: "Potencia de una longitud", "pt-BR": "Potência de um comprimento", de: "Potenz einer Länge", fr: "Puissance d'une longueur" }, description: { en: "Find volume by cubing a length", ja: "長さの3乗から体積を求める", es: "Calcula el volumen elevando una longitud al cubo", "pt-BR": "Calcula o volume elevando um comprimento ao cubo", de: "Das Volumen durch Kubieren einer Länge berechnen", fr: "Calculer le volume en élevant une longueur au cube" }, expression: "(2m)^3", targetUnit: "m³" },
  { id: "force", category: "mechanics", title: { en: "Find force", ja: "力を求める", es: "Calcular la fuerza", "pt-BR": "Calcular a força", de: "Kraft berechnen", fr: "Calculer la force" }, description: { en: "Mass × acceleration = force", ja: "質量 × 加速度 = 力", es: "Masa × aceleración = fuerza", "pt-BR": "Massa × aceleração = força", de: "Masse × Beschleunigung = Kraft", fr: "Masse × accélération = force" }, expression: "2kg × 9.8m/s²", targetUnit: "N" },
  { id: "standard-gravity", category: "mechanics", title: { en: "Convert standard gravity", ja: "標準重力を換算", es: "Convertir la gravedad estándar", "pt-BR": "Converter a gravidade padrão", de: "Normfallbeschleunigung umrechnen", fr: "Convertir la gravité standard" }, description: { en: "Convert 1G to Gal for gravimetry", ja: "1G を地球物理で用いる Gal へ", es: "Convierte 1G a Gal para gravimetría", "pt-BR": "Converte 1G para Gal para gravimetria", de: "1G für die Gravimetrie in Gal umrechnen", fr: "Convertir 1G en Gal pour la gravimétrie" }, expression: "1G", targetUnit: "Gal" },
  { id: "pressure", category: "mechanics", title: { en: "Find pressure", ja: "圧力を求める", es: "Calcular la presión", "pt-BR": "Calcular a pressão", de: "Druck berechnen", fr: "Calculer la pression" }, description: { en: "Force ÷ area = pressure", ja: "力 ÷ 面積 = 圧力", es: "Fuerza ÷ área = presión", "pt-BR": "Força ÷ área = pressão", de: "Kraft ÷ Fläche = Druck", fr: "Force ÷ aire = pression" }, expression: "100N ÷ 0.01m²", targetUnit: "kPa" },
  { id: "work", category: "energy", title: { en: "Find energy", ja: "仕事を求める", es: "Calcular la energía", "pt-BR": "Calcular a energia", de: "Energie berechnen", fr: "Calculer l'énergie" }, description: { en: "Force × distance = energy", ja: "力 × 距離 = エネルギー", es: "Fuerza × distancia = energía", "pt-BR": "Força × distância = energia", de: "Kraft × Strecke = Energie", fr: "Force × distance = énergie" }, expression: "250N × 4m", targetUnit: "kJ" },
  { id: "power", category: "energy", title: { en: "Find power", ja: "仕事率を求める", es: "Calcular la potencia", "pt-BR": "Calcular a potência", de: "Leistung berechnen", fr: "Calculer la puissance" }, description: { en: "Energy ÷ time = power", ja: "エネルギー ÷ 時間 = 電力", es: "Energía ÷ tiempo = potencia", "pt-BR": "Energia ÷ tempo = potência", de: "Energie ÷ Zeit = Leistung", fr: "Énergie ÷ temps = puissance" }, expression: "1200J ÷ 2min", targetUnit: "W" },
  { id: "electric-power", category: "electric", title: { en: "Electric power", ja: "電力を求める", es: "Potencia eléctrica", "pt-BR": "Potência elétrica", de: "Elektrische Leistung", fr: "Puissance électrique" }, description: { en: "Voltage × current = power", ja: "電圧 × 電流 = 電力", es: "Voltaje × corriente = potencia", "pt-BR": "Tensão × corrente = potência", de: "Spannung × Stromstärke = Leistung", fr: "Tension × courant = puissance" }, expression: "12V × 2A", targetUnit: "W" },
  { id: "percentage", category: "ratio", title: { en: "Convert to a percentage", ja: "割合を百分率へ", es: "Convertir a porcentaje", "pt-BR": "Converter para porcentagem", de: "In Prozent umrechnen", fr: "Convertir en pourcentage" }, description: { en: "Display a dimensionless value as %", ja: "無次元値を % で表示", es: "Muestra un valor adimensional como %", "pt-BR": "Exibe um valor adimensional como %", de: "Einen dimensionslosen Wert als % anzeigen", fr: "Afficher une valeur sans dimension en %" }, expression: "0.125", targetUnit: "%" },
  // ここから下は各言語版のターゲット層の「決定的な瞬間」に合わせたサンプル
  // （docs/target-users-by-locale-2026-09.md 第1節）。1つのサンプル表を6言語で共有するので、
  // 式は共通のまま、説明文でその層が実際に落とす桁・見落とす換算を名指ししている。
  { id: "prefix-chain", category: "exam", title: { en: "Prefixes that cancel (k × m)", ja: "接頭語の打ち消し（k × m）", es: "Prefijos que se cancelan (k × m)", "pt-BR": "Prefixos que se cancelam (k × m)", de: "Vorsatzzeichen kürzen (k × m)", fr: "Préfixes qui s'annulent (k × m)" }, description: { en: "kΩ × mA gives volts: the k and the m cancel out", ja: "kΩ × mA は k と m が打ち消えて V になる", es: "kΩ × mA da voltios: la k y la m se cancelan", "pt-BR": "kΩ × mA dá volts: o k e o m se cancelam", de: "kΩ × mA ergibt Volt – k und m kürzen sich weg (Zehnerpotenzen)", fr: "kΩ × mA donne des volts : le k et le m s'annulent" }, expression: "4.7kΩ × 2mA", targetUnit: "V" },
  { id: "micro-prefix-charge", category: "exam", title: { en: "Charge from µF and V", ja: "µFとVから電荷を出す", es: "Carga a partir de µF y V", "pt-BR": "Carga a partir de µF e V", de: "Ladung aus µF und V", fr: "Charge à partir de µF et V" }, description: { en: "µ jumps six decades: the answer lands in mC, not C", ja: "µは6桁分。答えはCではなくmCの桁に落ちる", es: "µ salta seis décadas: el resultado queda en mC, no en C", "pt-BR": "µ salta seis décadas: o resultado fica em mC, não em C", de: "µ überspringt sechs Zehnerpotenzen – das Ergebnis liegt bei mC, nicht C", fr: "µ saute six décades : le résultat tombe en mC, pas en C" }, expression: "470µF × 12V", targetUnit: "mC" },
  { id: "kmh-to-ms", category: "exam", title: { en: "km/h to m/s", ja: "km/h を m/s へ", es: "km/h a m/s", "pt-BR": "km/h para m/s", de: "km/h in m/s", fr: "km/h en m/s" }, description: { en: "The conversion every physics exam opens with (÷ 3.6)", ja: "物理の試験で最初に問われる換算（÷3.6）", es: "La conversión con la que empieza cualquier examen de física (÷ 3,6)", "pt-BR": "A conversão com que todo exame de física começa (÷ 3,6)", de: "Die Umrechnung, mit der jede Physik-Klausur beginnt (÷ 3,6)", fr: "La conversion par laquelle commence chaque épreuve de physique (÷ 3,6)" }, expression: "72km/h", targetUnit: "m/s" },
  { id: "three-phase-power", category: "exam", title: { en: "Three-phase power", ja: "三相電力", es: "Potencia trifásica", "pt-BR": "Potência trifásica", de: "Drehstromleistung", fr: "Puissance triphasée" }, description: { en: "√3 × line voltage × current × power factor", ja: "√3 × 線間電圧 × 電流 × 力率", es: "√3 × tensión de línea × corriente × factor de potencia", "pt-BR": "√3 × tensão de linha × corrente × fator de potência", de: "√3 × Netzspannung × Strom × Leistungsfaktor", fr: "√3 × tension entre phases × courant × facteur de puissance" }, expression: "sqrt(3) × 200V × 10A × 0.8", targetUnit: "kW" },
  { id: "energy-kwh", category: "exam", title: { en: "Energy in kWh", ja: "消費電力量（kWh）", es: "Energía en kWh", "pt-BR": "Energia em kWh", de: "Energie in kWh", fr: "Énergie en kWh" }, description: { en: "Watts × hours is already kWh once the units are kept", ja: "単位を持たせたまま W × h を掛ければそのまま kWh になる", es: "Vatios × horas ya es kWh si se conservan las unidades", "pt-BR": "Watts × horas já é kWh se as unidades forem mantidas", de: "Watt × Stunden ergibt direkt kWh, wenn man die Einheiten mitführt", fr: "Watts × heures donne directement des kWh si l'on garde les unités" }, expression: "100W × 3h", targetUnit: "kWh" },
  { id: "density-si", category: "lab", title: { en: "Density to SI", ja: "密度をSIへ", es: "Densidad al SI", "pt-BR": "Densidade para o SI", de: "Dichte in SI", fr: "Masse volumique en SI" }, description: { en: "g/cm³ to kg/m³ is a factor of 1000, not 100", ja: "g/cm³ から kg/m³ は100倍ではなく1000倍", es: "De g/cm³ a kg/m³ el factor es 1000, no 100", "pt-BR": "De g/cm³ para kg/m³ o fator é 1000, não 100", de: "Von g/cm³ auf kg/m³ ist der Faktor 1000, nicht 100", fr: "De g/cm³ à kg/m³, le facteur est 1000, pas 100" }, expression: "1.2g/cm³", targetUnit: "kg/m³" },
  { id: "molar-concentration", category: "lab", title: { en: "Concentration from mL", ja: "mLから濃度を出す", es: "Concentración a partir de mL", "pt-BR": "Concentração a partir de mL", de: "Konzentration aus mL", fr: "Concentration à partir de mL" }, description: { en: "Forget to turn mL into L and the concentration is off by 1000", ja: "mLをLに直し忘れると濃度が1000倍ずれる", es: "Si olvidas convertir mL a L, la concentración se desvía 1000 veces", "pt-BR": "Se esquecer de converter mL para L, a concentração erra por 1000", de: "Wird mL nicht in L umgerechnet, ist die Konzentration um den Faktor 1000 falsch", fr: "Si l'on oublie de convertir les mL en L, la concentration est fausse d'un facteur 1000" }, expression: "0.5mol ÷ 250mL", targetUnit: "mol/L" },
  { id: "celsius-to-kelvin", category: "lab", title: { en: "Celsius to kelvin", ja: "摂氏をケルビンへ", es: "Celsius a kelvin", "pt-BR": "Celsius para kelvin", de: "Celsius in Kelvin", fr: "Celsius en kelvin" }, description: { en: "Gas-law problems need the absolute temperature", ja: "気体の法則は絶対温度で計算する", es: "Los problemas de gases exigen temperatura absoluta", "pt-BR": "Problemas de gases exigem temperatura absoluta", de: "Gasgesetze brauchen die absolute Temperatur", fr: "Les lois des gaz exigent la température absolue" }, expression: "25°C", targetUnit: "K" },
];
