import type { LocalizedText } from "./i18n";

export type UnitExplanation = {
  symbol: string;
  name: LocalizedText;
  summary: LocalizedText;
  siConversion: string;
  usage: LocalizedText;
};

export const SPECIAL_UNIT_EXPLANATIONS: Record<string, UnitExplanation> = {
  mpg: {
    symbol: "mpg",
    name: { ja: "マイル毎米ガロン", en: "Mile per US gallon", es: "Milla por galón estadounidense", "pt-BR": "Milha por galão americano", de: "Meile pro US-Gallone", fr: "Mile par gallon américain" },
    summary: {
      ja: "米国の燃費です。米ガロン(3.785L)と英ガロン(4.546L)は別物で、同じ「mpg」でも約20%違います。英国式は mpg (imp) を選んでください。",
      en: "Fuel economy in the US. A US gallon (3.785 L) is not an imperial gallon (4.546 L), so the same \"mpg\" differs by about 20%. Pick mpg (imp) for the UK figure.",
      es: "Consumo de combustible en EE. UU. El galón estadounidense (3,785 L) no es el imperial (4,546 L): el mismo «mpg» difiere un 20 %. Usa mpg (imp) para el dato británico.",
      "pt-BR": "Consumo de combustível nos EUA. O galão americano (3,785 L) não é o imperial (4,546 L): o mesmo \"mpg\" difere cerca de 20%. Use mpg (imp) para o valor britânico.",
      de: "Kraftstoffverbrauch in den USA. Eine US-Gallone (3,785 l) ist keine britische Gallone (4,546 l) – dasselbe \"mpg\" unterscheidet sich um rund 20 %. Für britische Angaben mpg (imp) wählen.",
      fr: "Consommation aux États-Unis. Le gallon américain (3,785 L) n'est pas le gallon impérial (4,546 L) : le même « mpg » diffère d'environ 20 %. Choisissez mpg (imp) pour la valeur britannique.",
    },
    siConversion: "1 mpg = 1 mi / 1 US gal ≈ 0.425144 km/L",
    usage: {
      ja: "米国の車のカタログ燃費、走行コストの比較",
      en: "US vehicle fuel-economy ratings and running-cost comparisons",
      es: "Consumo homologado de vehículos en EE. UU. y comparación de costes",
      "pt-BR": "Consumo homologado de veículos nos EUA e comparação de custos",
      de: "Verbrauchsangaben US-amerikanischer Fahrzeuge und Kostenvergleiche",
      fr: "Consommation homologuée des véhicules américains et comparaison des coûts",
    },
  },
  mpgUK: {
    symbol: "mpgUK",
    name: { ja: "マイル毎英ガロン", en: "Mile per imperial gallon", es: "Milla por galón imperial", "pt-BR": "Milha por galão imperial", de: "Meile pro britische Gallone", fr: "Mile par gallon impérial" },
    summary: {
      ja: "英国の燃費です。英ガロンは4.546Lで米ガロンより大きいため、同じ車でも米国式より約20%大きい数字になります。",
      en: "Fuel economy in the UK. An imperial gallon is 4.546 L, larger than a US gallon, so the same car reads about 20% higher than in US mpg.",
      es: "Consumo en el Reino Unido. El galón imperial es de 4,546 L, mayor que el estadounidense, así que el mismo coche da una cifra un 20 % más alta.",
      "pt-BR": "Consumo no Reino Unido. O galão imperial tem 4,546 L, maior que o americano, então o mesmo carro indica cerca de 20% mais.",
      de: "Kraftstoffverbrauch im Vereinigten Königreich. Eine britische Gallone hat 4,546 l und ist größer als die US-Gallone, daher liegt derselbe Wagen rund 20 % höher.",
      fr: "Consommation au Royaume-Uni. Le gallon impérial fait 4,546 L, plus grand que l'américain : la même voiture affiche environ 20 % de plus.",
    },
    siConversion: "1 mpg (imp) = 1 mi / 1 imp gal ≈ 0.354006 km/L",
    usage: {
      ja: "英国の車のカタログ燃費（給油はリットル、燃費はmpg表記）",
      en: "UK vehicle fuel-economy ratings (fuel sold in litres, economy quoted in mpg)",
      es: "Consumo homologado de vehículos británicos (combustible en litros, consumo en mpg)",
      "pt-BR": "Consumo homologado de veículos britânicos (combustível em litros, consumo em mpg)",
      de: "Verbrauchsangaben britischer Fahrzeuge (Kraftstoff in Litern, Verbrauch in mpg)",
      fr: "Consommation homologuée des véhicules britanniques (carburant en litres, consommation en mpg)",
    },
  },
  PS: {
    symbol: "PS",
    name: { ja: "メートル馬力", en: "Metric horsepower", es: "Caballo de vapor", "pt-BR": "Cavalo-vapor", de: "Pferdestärke", fr: "Cheval-vapeur" },
    summary: {
      ja: "75kgを毎秒1m持ち上げる仕事率です。独語圏のPSと仏語圏のCVは同じ単位で、英馬力hp（745.7W）とは約1.4%ずれます。",
      en: "The power needed to lift 75 kg by one metre in one second. German PS and French CV are the same unit, about 1.4% smaller than mechanical horsepower (hp).",
      es: "La potencia necesaria para elevar 75 kg un metro en un segundo. El PS alemán y el CV francés son la misma unidad, un 1,4 % menor que el hp imperial.",
      "pt-BR": "A potência necessária para elevar 75 kg em um metro por segundo. O PS alemão e o CV francês são a mesma unidade, cerca de 1,4% menor que o hp imperial.",
      de: "Die Leistung, um 75 kg in einer Sekunde einen Meter zu heben. Das deutsche PS und das französische CV sind dieselbe Einheit und rund 1,4 % kleiner als die britische Horsepower (hp).",
      fr: "La puissance nécessaire pour élever 75 kg d'un mètre en une seconde. Le CV français et le PS allemand sont la même unité, environ 1,4 % plus petite que le horsepower anglais (hp).",
    },
    siConversion: "1 PS = 1 CV = 735.49875 W",
    usage: {
      ja: "自動車・二輪のエンジン出力（独・仏・日のカタログ値）",
      en: "Engine output in German, French, and Japanese vehicle specifications",
      es: "Potencia de motores en fichas técnicas de Europa continental",
      "pt-BR": "Potência de motores em fichas técnicas da Europa continental",
      de: "Motorleistung in Fahrzeugdaten (Deutschland, Frankreich, Japan)",
      fr: "Puissance moteur dans les fiches techniques (France, Allemagne, Japon)",
    },
  },
  Gal: {
    symbol: "Gal",
    name: { ja: "ガル", en: "Gal", es: "Gal", "pt-BR": "Gal", de: "Gal", fr: "Gal" },
    summary: {
      ja: "測地・地球物理で使われる加速度単位です。",
      en: "An acceleration unit used in geodesy and geophysics.",
      es: "Una unidad de aceleración utilizada en geodesia y geofísica.",
      "pt-BR": "Uma unidade de aceleração usada em geodésia e geofísica.",
      de: "Eine in der Geodäsie und Geophysik verwendete Beschleunigungseinheit.",
      fr: "Une unité d'accélération utilisée en géodésie et en géophysique.",
    },
    siConversion: "1 Gal = 0.01 m/s²",
    usage: {
      ja: "重力・地震・地盤の微小な加速度変化",
      en: "Gravity, earthquakes, and small ground-motion changes",
      es: "Gravedad, terremotos y pequeños cambios en el movimiento del suelo",
      "pt-BR": "Gravidade, terremotos e pequenas variações no movimento do solo",
      de: "Schwerkraft, Erdbeben und kleine Bodenbewegungsänderungen",
      fr: "Gravité, séismes et petites variations du mouvement du sol",
    },
  },
  mGal: {
    symbol: "mGal",
    name: { ja: "ミリガル", en: "Milligal", es: "Miligal", "pt-BR": "Miligal", de: "Milligal", fr: "Milligal" },
    summary: {
      ja: "Galの1,000分の1で、重力変化の表現に使われます。",
      en: "One thousandth of a Gal, used for gravity variations.",
      es: "Una milésima parte de un Gal, utilizada para expresar variaciones de gravedad.",
      "pt-BR": "Um milésimo de um Gal, usado para expressar variações de gravidade.",
      de: "Ein Tausendstel eines Gal, verwendet zur Darstellung von Schwereänderungen.",
      fr: "Un millième de Gal, utilisé pour exprimer les variations de gravité.",
    },
    siConversion: "1 mGal = 1×10⁻⁵ m/s²",
    usage: {
      ja: "重力探査・地殻変動",
      en: "Gravity surveys and crustal deformation",
      es: "Prospección gravimétrica y deformación cortical",
      "pt-BR": "Levantamentos gravimétricos e deformação crustal",
      de: "Schweremessungen und Krustendeformation",
      fr: "Prospection gravimétrique et déformation crustale",
    },
  },
  "µGal": {
    symbol: "µGal",
    name: { ja: "マイクロガル", en: "Microgal", es: "Microgal", "pt-BR": "Microgal", de: "Mikrogal", fr: "Microgal" },
    summary: {
      ja: "Galの100万分の1で、非常に小さな重力変化を表します。",
      en: "One millionth of a Gal for very small gravity variations.",
      es: "Una millonésima parte de un Gal para variaciones de gravedad muy pequeñas.",
      "pt-BR": "Um milionésimo de um Gal para variações de gravidade muito pequenas.",
      de: "Ein Millionstel eines Gal für sehr kleine Schwereänderungen.",
      fr: "Un millionième de Gal pour de très petites variations de gravité.",
    },
    siConversion: "1 µGal = 1×10⁻⁸ m/s²",
    usage: {
      ja: "高精度重力計測",
      en: "High-precision gravimetry",
      es: "Gravimetría de alta precisión",
      "pt-BR": "Gravimetria de alta precisão",
      de: "Hochpräzise Gravimetrie",
      fr: "Gravimétrie de haute précision",
    },
  },
  G: {
    symbol: "G",
    name: { ja: "標準重力", en: "Standard gravity", es: "Gravedad estándar", "pt-BR": "Gravidade padrão", de: "Normfallbeschleunigung", fr: "Gravité normale" },
    summary: {
      ja: "地球上の基準加速度を表す慣用単位です。",
      en: "A conventional unit representing standard Earth gravity.",
      es: "Una unidad convencional que representa la gravedad terrestre estándar.",
      "pt-BR": "Uma unidade convencional que representa a gravidade terrestre padrão.",
      de: "Eine konventionelle Einheit für die Standard-Erdbeschleunigung.",
      fr: "Une unité conventionnelle représentant la gravité terrestre normale.",
    },
    siConversion: "1 G = 9.80665 m/s²",
    usage: {
      ja: "加速度計・振動・G荷重",
      en: "Accelerometers, vibration, and G-loads",
      es: "Acelerómetros, vibraciones y cargas G",
      "pt-BR": "Acelerômetros, vibração e cargas G",
      de: "Beschleunigungssensoren, Vibrationen und G-Lasten",
      fr: "Accéléromètres, vibrations et charges G",
    },
  },
  g0: {
    symbol: "g0",
    name: { ja: "標準重力", en: "Standard gravity", es: "Gravedad estándar", "pt-BR": "Gravidade padrão", de: "Normfallbeschleunigung", fr: "Gravité normale" },
    summary: {
      ja: "Gと同じ標準重力を明示する別記法です。",
      en: "An alternate notation for the same standard gravity as G.",
      es: "Una notación alternativa para la misma gravedad estándar que G.",
      "pt-BR": "Uma notação alternativa para a mesma gravidade padrão representada por G.",
      de: "Eine alternative Schreibweise für dieselbe Normfallbeschleunigung wie G.",
      fr: "Une notation alternative pour désigner la même gravité normale que G.",
    },
    siConversion: "1 g0 = 9.80665 m/s²",
    usage: {
      ja: "科学・技術文書",
      en: "Scientific and technical documentation",
      es: "Documentación científica y técnica",
      "pt-BR": "Documentação científica e técnica",
      de: "Wissenschaftliche und technische Dokumentation",
      fr: "Documentation scientifique et technique",
    },
  },
  kine: {
    symbol: "kine",
    name: { ja: "カイン", en: "Kine", es: "Kine", "pt-BR": "Kine", de: "Kine", fr: "Kine" },
    summary: {
      ja: "CGS系で使われる速度単位です。",
      en: "A speed unit used in the CGS system.",
      es: "Una unidad de velocidad utilizada en el sistema CGS.",
      "pt-BR": "Uma unidade de velocidade usada no sistema CGS.",
      de: "Eine im CGS-System verwendete Geschwindigkeitseinheit.",
      fr: "Une unité de vitesse utilisée dans le système CGS.",
    },
    siConversion: "1 kine = 1 cm/s = 0.01 m/s",
    usage: {
      ja: "古いCGS系の科学・工学資料",
      en: "Legacy CGS scientific and engineering sources",
      es: "Fuentes científicas y técnicas antiguas del sistema CGS",
      "pt-BR": "Fontes científicas e técnicas antigas do sistema CGS",
      de: "Ältere wissenschaftliche und technische Quellen im CGS-System",
      fr: "Anciennes sources scientifiques et techniques du système CGS",
    },
  },
  kt: {
    symbol: "kt",
    name: { ja: "ノット", en: "Knot", es: "Nudo", "pt-BR": "Nó", de: "Knoten", fr: "Nœud" },
    summary: {
      ja: "海里毎時で表す航海・航空の速度単位です。",
      en: "A nautical and aviation speed unit expressed in nautical miles per hour.",
      es: "Una unidad de velocidad náutica y aeronáutica expresada en millas náuticas por hora.",
      "pt-BR": "Uma unidade de velocidade náutica e aeronáutica expressa em milhas náuticas por hora.",
      de: "Eine in der Seefahrt und Luftfahrt verwendete Geschwindigkeitseinheit in Seemeilen pro Stunde.",
      fr: "Une unité de vitesse maritime et aéronautique exprimée en milles marins par heure.",
    },
    siConversion: "1 kt = 0.514444444 m/s",
    usage: {
      ja: "船舶・航空・気象",
      en: "Marine, aviation, and meteorology",
      es: "Navegación marítima, aviación y meteorología",
      "pt-BR": "Navegação marítima, aviação e meteorologia",
      de: "Schifffahrt, Luftfahrt und Meteorologie",
      fr: "Navigation maritime, aviation et météorologie",
    },
  },
  mph: {
    symbol: "mph",
    name: { ja: "マイル毎時", en: "Miles per hour", es: "Millas por hora", "pt-BR": "Milhas por hora", de: "Meilen pro Stunde", fr: "Miles par heure" },
    summary: {
      ja: "1時間に進むマイル数で表す速度単位です。",
      en: "A speed unit expressed in miles travelled per hour.",
      es: "Una unidad de velocidad expresada en millas recorridas por hora.",
      "pt-BR": "Uma unidade de velocidade expressa em milhas percorridas por hora.",
      de: "Eine Geschwindigkeitseinheit, ausgedrückt in zurückgelegten Meilen pro Stunde.",
      fr: "Une unité de vitesse exprimée en miles parcourus par heure.",
    },
    siConversion: "1 mph = 0.44704 m/s",
    usage: {
      ja: "米国・英国の道路速度",
      en: "Road speeds in the US and UK",
      es: "Velocidades en carretera en EE. UU. y Reino Unido",
      "pt-BR": "Velocidades rodoviárias nos EUA e no Reino Unido",
      de: "Straßengeschwindigkeiten in den USA und im Vereinigten Königreich",
      fr: "Vitesses routières aux États-Unis et au Royaume-Uni",
    },
  },
  "ft/s": {
    symbol: "ft/s",
    name: { ja: "フィート毎秒", en: "Feet per second", es: "Pies por segundo", "pt-BR": "Pés por segundo", de: "Fuß pro Sekunde", fr: "Pieds par seconde" },
    summary: {
      ja: "1秒に進むフィート数で表す速度単位です。",
      en: "A speed unit expressed in feet travelled per second.",
      es: "Una unidad de velocidad expresada en pies recorridos por segundo.",
      "pt-BR": "Uma unidade de velocidade expressa em pés percorridos por segundo.",
      de: "Eine Geschwindigkeitseinheit, ausgedrückt in zurückgelegten Fuß pro Sekunde.",
      fr: "Une unité de vitesse exprimée en pieds parcourus par seconde.",
    },
    siConversion: "1 ft/s = 0.3048 m/s",
    usage: {
      ja: "工学・航空・流体計測",
      en: "Engineering, aviation, and flow measurement",
      es: "Ingeniería, aviación y medición de flujo",
      "pt-BR": "Engenharia, aviação e medição de vazão",
      de: "Technik, Luftfahrt und Strömungsmessung",
      fr: "Ingénierie, aviation et mesure de débit",
    },
  },
};

export function getUnitExplanation(symbol: string): UnitExplanation | undefined {
  return SPECIAL_UNIT_EXPLANATIONS[symbol];
}
