import type { NotebookSeed } from "../types";

/**
 * 材料試験のカテゴリ。試験片から材料の値（降伏点・引張強さ・ヤング率・硬さ・衝撃値）を読み出す計算で、
 * 出てきた σ_y・σ_B は「応力・ひずみ・安全率」や「疲労・破壊力学」のノートにそのまま持ち込める。
 * 既定値は規格の標準試験片（ASTM E8/E8M の Ø12.5mm 丸棒、ASTM E23 のVノッチ、ASTM C39 のφ100×200）
 * と、それに見合う実在の材料（機械構造用炭素鋼 S45C・AISI 1045 相当）から取っている。
 */
export const ENG_TESTING_SEEDS: NotebookSeed[] = [
  {
    title: { en: "Tensile test: yield, tensile strength, elongation & reduction of area", ja: "引張試験：降伏点・引張強さ・破断伸び・絞り", es: "Ensayo de tracción: límite elástico, resistencia a la tracción, alargamiento a la rotura y estricción", "pt-BR": "Ensaio de tração: tensão de escoamento, resistência à tração, alongamento após a ruptura e estricção", de: "Zugversuch: Streckgrenze, Zugfestigkeit, Bruchdehnung und Brucheinschnürung", fr: "Essai de traction : limite d'élasticité, résistance à la traction, allongement après rupture et striction" },
    description: { en: "A standard ASTM E8/E8M round specimen (Ø12.5 mm, 50 mm gauge length) of AISI 1045 steel yields at 40 kN and breaks after a maximum load of 76.7 kN. The marks end up 58.5 mm apart and the neck shrinks to Ø8.9 mm. Dividing the loads by the original cross-section gives the engineering yield and tensile strengths; the two percentages describe ductility.", ja: "ASTM E8/E8M の標準丸棒試験片（直径12.5mm・標点距離50mm）でS45C相当の炭素鋼を引っ張り、40kNで降伏、最大荷重76.7kNで破断した場合です。破断後の標点間は58.5mm、くびれた部分の直径は8.9mmでした。荷重を元の断面積で割ると降伏点と引張強さが、2つの百分率から延性が分かります。", es: "Una probeta redonda normalizada ASTM E8/E8M (Ø12,5 mm, longitud calibrada de 50 mm) de acero AISI 1045 cede a 40 kN y rompe con una carga máxima de 76,7 kN. Las marcas quedan separadas 58,5 mm y la estricción reduce el diámetro a Ø8,9 mm. Al dividir las cargas entre la sección transversal original se obtienen el límite elástico y la resistencia a la tracción de ingeniería; los dos porcentajes describen la ductilidad.", "pt-BR": "Um corpo de prova redondo padronizado ASTM E8/E8M (Ø12,5 mm, comprimento de referência de 50 mm) de aço AISI 1045 escoa a 40 kN e rompe após uma carga máxima de 76,7 kN. As marcas ficam 58,5 mm distantes e a região estrangulada reduz-se a Ø8,9 mm. Dividir as cargas pela seção transversal original dá as tensões nominais de escoamento e de resistência à tração; as duas porcentagens descrevem a ductilidade.", de: "Ein genormter Rundstab nach ASTM E8/E8M (Ø12,5 mm, Messlänge 50 mm) aus Stahl AISI 1045 beginnt bei 40 kN zu fließen und reißt nach einer Höchstlast von 76,7 kN. Die Messmarken liegen danach 58,5 mm auseinander, und die Einschnürung verjüngt sich auf Ø8,9 mm. Teilt man die Lasten durch den Ausgangsquerschnitt, erhält man die technische Streckgrenze und Zugfestigkeit; die beiden Prozentwerte beschreiben die Duktilität.", fr: "Une éprouvette cylindrique normalisée ASTM E8/E8M (Ø12,5 mm, longueur de référence 50 mm) en acier AISI 1045 atteint sa limite d'élasticité à 40 kN et rompt après une charge maximale de 76,7 kN. Les repères sont alors distants de 58,5 mm et la zone de striction se réduit à Ø8,9 mm. En divisant les charges par la section initiale, on obtient la limite d'élasticité et la résistance à la traction conventionnelles ; les deux pourcentages décrivent la ductilité." },
    // 下付きの y は Unicode に無いので、このノートの記号は全部 ASCII の `_` に寄せる（CLAUDE.md の表記ルール）。
    localConstants: [
      { symbol: "d_0", expression: "12.5mm" },
      { symbol: "L_0", expression: "50.0mm" },
      { symbol: "F_y", expression: "40.0kN" },
      { symbol: "F_m", expression: "76.7kN" },
      { symbol: "L_u", expression: "58.5mm" },
      { symbol: "d_u", expression: "8.90mm" },
    ],
    steps: [
      { title: { en: "Original cross-section A_0", ja: "元の断面積 A_0", es: "Sección transversal original A_0", "pt-BR": "Seção transversal original A_0", de: "Ursprünglicher Querschnitt A_0", fr: "Section initiale A_0" }, expression: "π*d_0^2/4", targetUnit: "mm²", resultSymbol: "A_0", formulaLatex: "A_0 = \\dfrac{\\pi d_0^2}{4}" },
      { title: { en: "Yield strength σ_y", ja: "降伏点 σ_y", es: "Límite elástico σ_y", "pt-BR": "Tensão de escoamento σ_y", de: "Streckgrenze σ_y", fr: "Limite d'élasticité σ_y" }, expression: "F_y/A_0", targetUnit: "MPa", formulaLatex: "\\sigma_y = \\dfrac{F_y}{A_0}" },
      { title: { en: "Tensile strength σ_B", ja: "引張強さ σ_B", es: "Resistencia a la tracción σ_B", "pt-BR": "Resistência à tração σ_B", de: "Zugfestigkeit σ_B", fr: "Résistance à la traction σ_B" }, expression: "F_m/A_0", targetUnit: "MPa", formulaLatex: "\\sigma_B = \\dfrac{F_m}{A_0}" },
      { title: { en: "Elongation after fracture", ja: "破断伸び", es: "Alargamiento a la rotura", "pt-BR": "Alongamento após a ruptura", de: "Bruchdehnung", fr: "Allongement après rupture" }, expression: "(L_u-L_0)/L_0", targetUnit: "%", formulaLatex: "\\delta = \\dfrac{L_u - L_0}{L_0}" },
      { title: { en: "Reduction of area", ja: "絞り", es: "Estricción", "pt-BR": "Estricção (redução de área)", de: "Brucheinschnürung", fr: "Striction (coefficient de striction)" }, expression: "1-(d_u/d_0)^2", targetUnit: "%", formulaLatex: "\\varphi = \\dfrac{A_0 - A_u}{A_0} = 1 - \\left(\\dfrac{d_u}{d_0}\\right)^2" },
    ],
  },
  {
    title: { en: "Young's modulus & 0.2% proof strain from a stress–strain curve", ja: "応力-ひずみ線図からヤング率と0.2%耐力のひずみ", es: "Módulo de Young y deformación en el límite convencional del 0,2 % a partir de la curva esfuerzo-deformación", "pt-BR": "Módulo de Young e deformação no limite convencional de escoamento de 0,2% a partir da curva tensão-deformação", de: "Elastizitätsmodul und Dehnung an der 0,2 %-Dehngrenze aus dem Spannungs-Dehnungs-Diagramm", fr: "Module de Young et déformation à la limite conventionnelle d'élasticité à 0,2 % d'après la courbe contrainte-déformation" },
    description: { en: "Two points read off the straight, elastic part of a stress–strain curve give Young's modulus as the slope. Materials without a clear yield point use the 0.2% proof stress instead: the stress where a line of that slope, shifted by 0.2% strain, meets the curve. The second step gives the total strain at that point, i.e. how far along the strain axis to look.", ja: "応力-ひずみ線図の直線部分（弾性域）から2点を読むと、その傾きがヤング率になります。はっきりした降伏点が無い材料では、同じ傾きの直線をひずみ0.2%だけずらして曲線と交わる応力を0.2%耐力とします。2つ目の手順は、その点での全ひずみ＝線図の横軸のどこを見ればよいかを出します。", es: "Dos puntos leídos en el tramo recto y elástico de una curva esfuerzo-deformación dan el módulo de Young como pendiente. Los materiales sin un límite elástico definido usan en su lugar el límite convencional del 0,2 %: el esfuerzo en el que una recta de esa pendiente, desplazada un 0,2 % de deformación, corta la curva. El segundo paso da la deformación total en ese punto, es decir, hasta dónde hay que mirar en el eje de deformaciones.", "pt-BR": "Dois pontos lidos no trecho reto e elástico de uma curva tensão-deformação dão o módulo de Young como inclinação. Materiais sem um ponto de escoamento nítido usam, em vez disso, a tensão limite convencional de 0,2%: a tensão em que uma reta com essa inclinação, deslocada de 0,2% de deformação, cruza a curva. O segundo passo dá a deformação total nesse ponto, ou seja, até onde olhar no eixo das deformações.", de: "Zwei Punkte aus dem geraden, elastischen Bereich eines Spannungs-Dehnungs-Diagramms ergeben den Elastizitätsmodul als Steigung. Werkstoffe ohne ausgeprägte Streckgrenze verwenden stattdessen die 0,2 %-Dehngrenze: die Spannung, bei der eine Gerade dieser Steigung, um 0,2 % Dehnung verschoben, die Kurve schneidet. Der zweite Schritt liefert die Gesamtdehnung an diesem Punkt, also wo auf der Dehnungsachse man nachsehen muss.", fr: "Deux points relevés sur la partie rectiligne, élastique, d'une courbe contrainte-déformation donnent le module de Young comme pente. Les matériaux sans limite d'élasticité nette utilisent à la place la limite conventionnelle d'élasticité à 0,2 % : la contrainte pour laquelle une droite de cette pente, décalée de 0,2 % de déformation, coupe la courbe. La deuxième étape donne la déformation totale en ce point, c'est-à-dire où lire sur l'axe des déformations." },
    localConstants: [
      { symbol: "σ₁", expression: "40.0MPa" },
      { symbol: "ε₁", expression: "0.000200" },
      { symbol: "σ₂", expression: "200MPa" },
      { symbol: "ε₂", expression: "0.000980" },
      { symbol: "σₚ", expression: "330MPa" },
    ],
    steps: [
      { title: { en: "Young's modulus E (slope of the elastic line)", ja: "ヤング率 E（弾性域の傾き）", es: "Módulo de Young E (pendiente de la recta elástica)", "pt-BR": "Módulo de Young E (inclinação da reta elástica)", de: "Elastizitätsmodul E (Steigung der elastischen Geraden)", fr: "Module de Young E (pente de la droite élastique)" }, expression: "(σ₂-σ₁)/(ε₂-ε₁)", targetUnit: "GPa", formulaLatex: "E = \\dfrac{\\sigma_2 - \\sigma_1}{\\varepsilon_2 - \\varepsilon_1}" },
      { title: { en: "Total strain at the 0.2% proof stress", ja: "0.2%耐力での全ひずみ", es: "Deformación total en el límite convencional del 0,2 %", "pt-BR": "Deformação total na tensão limite convencional de 0,2%", de: "Gesamtdehnung an der 0,2 %-Dehngrenze", fr: "Déformation totale à la limite conventionnelle à 0,2 %" }, expression: "σₚ/E + 0.002", targetUnit: "%", formulaLatex: "\\varepsilon = \\dfrac{\\sigma_p}{E} + 0.002" },
    ],
  },
  {
    title: { en: "True stress & true strain", ja: "真応力と真ひずみ", es: "Esfuerzo real y deformación real", "pt-BR": "Tensão real e deformação real", de: "Wahre Spannung und wahre Dehnung", fr: "Contrainte vraie et déformation vraie" },
    description: { en: "Engineering stress divides by the original area, but the specimen gets thinner as it stretches. As long as it deforms uniformly (before necking) and keeps its volume, the true stress and true (logarithmic) strain follow directly from the engineering values. Here 500 MPa at 10% strain becomes 550 MPa at a true strain of 9.5%.", ja: "公称応力は元の断面積で割りますが、試験片は伸びるにつれて細くなります。くびれが始まる前（一様伸びの範囲）で体積が変わらないとみなせば、真応力と真ひずみ（対数ひずみ）は公称値からそのまま求まります。公称で500MPa・ひずみ10%のとき、真応力は550MPa、真ひずみは9.5%になります。", es: "El esfuerzo de ingeniería divide entre el área original, pero la probeta se adelgaza al alargarse. Mientras se deforme de manera uniforme (antes de la estricción) y conserve su volumen, el esfuerzo real y la deformación real (logarítmica) se obtienen directamente de los valores de ingeniería. Aquí 500 MPa con una deformación del 10 % se convierten en 550 MPa con una deformación real del 9,5 %.", "pt-BR": "A tensão de engenharia divide pela área original, mas o corpo de prova fica mais fino ao se alongar. Enquanto se deformar de modo uniforme (antes da estricção) e mantiver o volume, a tensão real e a deformação real (logarítmica) saem diretamente dos valores de engenharia. Aqui, 500 MPa com 10% de deformação viram 550 MPa com deformação real de 9,5%.", de: "Die technische Spannung bezieht sich auf den Ausgangsquerschnitt, doch der Probestab wird beim Dehnen dünner. Solange er sich gleichmäßig verformt (vor der Einschnürung) und sein Volumen behält, ergeben sich die wahre Spannung und die wahre (logarithmische) Dehnung direkt aus den technischen Werten. Hier werden aus 500 MPa bei 10 % Dehnung 550 MPa bei einer wahren Dehnung von 9,5 %.", fr: "La contrainte conventionnelle est rapportée à la section initiale, mais l'éprouvette s'amincit en s'allongeant. Tant qu'elle se déforme uniformément (avant la striction) et conserve son volume, la contrainte vraie et la déformation vraie (logarithmique) se déduisent directement des valeurs conventionnelles. Ici, 500 MPa à 10 % de déformation deviennent 550 MPa pour une déformation vraie de 9,5 %." },
    localConstants: [
      { symbol: "σₙ", expression: "500MPa" },
      { symbol: "εₙ", expression: "0.100" },
    ],
    steps: [
      { title: { en: "True stress σ_t", ja: "真応力 σ_t", es: "Esfuerzo real σ_t", "pt-BR": "Tensão real σ_t", de: "Wahre Spannung σ_t", fr: "Contrainte vraie σ_t" }, expression: "σₙ*(1+εₙ)", targetUnit: "MPa", formulaLatex: "\\sigma_t = \\sigma_n (1 + \\varepsilon_n)" },
      { title: { en: "True strain ε_t", ja: "真ひずみ ε_t", es: "Deformación real ε_t", "pt-BR": "Deformação real ε_t", de: "Wahre Dehnung ε_t", fr: "Déformation vraie ε_t" }, expression: "ln(1+εₙ)", targetUnit: "%", formulaLatex: "\\varepsilon_t = \\ln(1 + \\varepsilon_n)" },
    ],
  },
  {
    title: { en: "Vickers hardness & estimated tensile strength", ja: "ビッカース硬さと引張強さの目安", es: "Dureza Vickers y resistencia a la tracción estimada", "pt-BR": "Dureza Vickers e resistência à tração estimada", de: "Vickershärte und abgeschätzte Zugfestigkeit", fr: "Dureté Vickers et résistance à la traction estimée" },
    description: { en: "An HV10 test presses a diamond pyramid in with a 10 kgf force; the mean diagonal of the indent is 0.250 mm. Hardness is the force over the indent's surface area in kgf/mm², which works out to 0.1891·F/d² with F in newtons. For steels, the tensile strength is roughly 3.3 × HV in MPa (a rule of thumb, not a substitute for a tensile test).", ja: "HV10の試験で、10kgfの力でダイヤモンドの四角錐を押し込み、くぼみの対角線の平均が0.250mmだった場合です。ビッカース硬さは「力÷くぼみの表面積」をkgf/mm²で表した値で、力をNで書くと 0.1891·F/d² になります。鋼なら引張強さは HV の約3.3倍（MPa）が目安です（引張試験の代わりにはなりません）。", es: "Un ensayo HV10 presiona una pirámide de diamante con una fuerza de 10 kgf; la diagonal media de la huella es de 0,250 mm. La dureza es la fuerza dividida entre la superficie de la huella, en kgf/mm², lo que equivale a 0,1891·F/d² con F en newtons. En los aceros, la resistencia a la tracción es aproximadamente 3,3 × HV en MPa (una regla empírica, no un sustituto del ensayo de tracción).", "pt-BR": "Um ensaio HV10 pressiona uma pirâmide de diamante com uma força de 10 kgf; a diagonal média da impressão é de 0,250 mm. A dureza é a força dividida pela área da superfície da impressão, em kgf/mm², o que resulta em 0,1891·F/d² com F em newtons. Para aços, a resistência à tração é aproximadamente 3,3 × HV em MPa (uma regra prática, não um substituto do ensaio de tração).", de: "Beim HV10-Versuch wird eine Diamantpyramide mit 10 kgf eingedrückt; die mittlere Diagonale des Eindrucks beträgt 0,250 mm. Die Härte ist die Kraft bezogen auf die Oberfläche des Eindrucks in kgf/mm², was bei F in Newton 0,1891·F/d² ergibt. Bei Stählen beträgt die Zugfestigkeit etwa 3,3 × HV in MPa (eine Faustformel, kein Ersatz für einen Zugversuch).", fr: "Un essai HV10 enfonce une pyramide de diamant avec une force de 10 kgf ; la diagonale moyenne de l'empreinte est de 0,250 mm. La dureté est la force rapportée à la surface de l'empreinte, en kgf/mm², ce qui donne 0,1891·F/d² avec F en newtons. Pour les aciers, la résistance à la traction vaut environ 3,3 × HV en MPa (une règle empirique, qui ne remplace pas un essai de traction)." },
    localConstants: [
      // 試験力 HV10 は規格で決まる値（測定値ではない）。
      { symbol: "F", expression: "10kgf", exact: true },
      { symbol: "d", expression: "0.250mm" },
    ],
    steps: [
      { title: { en: "Vickers hardness HV", ja: "ビッカース硬さ HV", es: "Dureza Vickers HV", "pt-BR": "Dureza Vickers HV", de: "Vickershärte HV", fr: "Dureté Vickers HV" }, expression: "0.1891*F/d^2/(N/mm^2)", targetUnit: "", formulaLatex: "HV = 0.1891\\,\\dfrac{F}{d^2}" },
      { title: { en: "Estimated tensile strength (steel)", ja: "引張強さの目安（鋼）", es: "Resistencia a la tracción estimada (acero)", "pt-BR": "Resistência à tração estimada (aço)", de: "Abgeschätzte Zugfestigkeit (Stahl)", fr: "Résistance à la traction estimée (acier)" }, expression: "3.3*s1*MPa", targetUnit: "MPa", formulaLatex: "\\sigma_B \\approx 3.3\\,HV" },
    ],
  },
  {
    title: { en: "Charpy impact test: absorbed energy", ja: "シャルピー衝撃試験の吸収エネルギー", es: "Ensayo Charpy: energía absorbida", "pt-BR": "Ensaio Charpy: energia absorvida", de: "Kerbschlagbiegeversuch nach Charpy: Kerbschlagarbeit", fr: "Essai Charpy : énergie absorbée" },
    description: { en: "A pendulum hammer (27 kg, 0.8 m arm) is released from 140° and swings through after breaking an ASTM E23 V-notch specimen, rising only to 70°. The potential energy it lost went into breaking the specimen. Dividing by the 8 × 10 mm ligament under the notch gives the impact value per area that older standards quote.", ja: "質量27kg・腕の長さ0.8mの振り子ハンマーを140°から振り下ろし、ASTM E23 のVノッチ試験片を割ったあと70°までしか振り上がらなかった場合です。失った位置エネルギーが試験片を割るのに使われた吸収エネルギーです。ノッチ下の断面（8×10mm）で割ると、古い規格で使われる単位面積あたりの衝撃値になります。", es: "Un martillo pendular (27 kg, brazo de 0,8 m) se suelta desde 140° y, tras romper una probeta con entalla en V según ASTM E23, sigue su recorrido hasta solo 70°. La energía potencial que perdió se empleó en romper la probeta. Al dividirla entre el ligamento de 8 × 10 mm bajo la entalla se obtiene la resiliencia por área que citan las normas más antiguas.", "pt-BR": "Um martelo pendular (27 kg, braço de 0,8 m) é solto a partir de 140° e, depois de romper um corpo de prova com entalhe em V conforme a ASTM E23, sobe apenas até 70°. A energia potencial perdida foi usada para romper o corpo de prova. Dividindo pelo ligamento de 8 × 10 mm sob o entalhe, obtém-se o valor de impacto por área citado em normas mais antigas.", de: "Ein Pendelhammer (27 kg, Pendellänge 0,8 m) wird aus 140° losgelassen und schwingt nach dem Durchschlagen einer ASTM-E23-Probe mit V-Kerb nur noch bis 70° hoch. Die verlorene potenzielle Energie wurde zum Brechen der Probe verbraucht. Teilt man sie durch den Restquerschnitt von 8 × 10 mm unter der Kerbe, erhält man die flächenbezogene Kerbschlagzähigkeit, die ältere Normen angeben.", fr: "Un mouton-pendule (27 kg, bras de 0,8 m) est lâché de 140° et, après avoir rompu une éprouvette ASTM E23 à entaille en V, ne remonte que jusqu'à 70°. L'énergie potentielle perdue a servi à rompre l'éprouvette. En la divisant par le ligament de 8 × 10 mm sous l'entaille, on obtient la résilience par unité d'aire citée par les normes plus anciennes." },
    localConstants: [
      { symbol: "m", expression: "27.0kg" },
      { symbol: "R", expression: "0.800m" },
      { symbol: "g", expression: "9.80665m/s^2", exact: true },
      { symbol: "α", expression: "140deg" },
      { symbol: "β", expression: "70.0deg" },
      { symbol: "A", expression: "80.0mm^2" },
    ],
    steps: [
      { title: { en: "Absorbed energy E", ja: "吸収エネルギー E", es: "Energía absorbida E", "pt-BR": "Energia absorvida E", de: "Kerbschlagarbeit E", fr: "Énergie absorbée E" }, expression: "m*g*R*(cos(β)-cos(α))", targetUnit: "J", formulaLatex: "E = mgR(\\cos\\beta - \\cos\\alpha)" },
      { title: { en: "Impact value per area", ja: "衝撃値（単位面積あたり）", es: "Resiliencia (por unidad de área)", "pt-BR": "Valor de impacto (por unidade de área)", de: "Kerbschlagzähigkeit (flächenbezogen)", fr: "Résilience (par unité d'aire)" }, expression: "s1/A", targetUnit: "J/cm²", formulaLatex: "a_k = \\dfrac{E}{A}" },
    ],
  },
  {
    title: { en: "Compressive strength of a concrete cylinder (Ø100 × 200)", ja: "コンクリート円柱供試体（φ100×200）の圧縮強度", es: "Resistencia a compresión de una probeta cilíndrica de hormigón (Ø100 × 200)", "pt-BR": "Resistência à compressão de um corpo de prova cilíndrico de concreto (Ø100 × 200)", de: "Druckfestigkeit eines Betonzylinders (Ø100 × 200)", fr: "Résistance en compression d'une éprouvette cylindrique de béton (Ø100 × 200)" },
    description: { en: "A Ø100 × 200 mm concrete cylinder (ASTM C39 / JIS A 1108) fails at 314 kN. The compressive strength is the failure load over the circular cross-section; 40 MPa is a typical value for structural concrete at 28 days.", ja: "φ100×200mmのコンクリート円柱供試体（ASTM C39 / JIS A 1108）が314kNで破壊した場合です。圧縮強度は破壊荷重を円形断面で割った値で、40MPaは構造用コンクリートの材齢28日として標準的な値です。", es: "Una probeta cilíndrica de hormigón de Ø100 × 200 mm (ASTM C39 / JIS A 1108) rompe a 314 kN. La resistencia a compresión es la carga de rotura dividida entre la sección circular; 40 MPa es un valor típico del hormigón estructural a los 28 días.", "pt-BR": "Um corpo de prova cilíndrico de concreto de Ø100 × 200 mm (ASTM C39 / JIS A 1108) rompe a 314 kN. A resistência à compressão é a carga de ruptura dividida pela seção circular; 40 MPa é um valor típico para concreto estrutural aos 28 dias.", de: "Ein Betonzylinder mit Ø100 × 200 mm (ASTM C39 / JIS A 1108) versagt bei 314 kN. Die Druckfestigkeit ist die Bruchlast bezogen auf den Kreisquerschnitt; 40 MPa ist ein typischer Wert für Konstruktionsbeton nach 28 Tagen.", fr: "Une éprouvette cylindrique de béton de Ø100 × 200 mm (ASTM C39 / JIS A 1108) rompt à 314 kN. La résistance en compression est la charge de rupture divisée par la section circulaire ; 40 MPa est une valeur typique pour un béton de structure à 28 jours." },
    localConstants: [
      { symbol: "P", expression: "314kN" },
      { symbol: "d", expression: "100mm" },
    ],
    steps: [
      { title: { en: "Cross-sectional area A", ja: "断面積 A", es: "Área de la sección transversal A", "pt-BR": "Área da seção transversal A", de: "Querschnittsfläche A", fr: "Aire de la section A" }, expression: "π*d^2/4", targetUnit: "mm²", formulaLatex: "A = \\dfrac{\\pi d^2}{4}" },
      { title: { en: "Compressive strength f_c", ja: "圧縮強度 f_c", es: "Resistencia a compresión f_c", "pt-BR": "Resistência à compressão f_c", de: "Druckfestigkeit f_c", fr: "Résistance en compression f_c" }, expression: "P/s1", targetUnit: "MPa", formulaLatex: "f_c = \\dfrac{P}{A}" },
    ],
  },
];

/**
 * 疲労・破壊力学のカテゴリ。前半が疲労試験と疲労設計（応力の振幅・試験時間・疲労限度・グッドマン・S-N・
 * マイナー則）、後半が破壊力学（試験片ごとの応力拡大係数・J積分・有効性判定・臨界き裂長さ・パリス則）。
 * 試験片の式は ASTM E399 / E647 / E1820 の付属書の形のまま書いてある（係数を丸めないこと）。
 * K の単位 MPa√m はエンジンが次元の指数を0.5刻みまで扱えるようになって初めて書ける（2026-10）。
 */
export const ENG_FATIGUE_FRACTURE_SEEDS: NotebookSeed[] = [
  {
    title: { en: "Stress amplitude, mean stress & stress ratio", ja: "応力振幅・平均応力・応力比", es: "Amplitud de esfuerzo, esfuerzo medio y relación de esfuerzos", "pt-BR": "Amplitude de tensão, tensão média e razão de tensão", de: "Spannungsamplitude, Mittelspannung und Spannungsverhältnis", fr: "Amplitude de contrainte, contrainte moyenne et rapport de contraintes" },
    description: { en: "Every fatigue calculation starts by splitting a cyclic load into its amplitude and its mean. Here the stress swings between +300 MPa and −100 MPa. The stress ratio R = σ_min/σ_max labels the test condition: R = −1 is fully reversed, R = 0 is pulsating tension, R = 0.1 is the usual crack-growth test.", ja: "疲労の計算は、繰り返す応力を「振幅」と「平均」に分けるところから始まります。ここでは応力が +300MPa と −100MPa の間を往復します。応力比 R = σ_min/σ_max は試験条件の呼び名で、R = −1 が両振り、R = 0 が片振り（引張）、R = 0.1 がき裂進展試験でよく使う条件です。", es: "Todo cálculo de fatiga empieza dividiendo una carga cíclica en su amplitud y su valor medio. Aquí el esfuerzo oscila entre +300 MPa y −100 MPa. La relación de esfuerzos R = σ_min/σ_max identifica la condición de ensayo: R = −1 es alternado simétrico, R = 0 es tracción pulsante y R = 0,1 es el ensayo habitual de propagación de grietas.", "pt-BR": "Todo cálculo de fadiga começa separando um carregamento cíclico em sua amplitude e sua média. Aqui a tensão oscila entre +300 MPa e −100 MPa. A razão de tensão R = σ_min/σ_max identifica a condição de ensaio: R = −1 é alternada simétrica, R = 0 é tração pulsante e R = 0,1 é o ensaio usual de propagação de trincas.", de: "Jede Ermüdungsrechnung beginnt damit, eine zyklische Belastung in Amplitude und Mittelwert zu zerlegen. Hier schwankt die Spannung zwischen +300 MPa und −100 MPa. Das Spannungsverhältnis R = σ_min/σ_max kennzeichnet die Versuchsbedingung: R = −1 ist reine Wechselbeanspruchung, R = 0 ist Zugschwellbeanspruchung, R = 0,1 ist der übliche Versuch zur Rissausbreitung.", fr: "Tout calcul de fatigue commence par la décomposition d'une charge cyclique en amplitude et en valeur moyenne. Ici la contrainte oscille entre +300 MPa et −100 MPa. Le rapport de contraintes R = σ_min/σ_max désigne la condition d'essai : R = −1 correspond à l'alterné symétrique, R = 0 à la traction répétée et R = 0,1 à l'essai habituel de propagation de fissure." },
    localConstants: [
      { symbol: "σₘₐₓ", expression: "300MPa" },
      { symbol: "σₘᵢₙ", expression: "-100MPa" },
    ],
    steps: [
      { title: { en: "Stress amplitude σ_a", ja: "応力振幅 σ_a", es: "Amplitud de esfuerzo σ_a", "pt-BR": "Amplitude de tensão σ_a", de: "Spannungsamplitude σ_a", fr: "Amplitude de contrainte σ_a" }, expression: "(σₘₐₓ-σₘᵢₙ)/2", targetUnit: "MPa", formulaLatex: "\\sigma_a = \\dfrac{\\sigma_{max} - \\sigma_{min}}{2}" },
      { title: { en: "Mean stress σ_m", ja: "平均応力 σ_m", es: "Esfuerzo medio σ_m", "pt-BR": "Tensão média σ_m", de: "Mittelspannung σ_m", fr: "Contrainte moyenne σ_m" }, expression: "(σₘₐₓ+σₘᵢₙ)/2", targetUnit: "MPa", formulaLatex: "\\sigma_m = \\dfrac{\\sigma_{max} + \\sigma_{min}}{2}" },
      { title: { en: "Stress ratio R", ja: "応力比 R", es: "Relación de esfuerzos R", "pt-BR": "Razão de tensão R", de: "Spannungsverhältnis R", fr: "Rapport de contraintes R" }, expression: "σₘᵢₙ/σₘₐₓ", targetUnit: "", formulaLatex: "R = \\dfrac{\\sigma_{min}}{\\sigma_{max}}" },
    ],
  },
  {
    title: { en: "Fatigue test duration from cycles & frequency", ja: "疲労試験の所要時間（繰返し数と周波数）", es: "Duración de un ensayo de fatiga a partir de ciclos y frecuencia", "pt-BR": "Duração de um ensaio de fadiga a partir dos ciclos e da frequência", de: "Dauer eines Ermüdungsversuchs aus Lastspielzahl und Frequenz", fr: "Durée d'un essai de fatigue à partir du nombre de cycles et de la fréquence" },
    description: { en: "How long does a run-out test take? 10⁷ cycles is the usual limit for declaring a steel specimen run-out, and 100 Hz is typical for a resonant or servo-hydraulic machine. The time is simply cycles ÷ frequency: about 28 hours, a little over a day per specimen.", ja: "打ち切りまで回すと何時間かかるかの計算です。鋼の疲労試験は10⁷回で打ち切り（未破断）とするのが一般的で、共振型や油圧サーボ式の試験機なら100Hz前後で回します。時間は「回数÷周波数」で、1本あたり約28時間＝1日強です。", es: "¿Cuánto dura un ensayo hasta el límite de ciclos? 10⁷ ciclos es el límite habitual para dar por no roto (run-out) una probeta de acero, y 100 Hz es típico en una máquina resonante o servohidráulica. El tiempo es simplemente ciclos ÷ frecuencia: unas 28 horas, algo más de un día por probeta.", "pt-BR": "Quanto tempo leva um ensaio até o limite de ciclos? 10⁷ ciclos é o limite usual para considerar um corpo de prova de aço como sem ruptura (run-out), e 100 Hz é típico em uma máquina ressonante ou servo-hidráulica. O tempo é simplesmente ciclos ÷ frequência: cerca de 28 horas, pouco mais de um dia por corpo de prova.", de: "Wie lange dauert ein Versuch bis zum Grenzlastspiel? 10⁷ Lastspiele sind die übliche Grenze, ab der eine Stahlprobe als Durchläufer gilt, und 100 Hz sind für eine Resonanzprüfmaschine oder eine servohydraulische Maschine typisch. Die Zeit ist einfach Lastspielzahl ÷ Frequenz: etwa 28 Stunden, gut ein Tag pro Probe.", fr: "Combien de temps dure un essai poussé jusqu'à la limite de cycles ? 10⁷ cycles est la limite habituelle pour déclarer une éprouvette en acier non rompue (run-out), et 100 Hz est typique d'une machine à résonance ou servo-hydraulique. La durée vaut simplement cycles ÷ fréquence : environ 28 heures, un peu plus d'une journée par éprouvette." },
    localConstants: [
      // 繰返し数は数えた量（打ち切り回数の設定値）なので測定値ではない。
      { symbol: "N", expression: "1e7", exact: true },
      { symbol: "f", expression: "100Hz" },
    ],
    steps: [
      { title: { en: "Test duration t (hours)", ja: "所要時間 t（時間）", es: "Duración del ensayo t (horas)", "pt-BR": "Duração do ensaio t (horas)", de: "Versuchsdauer t (Stunden)", fr: "Durée de l'essai t (heures)" }, expression: "N/f", targetUnit: "h", formulaLatex: "t = \\dfrac{N}{f}" },
      { title: { en: "Test duration (days)", ja: "所要時間（日）", es: "Duración del ensayo (días)", "pt-BR": "Duração do ensaio (dias)", de: "Versuchsdauer (Tage)", fr: "Durée de l'essai (jours)" }, expression: "N/f", targetUnit: "d" },
    ],
  },
  {
    title: { en: "Estimating the endurance limit (surface & size factors)", ja: "疲労限度の推定（表面・寸法の補正）", es: "Estimación del límite de fatiga (factores de superficie y tamaño)", "pt-BR": "Estimativa do limite de fadiga (fatores de superfície e de tamanho)", de: "Abschätzung der Dauerfestigkeit (Oberflächen- und Größeneinflussfaktor)", fr: "Estimation de la limite d'endurance (facteurs de surface et de taille)" },
    description: { en: "Without test data, a steel's rotating-bending endurance limit is about half its tensile strength (up to 1400 MPa). A real part is weaker than the polished lab specimen: a machined surface and a Ø30 mm diameter each knock it down (Marin factors, as in Shigley). For S45C/1045 at 625 MPa this gives about 220 MPa.", ja: "試験データが無いとき、鋼の回転曲げ疲労限度は引張強さの約半分（1400MPaまで）が目安です。実際の部品は磨いた試験片より弱く、機械加工の表面と直径30mmという寸法がそれぞれ割り引きます（マリンの係数。シグリーの教科書の形）。S45C相当（625MPa）ではおよそ220MPaになります。", es: "Sin datos de ensayo, el límite de fatiga a flexión rotativa de un acero es aproximadamente la mitad de su resistencia a la tracción (hasta 1400 MPa). Una pieza real es más débil que la probeta pulida de laboratorio: una superficie mecanizada y un diámetro de Ø30 mm la reducen cada uno (factores de Marin, como en Shigley). Para S45C/1045 con 625 MPa resulta de unos 220 MPa.", "pt-BR": "Sem dados de ensaio, o limite de fadiga em flexão rotativa de um aço é cerca de metade de sua resistência à tração (até 1400 MPa). Uma peça real é mais fraca que o corpo de prova polido de laboratório: uma superfície usinada e um diâmetro de Ø30 mm reduzem cada um o valor (fatores de Marin, como em Shigley). Para S45C/1045 com 625 MPa, resulta em cerca de 220 MPa.", de: "Liegen keine Versuchsdaten vor, beträgt die Dauerfestigkeit eines Stahls bei Umlaufbiegung etwa die Hälfte seiner Zugfestigkeit (bis 1400 MPa). Ein reales Bauteil ist schwächer als die polierte Laborprobe: Eine spanend bearbeitete Oberfläche und ein Durchmesser von Ø30 mm mindern sie jeweils (Marin-Faktoren, wie bei Shigley). Für S45C/1045 mit 625 MPa ergeben sich etwa 220 MPa.", fr: "Sans données d'essai, la limite d'endurance en flexion rotative d'un acier vaut environ la moitié de sa résistance à la traction (jusqu'à 1400 MPa). Une pièce réelle est plus faible que l'éprouvette polie de laboratoire : une surface usinée et un diamètre de Ø30 mm la réduisent chacun (facteurs de Marin, comme chez Shigley). Pour le S45C/1045 à 625 MPa, on trouve environ 220 MPa." },
    localConstants: [
      { symbol: "σ_B", expression: "625MPa" },
      { symbol: "d", expression: "30.0mm" },
    ],
    steps: [
      { title: { en: "Specimen endurance limit σ_w0", ja: "試験片の疲労限度 σ_w0", es: "Límite de fatiga de la probeta σ_w0", "pt-BR": "Limite de fadiga do corpo de prova σ_w0", de: "Dauerfestigkeit der Probe σ_w0", fr: "Limite d'endurance de l'éprouvette σ_w0" }, expression: "σ_B/2", targetUnit: "MPa", resultSymbol: "σ_w0", formulaLatex: "\\sigma_{w0} \\approx 0.5\\,\\sigma_B" },
      { title: { en: "Surface factor k_a (machined)", ja: "表面係数 k_a（機械加工）", es: "Factor de superficie k_a (mecanizada)", "pt-BR": "Fator de superfície k_a (usinada)", de: "Oberflächenfaktor k_a (spanend bearbeitet)", fr: "Facteur de surface k_a (usinée)" }, expression: "4.51*(σ_B/MPa)^-0.265", targetUnit: "", resultSymbol: "k_a", formulaLatex: "k_a = 4.51\\,\\sigma_B^{-0.265}" },
      { title: { en: "Size factor k_b (rotating shaft)", ja: "寸法係数 k_b（回転軸）", es: "Factor de tamaño k_b (eje giratorio)", "pt-BR": "Fator de tamanho k_b (eixo rotativo)", de: "Größenfaktor k_b (umlaufende Welle)", fr: "Facteur de taille k_b (arbre tournant)" }, expression: "1.24*(d/mm)^-0.107", targetUnit: "", formulaLatex: "k_b = 1.24\\,d^{-0.107}" },
      { title: { en: "Endurance limit of the part σ_w", ja: "部品の疲労限度 σ_w", es: "Límite de fatiga de la pieza σ_w", "pt-BR": "Limite de fadiga da peça σ_w", de: "Dauerfestigkeit des Bauteils σ_w", fr: "Limite d'endurance de la pièce σ_w" }, expression: "k_a*k_b*σ_w0", targetUnit: "MPa", formulaLatex: "\\sigma_w = k_a k_b\\,\\sigma_{w0}" },
    ],
  },
  {
    title: { en: "Fatigue safety factor (modified Goodman)", ja: "疲労安全率（修正グッドマン線図）", es: "Factor de seguridad a fatiga (Goodman modificado)", "pt-BR": "Fator de segurança à fadiga (Goodman modificado)", de: "Sicherheitsfaktor gegen Ermüdung (modifizierte Goodman-Gerade)", fr: "Coefficient de sécurité en fatigue (droite de Goodman modifiée)" },
    description: { en: "A mean stress lowers how much amplitude a part can take. The modified Goodman line joins the endurance limit on the amplitude axis to the tensile strength on the mean-stress axis; the safety factor is how far the working point sits inside that line. With 150 MPa amplitude on 100 MPa mean, the 1045 shaft above comes out at about 1.2.", ja: "平均応力が加わると、耐えられる振幅は小さくなります。修正グッドマン線図は、振幅の軸の疲労限度と平均応力の軸の引張強さを結んだ直線で、安全率は使用点がその線の内側にどれだけ余裕があるかです。平均100MPaに振幅150MPaが重なると、上のS45C軸ではおよそ1.2になります。", es: "Un esfuerzo medio reduce la amplitud que puede soportar una pieza. La recta de Goodman modificada une el límite de fatiga en el eje de amplitud con la resistencia a la tracción en el eje de esfuerzo medio; el factor de seguridad indica cuánto queda el punto de trabajo dentro de esa recta. Con 150 MPa de amplitud sobre 100 MPa de esfuerzo medio, el eje de 1045 anterior sale con aproximadamente 1,2.", "pt-BR": "Uma tensão média reduz a amplitude que uma peça suporta. A reta de Goodman modificada liga o limite de fadiga no eixo da amplitude à resistência à tração no eixo da tensão média; o fator de segurança indica o quanto o ponto de trabalho está dentro dessa reta. Com 150 MPa de amplitude sobre 100 MPa de tensão média, o eixo de 1045 acima resulta em cerca de 1,2.", de: "Eine Mittelspannung verringert die Amplitude, die ein Bauteil ertragen kann. Die modifizierte Goodman-Gerade verbindet die Dauerfestigkeit auf der Amplitudenachse mit der Zugfestigkeit auf der Mittelspannungsachse; der Sicherheitsfaktor gibt an, wie weit der Arbeitspunkt innerhalb dieser Geraden liegt. Bei 150 MPa Amplitude auf 100 MPa Mittelspannung ergibt sich für die obige 1045-Welle etwa 1,2.", fr: "Une contrainte moyenne réduit l'amplitude que peut supporter une pièce. La droite de Goodman modifiée relie la limite d'endurance sur l'axe des amplitudes à la résistance à la traction sur l'axe des contraintes moyennes ; le coefficient de sécurité indique de combien le point de fonctionnement se trouve à l'intérieur de cette droite. Avec 150 MPa d'amplitude sur 100 MPa de contrainte moyenne, l'arbre en 1045 ci-dessus donne environ 1,2." },
    localConstants: [
      { symbol: "σ_a", expression: "150MPa" },
      { symbol: "σ_m", expression: "100MPa" },
      { symbol: "σ_w", expression: "220MPa" },
      { symbol: "σ_B", expression: "625MPa" },
    ],
    steps: [
      { title: { en: "Fatigue safety factor n", ja: "疲労安全率 n", es: "Factor de seguridad a fatiga n", "pt-BR": "Fator de segurança à fadiga n", de: "Sicherheitsfaktor gegen Ermüdung n", fr: "Coefficient de sécurité en fatigue n" }, expression: "1/(σ_a/σ_w + σ_m/σ_B)", targetUnit: "", formulaLatex: "\\dfrac{1}{n} = \\dfrac{\\sigma_a}{\\sigma_w} + \\dfrac{\\sigma_m}{\\sigma_B}" },
    ],
  },
  {
    title: { en: "Fatigue life from the S–N curve (Basquin)", ja: "S-N曲線から疲労寿命（バスキン則）", es: "Vida a fatiga a partir de la curva S–N (ley de Basquin)", "pt-BR": "Vida em fadiga a partir da curva S–N (lei de Basquin)", de: "Lebensdauer aus der Wöhlerlinie (Basquin-Gleichung)", fr: "Durée de vie en fatigue à partir de la courbe S–N (loi de Basquin)" },
    description: { en: "Above the endurance limit, the S–N curve is a straight line on log–log axes: σ_a = σ_f′(2N)^b. Turned around, it gives the number of cycles to failure for a given amplitude. With typical values for normalized 1045 steel (σ_f′ = 930 MPa, b = −0.085), 300 MPa amplitude lasts about 3 × 10⁵ cycles.", ja: "疲労限度より上では、S-N曲線は両対数で直線になります：σ_a = σ_f′(2N)^b。これを逆に解くと、ある振幅で何回もつかが出ます。焼ならしたS45C相当の代表値（σ_f′ = 930MPa、b = −0.085）では、振幅300MPaでおよそ3×10⁵回です。", es: "Por encima del límite de fatiga, la curva S–N es una recta en ejes logarítmicos: σ_a = σ_f′(2N)^b. Despejando N, da el número de ciclos hasta la rotura para una amplitud dada. Con valores típicos de un acero 1045 normalizado (σ_f′ = 930 MPa, b = −0,085), una amplitud de 300 MPa dura unos 3 × 10⁵ ciclos.", "pt-BR": "Acima do limite de fadiga, a curva S–N é uma reta em eixos log–log: σ_a = σ_f′(2N)^b. Resolvida ao contrário, dá o número de ciclos até a falha para uma dada amplitude. Com valores típicos de um aço 1045 normalizado (σ_f′ = 930 MPa, b = −0,085), uma amplitude de 300 MPa dura cerca de 3 × 10⁵ ciclos.", de: "Oberhalb der Dauerfestigkeit ist die Wöhlerlinie (S–N-Kurve) in doppelt-logarithmischer Darstellung eine Gerade: σ_a = σ_f′(2N)^b. Nach N aufgelöst ergibt sich die Lastspielzahl bis zum Bruch für eine gegebene Amplitude. Mit typischen Werten für normalgeglühten Stahl 1045 (σ_f′ = 930 MPa, b = −0,085) hält eine Amplitude von 300 MPa etwa 3 × 10⁵ Lastspiele.", fr: "Au-dessus de la limite d'endurance, la courbe S–N est une droite en axes log–log : σ_a = σ_f′(2N)^b. Inversée, elle donne le nombre de cycles à la rupture pour une amplitude donnée. Avec des valeurs typiques d'un acier 1045 normalisé (σ_f′ = 930 MPa, b = −0,085), une amplitude de 300 MPa tient environ 3 × 10⁵ cycles." },
    localConstants: [
      { symbol: "σ_a", expression: "300MPa" },
      { symbol: "σ_f", expression: "930MPa" },
      { symbol: "b", expression: "-0.085" },
    ],
    steps: [
      { title: { en: "Cycles to failure N", ja: "破断までの繰返し数 N", es: "Ciclos hasta la rotura N", "pt-BR": "Ciclos até a ruptura N", de: "Lastspielzahl bis zum Bruch N", fr: "Nombre de cycles à la rupture N" }, expression: "(σ_a/σ_f)^(1/b)/2", targetUnit: "", formulaLatex: "N = \\dfrac{1}{2}\\left(\\dfrac{\\sigma_a}{\\sigma_f'}\\right)^{1/b}" },
    ],
  },
  {
    title: { en: "Cumulative damage (Miner's rule)", ja: "累積損傷（マイナー則）", es: "Daño acumulado (regla de Miner)", "pt-BR": "Dano acumulado (regra de Miner)", de: "Schadensakkumulation (Miner-Regel)", fr: "Cumul de dommage (règle de Miner)" },
    description: { en: "A part rarely sees one stress level. Miner's rule adds up, for each level, the cycles applied divided by the cycles that level would take to failure. Failure is expected when the sum D reaches 1, so 1/D says how many times the whole load history could be repeated.", ja: "部品が1つの応力レベルだけを受けることはまれです。マイナー則は、レベルごとに「加えた回数÷そのレベルでの寿命」を足し合わせ、その和 D が1に達したら破壊すると考えます。1/D は、同じ荷重履歴をあと何回繰り返せるかを表します。", es: "Una pieza rara vez soporta un solo nivel de esfuerzo. La regla de Miner suma, para cada nivel, los ciclos aplicados divididos entre los ciclos que ese nivel tardaría en producir la rotura. Se espera la rotura cuando la suma D alcanza 1, de modo que 1/D indica cuántas veces podría repetirse todo el historial de carga.", "pt-BR": "Uma peça raramente é submetida a um único nível de tensão. A regra de Miner soma, para cada nível, os ciclos aplicados divididos pelos ciclos que esse nível levaria até a ruptura. Espera-se a falha quando a soma D chega a 1, de modo que 1/D indica quantas vezes todo o histórico de carga poderia ser repetido.", de: "Ein Bauteil erfährt selten nur eine Spannungsstufe. Die Miner-Regel (lineare Schadensakkumulation) addiert für jede Stufe die aufgebrachten Lastspiele geteilt durch die Lastspiele, die diese Stufe bis zum Bruch ertragen würde. Versagen wird erwartet, wenn die Summe D den Wert 1 erreicht; 1/D gibt an, wie oft sich das gesamte Lastkollektiv wiederholen ließe.", fr: "Une pièce subit rarement un seul niveau de contrainte. La règle de Miner additionne, pour chaque niveau, les cycles appliqués divisés par les cycles que ce niveau mettrait à provoquer la rupture. La rupture est attendue lorsque la somme D atteint 1 ; 1/D indique donc combien de fois l'ensemble de l'historique de chargement pourrait être répété." },
    localConstants: [
      { symbol: "n₁", expression: "2.0e4", exact: true },
      { symbol: "N₁", expression: "1.0e5" },
      { symbol: "n₂", expression: "1.0e5", exact: true },
      { symbol: "N₂", expression: "1.0e6" },
      { symbol: "n₃", expression: "5.0e5", exact: true },
      { symbol: "N₃", expression: "1.0e7" },
    ],
    steps: [
      { title: { en: "Damage sum D", ja: "損傷和 D", es: "Suma de daño D", "pt-BR": "Soma de dano D", de: "Schädigungssumme D", fr: "Somme des dommages D" }, expression: "n₁/N₁ + n₂/N₂ + n₃/N₃", targetUnit: "", formulaLatex: "D = \\sum \\dfrac{n_i}{N_i}" },
      { title: { en: "Repeats of the load history until failure", ja: "破壊までに荷重履歴を繰り返せる回数", es: "Repeticiones del historial de carga hasta la rotura", "pt-BR": "Repetições do histórico de carga até a ruptura", de: "Wiederholungen des Lastkollektivs bis zum Bruch", fr: "Répétitions de l'historique de chargement jusqu'à la rupture" }, expression: "1/s1", targetUnit: "", formulaLatex: "\\dfrac{1}{D}" },
    ],
  },
  {
    title: { en: "Fatigue notch factor from K_t", ja: "応力集中係数から切欠き係数", es: "Factor de entalla a la fatiga a partir de K_t", "pt-BR": "Fator de entalhe à fadiga a partir de K_t", de: "Kerbwirkungszahl aus K_t", fr: "Facteur effectif de concentration de contrainte en fatigue à partir de K_t" },
    description: { en: "A notch does not hurt fatigue strength by the full elastic stress concentration K_t; how much it does depends on the material's notch sensitivity q (0 = insensitive, 1 = fully sensitive). The fatigue notch factor K_f then divides the endurance limit. With the hole from the stress-concentration notebook (K_t = 2.4) and q = 0.85, the 220 MPa limit drops to about 100 MPa.", ja: "切欠きは、弾性の応力集中係数 K_t の分だけそのまま疲労強度を下げるわけではありません。どれだけ効くかは材料の切欠き感度 q（0＝鈍感、1＝敏感）で決まり、切欠き係数 K_f で疲労限度を割ります。応力集中のノートの穴（K_t = 2.4）と q = 0.85 では、220MPaの疲労限度がおよそ100MPaまで下がります。", es: "Una entalla no reduce la resistencia a la fatiga en todo el factor elástico de concentración de esfuerzos K_t; cuánto lo hace depende de la sensibilidad a la entalla q del material (0 = insensible, 1 = totalmente sensible). El factor de entalla a la fatiga K_f divide entonces el límite de fatiga. Con el agujero del ejemplo de concentración de esfuerzos (K_t = 2,4) y q = 0,85, el límite de 220 MPa baja a unos 100 MPa.", "pt-BR": "Um entalhe não reduz a resistência à fadiga em todo o fator elástico de concentração de tensões K_t; quanto reduz depende da sensibilidade ao entalhe q do material (0 = insensível, 1 = totalmente sensível). O fator de entalhe à fadiga K_f divide então o limite de fadiga. Com o furo do exemplo de concentração de tensões (K_t = 2,4) e q = 0,85, o limite de 220 MPa cai para cerca de 100 MPa.", de: "Eine Kerbe mindert die Dauerfestigkeit nicht um die volle elastische Formzahl K_t; wie stark, hängt von der Kerbempfindlichkeit q des Werkstoffs ab (0 = unempfindlich, 1 = voll empfindlich). Die Kerbwirkungszahl K_f teilt dann die Dauerfestigkeit. Mit dem Loch aus dem Beispiel zur Spannungskonzentration (K_t = 2,4) und q = 0,85 sinkt die Dauerfestigkeit von 220 MPa auf etwa 100 MPa.", fr: "Une entaille ne réduit pas la tenue en fatigue de tout le coefficient élastique de concentration de contrainte K_t ; l'effet dépend de la sensibilité à l'entaille q du matériau (0 = insensible, 1 = totalement sensible). Le facteur effectif de concentration de contrainte en fatigue K_f divise alors la limite d'endurance. Avec le trou de l'exemple de concentration de contraintes (K_t = 2,4) et q = 0,85, la limite de 220 MPa tombe à environ 100 MPa." },
    localConstants: [
      { symbol: "Kₜ", expression: "2.4" },
      { symbol: "q", expression: "0.85" },
      { symbol: "σ_w", expression: "220MPa" },
    ],
    steps: [
      { title: { en: "Fatigue notch factor K_f", ja: "切欠き係数 K_f", es: "Factor de entalla a la fatiga K_f", "pt-BR": "Fator de entalhe à fadiga K_f", de: "Kerbwirkungszahl K_f", fr: "Facteur effectif de concentration de contrainte K_f" }, expression: "1+q*(Kₜ-1)", targetUnit: "", formulaLatex: "K_f = 1 + q(K_t - 1)" },
      { title: { en: "Endurance limit at the notch", ja: "切欠き部の疲労限度", es: "Límite de fatiga en la entalla", "pt-BR": "Limite de fadiga no entalhe", de: "Dauerfestigkeit an der Kerbe", fr: "Limite d'endurance à l'entaille" }, expression: "σ_w/s1", targetUnit: "MPa", formulaLatex: "\\sigma_{wk} = \\dfrac{\\sigma_w}{K_f}" },
    ],
  },
  {
    title: { en: "Stress intensity of a compact tension C(T) specimen (ASTM E399 / E647)", ja: "CT試験片の応力拡大係数（ASTM E399 / E647）", es: "Factor de intensidad de esfuerzos de una probeta compacta de tracción C(T) (ASTM E399 / E647)", "pt-BR": "Fator de intensidade de tensão de um corpo de prova compacto de tração C(T) (ASTM E399 / E647)", de: "Spannungsintensitätsfaktor einer Kompaktzugprobe C(T) (ASTM E399 / E647)", fr: "Facteur d'intensité de contrainte d'une éprouvette compacte de traction C(T) (ASTM E399 / E647)" },
    description: { en: "The compact tension specimen is the workhorse of fracture-toughness and crack-growth testing. Its K is the load over B√W times a geometry function of a/W, given in ASTM E399 and E647 (valid for 0.2 ≤ a/W ≤ 1). For a 1T specimen (W = 50 mm, B = 25 mm) with a/W = 0.5 at 10 kN, K is about 17 MPa√m.", ja: "CT試験片は破壊靭性試験・き裂進展試験で最もよく使う試験片です。K は「荷重÷(B√W)」に a/W の形状関数を掛けたもので、式は ASTM E399・E647 にあります（0.2 ≤ a/W ≤ 1 で有効）。1T試験片（W = 50mm、B = 25mm）で a/W = 0.5、荷重10kNなら K はおよそ17MPa√mです。", es: "La probeta compacta de tracción es el caballo de batalla de los ensayos de tenacidad a la fractura y de propagación de grietas. Su K es la carga dividida entre B√W por una función geométrica de a/W, dada en ASTM E399 y E647 (válida para 0,2 ≤ a/W ≤ 1). Para una probeta 1T (W = 50 mm, B = 25 mm) con a/W = 0,5 y 10 kN, K es de unos 17 MPa√m.", "pt-BR": "O corpo de prova compacto de tração é o principal tipo usado em ensaios de tenacidade à fratura e de propagação de trincas. Seu K é a carga dividida por B√W vezes uma função geométrica de a/W, dada nas normas ASTM E399 e E647 (válida para 0,2 ≤ a/W ≤ 1). Para um corpo de prova 1T (W = 50 mm, B = 25 mm) com a/W = 0,5 e 10 kN, K é de cerca de 17 MPa√m.", de: "Die Kompaktzugprobe ist das Arbeitspferd der Bruchzähigkeits- und Rissausbreitungsversuche. Ihr K ergibt sich aus der Last geteilt durch B√W, multipliziert mit einer Geometriefunktion von a/W, die in ASTM E399 und E647 angegeben ist (gültig für 0,2 ≤ a/W ≤ 1). Bei einer 1T-Probe (W = 50 mm, B = 25 mm) mit a/W = 0,5 und 10 kN beträgt K etwa 17 MPa√m.", fr: "L'éprouvette compacte de traction est l'éprouvette de référence des essais de ténacité et de propagation de fissure. Son K est la charge divisée par B√W, multipliée par une fonction géométrique de a/W donnée dans ASTM E399 et E647 (valable pour 0,2 ≤ a/W ≤ 1). Pour une éprouvette 1T (W = 50 mm, B = 25 mm) avec a/W = 0,5 sous 10 kN, K vaut environ 17 MPa√m." },
    localConstants: [
      { symbol: "P", expression: "10.0kN" },
      { symbol: "B", expression: "25.0mm" },
      { symbol: "W", expression: "50.0mm" },
      { symbol: "a", expression: "25.0mm" },
    ],
    steps: [
      { title: { en: "Relative crack length α = a/W", ja: "き裂長さ比 α = a/W", es: "Longitud relativa de la grieta α = a/W", "pt-BR": "Comprimento relativo da trinca α = a/W", de: "Relative Risslänge α = a/W", fr: "Longueur relative de fissure α = a/W" }, expression: "a/W", targetUnit: "", formulaLatex: "\\alpha = \\dfrac{a}{W}" },
      { title: { en: "Geometry function f(α)", ja: "形状関数 f(α)", es: "Función geométrica f(α)", "pt-BR": "Função geométrica f(α)", de: "Geometriefunktion f(α)", fr: "Fonction géométrique f(α)" }, expression: "(2+s1)/(1-s1)^1.5*(0.886+4.64*s1-13.32*s1^2+14.72*s1^3-5.6*s1^4)", targetUnit: "", formulaLatex: "\\begin{aligned} f &= \\dfrac{2+\\alpha}{(1-\\alpha)^{3/2}}\\bigl(0.886 + 4.64\\alpha - 13.32\\alpha^2 \\\\ &\\qquad + 14.72\\alpha^3 - 5.6\\alpha^4\\bigr) \\end{aligned}" },
      { title: { en: "Stress intensity factor K", ja: "応力拡大係数 K", es: "Factor de intensidad de esfuerzos K", "pt-BR": "Fator de intensidade de tensão K", de: "Spannungsintensitätsfaktor K", fr: "Facteur d'intensité de contrainte K" }, expression: "P/(B*√W)*s2", targetUnit: "MPa√m", formulaLatex: "K = \\dfrac{P}{B\\sqrt{W}}\\,f(\\alpha)" },
    ],
  },
  {
    title: { en: "Stress intensity of a three-point bend SE(B) specimen (ASTM E1820 / E399)", ja: "三点曲げSE(B)試験片の応力拡大係数（ASTM E1820 / E399）", es: "Factor de intensidad de esfuerzos de una probeta de flexión en tres puntos SE(B) (ASTM E1820 / E399)", "pt-BR": "Fator de intensidade de tensão de um corpo de prova de flexão em três pontos SE(B) (ASTM E1820 / E399)", de: "Spannungsintensitätsfaktor einer Dreipunkt-Biegeprobe SE(B) (ASTM E1820 / E399)", fr: "Facteur d'intensité de contrainte d'une éprouvette de flexion trois points SE(B) (ASTM E1820 / E399)" },
    description: { en: "The single-edge bend specimen is loaded in three-point bending over a span S = 4W. ASTM E1820 and E399 give K as P·S/(B·W^1.5) times a geometry function of a/W. For W = 20 mm, B = 10 mm, a/W = 0.5 and 5 kN, K is about 38 MPa√m. With side grooves, E1820 replaces B by √(B·B_N).", ja: "SE(B)試験片は、スパン S = 4W の三点曲げで荷重をかける試験片です。ASTM E1820・E399 では K を「P·S/(B·W^1.5)」に a/W の形状関数を掛けて求めます。W = 20mm、B = 10mm、a/W = 0.5、荷重5kNなら K はおよそ38MPa√mです。サイドグルーブ付きでは E1820 は B を √(B·B_N) に置き換えます。", es: "La probeta de flexión con una sola entalla en el borde se carga en flexión en tres puntos con una luz S = 4W. ASTM E1820 y E399 dan K como P·S/(B·W^1.5) por una función geométrica de a/W. Para W = 20 mm, B = 10 mm, a/W = 0,5 y 5 kN, K es de unos 38 MPa√m. Con ranuras laterales, E1820 sustituye B por √(B·B_N).", "pt-BR": "O corpo de prova de flexão com entalhe único na borda é carregado em flexão em três pontos com vão S = 4W. As normas ASTM E1820 e E399 dão K como P·S/(B·W^1.5) vezes uma função geométrica de a/W. Para W = 20 mm, B = 10 mm, a/W = 0,5 e 5 kN, K é de cerca de 38 MPa√m. Com entalhes laterais, a E1820 substitui B por √(B·B_N).", de: "Die Biegeprobe mit einseitigem Kerb wird in Dreipunktbiegung mit der Stützweite S = 4W belastet. ASTM E1820 und E399 geben K als P·S/(B·W^1.5) mal einer Geometriefunktion von a/W an. Für W = 20 mm, B = 10 mm, a/W = 0,5 und 5 kN beträgt K etwa 38 MPa√m. Bei Seitenkerben ersetzt E1820 B durch √(B·B_N).", fr: "L'éprouvette de flexion à entaille unique sur un bord est sollicitée en flexion trois points avec une portée S = 4W. ASTM E1820 et E399 donnent K sous la forme P·S/(B·W^1.5) multiplié par une fonction géométrique de a/W. Pour W = 20 mm, B = 10 mm, a/W = 0,5 et 5 kN, K vaut environ 38 MPa√m. Avec des rainures latérales, E1820 remplace B par √(B·B_N)." },
    localConstants: [
      { symbol: "P", expression: "5.00kN" },
      { symbol: "B", expression: "10.0mm" },
      { symbol: "W", expression: "20.0mm" },
      { symbol: "S", expression: "80.0mm" },
      { symbol: "a", expression: "10.0mm" },
    ],
    steps: [
      { title: { en: "Relative crack length α = a/W", ja: "き裂長さ比 α = a/W", es: "Longitud relativa de la grieta α = a/W", "pt-BR": "Comprimento relativo da trinca α = a/W", de: "Relative Risslänge α = a/W", fr: "Longueur relative de fissure α = a/W" }, expression: "a/W", targetUnit: "", formulaLatex: "\\alpha = \\dfrac{a}{W}" },
      { title: { en: "Geometry function f(α)", ja: "形状関数 f(α)", es: "Función geométrica f(α)", "pt-BR": "Função geométrica f(α)", de: "Geometriefunktion f(α)", fr: "Fonction géométrique f(α)" }, expression: "3*√s1*(1.99-s1*(1-s1)*(2.15-3.93*s1+2.7*s1^2))/(2*(1+2*s1)*(1-s1)^1.5)", targetUnit: "", formulaLatex: "\\begin{aligned} f &= \\dfrac{3\\sqrt{\\alpha}}{2(1+2\\alpha)(1-\\alpha)^{3/2}} \\\\ &\\quad \\times \\bigl[1.99 - \\alpha(1-\\alpha) \\\\ &\\qquad \\times (2.15 - 3.93\\alpha + 2.7\\alpha^2)\\bigr] \\end{aligned}" },
      { title: { en: "Stress intensity factor K", ja: "応力拡大係数 K", es: "Factor de intensidad de esfuerzos K", "pt-BR": "Fator de intensidade de tensão K", de: "Spannungsintensitätsfaktor K", fr: "Facteur d'intensité de contrainte K" }, expression: "P*S/(B*W^1.5)*s2", targetUnit: "MPa√m", formulaLatex: "K = \\dfrac{PS}{BW^{3/2}}\\,f(\\alpha)" },
    ],
  },
  {
    title: { en: "ΔK of a middle-crack tension M(T) specimen (ASTM E647)", ja: "中央き裂M(T)試験片のΔK（ASTM E647）", es: "ΔK de una probeta de tracción con grieta central M(T) (ASTM E647)", "pt-BR": "ΔK de um corpo de prova de tração com trinca central M(T) (ASTM E647)", de: "ΔK einer Zugprobe mit Mittenriss M(T) (ASTM E647)", fr: "ΔK d'une éprouvette de traction à fissure centrale M(T) (ASTM E647)" },
    description: { en: "The middle-crack tension panel is the thin-sheet specimen of ASTM E647, used for aluminium alloys and aircraft skins. W is the full width and 2a the total crack length. A load range of 20 kN on a 100 mm × 6 mm panel with a 20 mm crack gives ΔK of about 6 MPa√m — near the start of a typical da/dN curve.", ja: "M(T)試験片は ASTM E647 の薄板用の試験片で、アルミ合金や航空機の外板に使います。W は全幅、2a はき裂の全長です。幅100mm・厚さ6mmの板に長さ20mmのき裂があり、荷重範囲が20kNなら ΔK はおよそ6MPa√m で、典型的な da/dN 曲線の出だし付近です。", es: "El panel de tracción con grieta central es la probeta de chapa delgada de ASTM E647, usada para aleaciones de aluminio y revestimientos de aeronaves. W es el ancho total y 2a la longitud total de la grieta. Un intervalo de carga de 20 kN en un panel de 100 mm × 6 mm con una grieta de 20 mm da un ΔK de unos 6 MPa√m, cerca del comienzo de una curva da/dN típica.", "pt-BR": "O painel de tração com trinca central é o corpo de prova de chapa fina da ASTM E647, usado para ligas de alumínio e revestimentos de aeronaves. W é a largura total e 2a o comprimento total da trinca. Uma faixa de carga de 20 kN em um painel de 100 mm × 6 mm com uma trinca de 20 mm dá um ΔK de cerca de 6 MPa√m, perto do início de uma curva da/dN típica.", de: "Die Zugprobe mit Mittenriss ist die Blechprobe nach ASTM E647 und wird für Aluminiumlegierungen und Flugzeugbeplankungen verwendet. W ist die Gesamtbreite und 2a die gesamte Risslänge. Eine Lastschwingbreite von 20 kN an einer Platte von 100 mm × 6 mm mit einem 20 mm langen Riss ergibt ein ΔK von etwa 6 MPa√m – nahe dem Beginn einer typischen da/dN-Kurve.", fr: "L'éprouvette de traction à fissure centrale est l'éprouvette de tôle mince de l'ASTM E647, utilisée pour les alliages d'aluminium et les revêtements d'aéronefs. W est la largeur totale et 2a la longueur totale de la fissure. Une étendue de charge de 20 kN sur un panneau de 100 mm × 6 mm avec une fissure de 20 mm donne un ΔK d'environ 6 MPa√m, près du début d'une courbe da/dN typique." },
    localConstants: [
      { symbol: "ΔP", expression: "20.0kN" },
      { symbol: "B", expression: "6.00mm" },
      { symbol: "W", expression: "100mm" },
      { symbol: "a", expression: "10.0mm" },
    ],
    steps: [
      { title: { en: "Relative crack length α = 2a/W", ja: "き裂長さ比 α = 2a/W", es: "Longitud relativa de la grieta α = 2a/W", "pt-BR": "Comprimento relativo da trinca α = 2a/W", de: "Relative Risslänge α = 2a/W", fr: "Longueur relative de fissure α = 2a/W" }, expression: "2*a/W", targetUnit: "", formulaLatex: "\\alpha = \\dfrac{2a}{W}" },
      { title: { en: "Stress intensity range ΔK", ja: "応力拡大係数範囲 ΔK", es: "Intervalo del factor de intensidad de esfuerzos ΔK", "pt-BR": "Faixa do fator de intensidade de tensão ΔK", de: "Schwingbreite des Spannungsintensitätsfaktors ΔK", fr: "Étendue du facteur d'intensité de contrainte ΔK" }, expression: "ΔP/B*√(π*s1/(2*W)/cos(π*s1/2))", targetUnit: "MPa√m", formulaLatex: "\\Delta K = \\dfrac{\\Delta P}{B}\\sqrt{\\dfrac{\\pi\\alpha}{2W}\\sec\\dfrac{\\pi\\alpha}{2}}" },
    ],
  },
  {
    title: { en: "Fatigue crack growth rate (Paris law, ASTM E647)", ja: "疲労き裂進展速度（パリス則・ASTM E647）", es: "Velocidad de propagación de grietas por fatiga (ley de Paris, ASTM E647)", "pt-BR": "Taxa de propagação de trincas por fadiga (lei de Paris, ASTM E647)", de: "Ermüdungsrissausbreitung: Rissfortschrittsrate (Paris-Gesetz, ASTM E647)", fr: "Vitesse de propagation des fissures de fatigue (loi de Paris, ASTM E647)" },
    description: { en: "In the middle of the da/dN curve, crack growth per cycle follows a power law of ΔK. Barsom's values for ferrite–pearlite steels are C = 6.9 × 10⁻¹² m/cycle and n = 3.0 with ΔK in MPa√m. At ΔK = 20 MPa√m the crack grows about 0.055 µm per cycle, so 1 mm of growth takes some 18,000 cycles (at constant ΔK).", ja: "da/dN 曲線の中間域では、1サイクルあたりのき裂進展量が ΔK のべき乗に従います。フェライト・パーライト鋼のバーソムの値は C = 6.9×10⁻¹² m/cycle、n = 3.0（ΔK は MPa√m）です。ΔK = 20MPa√m では1サイクルに約0.055µm進むので、1mm進むのにおよそ1.8万サイクルかかります（ΔK一定とした場合）。", es: "En la zona media de la curva da/dN, el crecimiento de la grieta por ciclo sigue una ley de potencias de ΔK. Los valores de Barsom para aceros ferrítico-perlíticos son C = 6,9 × 10⁻¹² m/ciclo y n = 3,0 con ΔK en MPa√m. Con ΔK = 20 MPa√m la grieta avanza unos 0,055 µm por ciclo, de modo que avanzar 1 mm lleva unos 18 000 ciclos (con ΔK constante).", "pt-BR": "Na região intermediária da curva da/dN, o crescimento da trinca por ciclo segue uma lei de potência de ΔK. Os valores de Barsom para aços ferríticos-perlíticos são C = 6,9 × 10⁻¹² m/ciclo e n = 3,0 com ΔK em MPa√m. Com ΔK = 20 MPa√m a trinca cresce cerca de 0,055 µm por ciclo, então crescer 1 mm leva cerca de 18.000 ciclos (com ΔK constante).", de: "Im mittleren Bereich der da/dN-Kurve folgt das Risswachstum pro Lastspiel einem Potenzgesetz in ΔK. Die Werte von Barsom für ferritisch-perlitische Stähle sind C = 6,9 × 10⁻¹² m/Lastspiel und n = 3,0 mit ΔK in MPa√m. Bei ΔK = 20 MPa√m wächst der Riss etwa 0,055 µm pro Lastspiel, sodass 1 mm Rissfortschritt rund 18.000 Lastspiele dauert (bei konstantem ΔK).", fr: "Dans la partie médiane de la courbe da/dN, la croissance de la fissure par cycle suit une loi de puissance de ΔK. Les valeurs de Barsom pour les aciers ferrito-perlitiques sont C = 6,9 × 10⁻¹² m/cycle et n = 3,0 avec ΔK en MPa√m. À ΔK = 20 MPa√m, la fissure avance d'environ 0,055 µm par cycle ; 1 mm de propagation demande donc quelque 18 000 cycles (à ΔK constant)." },
    localConstants: [
      { symbol: "C", expression: "6.9e-12m" },
      { symbol: "n", expression: "3.0" },
      { symbol: "ΔK", expression: "20.0MPa√m" },
      { symbol: "Δa", expression: "1.00mm" },
    ],
    steps: [
      { title: { en: "Crack growth per cycle da/dN", ja: "1サイクルあたりの進展量 da/dN", es: "Avance de la grieta por ciclo da/dN", "pt-BR": "Avanço da trinca por ciclo da/dN", de: "Rissfortschritt pro Lastspiel da/dN", fr: "Avance de la fissure par cycle da/dN" }, expression: "C*(ΔK/(MPa√m))^n", targetUnit: "µm", formulaLatex: "\\dfrac{da}{dN} = C\\,(\\Delta K)^n" },
      { title: { en: "Cycles to grow Δa (constant ΔK)", ja: "Δa 進むまでのサイクル数（ΔK一定）", es: "Ciclos para avanzar Δa (ΔK constante)", "pt-BR": "Ciclos para avançar Δa (ΔK constante)", de: "Lastspiele für den Rissfortschritt Δa (ΔK konstant)", fr: "Cycles pour avancer de Δa (ΔK constant)" }, expression: "Δa/s1", targetUnit: "", formulaLatex: "N = \\dfrac{\\Delta a}{da/dN}" },
    ],
  },
  {
    title: { en: "Fracture toughness from the J-integral (ASTM E1820)", ja: "J積分から破壊靭性 K_J（ASTM E1820）", es: "Tenacidad a la fractura a partir de la integral J (ASTM E1820)", "pt-BR": "Tenacidade à fratura a partir da integral J (ASTM E1820)", de: "Bruchzähigkeit aus dem J-Integral (ASTM E1820)", fr: "Ténacité à partir de l'intégrale J (ASTM E1820)" },
    description: { en: "Tough steels yield too much for a valid linear-elastic K_IC test, so ASTM E1820 measures the J-integral instead and converts it to an equivalent K under plane strain. J = 50 kJ/m² on a steel with E = 205 GPa and ν = 0.3 corresponds to about 106 MPa√m.", ja: "靭性の高い鋼は降伏が大きすぎて線形弾性の K_IC 試験が成立しないので、ASTM E1820 では J積分を測り、平面ひずみの等価な K に換算します。E = 205GPa・ν = 0.3 の鋼で J = 50kJ/m² なら、およそ106MPa√mです。", es: "Los aceros tenaces ceden demasiado para un ensayo K_IC elástico lineal válido, así que ASTM E1820 mide en su lugar la integral J y la convierte en un K equivalente en deformación plana. J = 50 kJ/m² en un acero con E = 205 GPa y ν = 0,3 corresponde a unos 106 MPa√m.", "pt-BR": "Aços tenazes escoam demais para um ensaio K_IC linear-elástico válido, então a ASTM E1820 mede em vez disso a integral J e a converte em um K equivalente em estado plano de deformação. J = 50 kJ/m² em um aço com E = 205 GPa e ν = 0,3 corresponde a cerca de 106 MPa√m.", de: "Zähe Stähle fließen zu stark für einen gültigen linear-elastischen K_IC-Versuch, daher misst ASTM E1820 stattdessen das J-Integral und rechnet es unter ebenem Dehnungszustand in ein äquivalentes K um. J = 50 kJ/m² bei einem Stahl mit E = 205 GPa und ν = 0,3 entspricht etwa 106 MPa√m.", fr: "Les aciers tenaces plastifient trop pour un essai K_IC élastique linéaire valide ; l'ASTM E1820 mesure donc l'intégrale J et la convertit en un K équivalent en déformation plane. J = 50 kJ/m² pour un acier avec E = 205 GPa et ν = 0,3 correspond à environ 106 MPa√m." },
    localConstants: [
      { symbol: "J", expression: "50.0kJ/m^2" },
      { symbol: "E", expression: "205GPa" },
      { symbol: "ν", expression: "0.30" },
    ],
    steps: [
      { title: { en: "Equivalent fracture toughness K_J", ja: "等価な破壊靭性 K_J", es: "Tenacidad a la fractura equivalente K_J", "pt-BR": "Tenacidade à fratura equivalente K_J", de: "Äquivalente Bruchzähigkeit K_J", fr: "Ténacité équivalente K_J" }, expression: "√(J*E/(1-ν^2))", targetUnit: "MPa√m", formulaLatex: "K_J = \\sqrt{\\dfrac{JE}{1-\\nu^2}}" },
    ],
  },
  {
    title: { en: "Validity of a K_IC test: specimen size (ASTM E399)", ja: "K_IC試験の有効性：試験片寸法（ASTM E399）", es: "Validez de un ensayo K_IC: tamaño de la probeta (ASTM E399)", "pt-BR": "Validade de um ensaio K_IC: tamanho do corpo de prova (ASTM E399)", de: "Gültigkeit eines K_IC-Versuchs: Probengröße (ASTM E399)", fr: "Validité d'un essai K_IC : taille de l'éprouvette (ASTM E399)" },
    description: { en: "A K_Q result only counts as the plane-strain toughness K_IC if the specimen is large compared with the plastic zone: thickness B and crack length a must both exceed 2.5(K_Q/σ_YS)². For a high-strength steel (σ_YS = 1000 MPa) with K_Q = 60 MPa√m that is 9 mm, so the 1T C(T) specimen (B = 25 mm, a = 25 mm) qualifies.", ja: "K_Q の結果が平面ひずみ破壊靭性 K_IC として認められるのは、塑性域に比べて試験片が十分大きいときだけです。板厚 B とき裂長さ a がどちらも 2.5(K_Q/σ_YS)² 以上でなければなりません。高強度鋼（σ_YS = 1000MPa）で K_Q = 60MPa√m なら9mmで、1TのCT試験片（B = 25mm、a = 25mm）は条件を満たします。", es: "Un resultado K_Q solo cuenta como tenacidad a la fractura en deformación plana K_IC si la probeta es grande en comparación con la zona plástica: el espesor B y la longitud de grieta a deben superar ambos 2,5(K_Q/σ_YS)². Para un acero de alta resistencia (σ_YS = 1000 MPa) con K_Q = 60 MPa√m, eso son 9 mm, de modo que la probeta C(T) 1T (B = 25 mm, a = 25 mm) cumple.", "pt-BR": "Um resultado K_Q só vale como tenacidade à fratura em estado plano de deformação K_IC se o corpo de prova for grande em relação à zona plástica: a espessura B e o comprimento da trinca a devem ambos exceder 2,5(K_Q/σ_YS)². Para um aço de alta resistência (σ_YS = 1000 MPa) com K_Q = 60 MPa√m, isso dá 9 mm, de modo que o corpo de prova C(T) 1T (B = 25 mm, a = 25 mm) atende.", de: "Ein K_Q-Ergebnis zählt nur dann als Bruchzähigkeit K_IC im ebenen Dehnungszustand, wenn die Probe im Vergleich zur plastischen Zone groß ist: Dicke B und Risslänge a müssen beide größer als 2,5(K_Q/σ_YS)² sein. Für einen hochfesten Stahl (σ_YS = 1000 MPa) mit K_Q = 60 MPa√m sind das 9 mm, die 1T-C(T)-Probe (B = 25 mm, a = 25 mm) erfüllt die Bedingung also.", fr: "Un résultat K_Q ne vaut comme ténacité en déformation plane K_IC que si l'éprouvette est grande devant la zone plastique : l'épaisseur B et la longueur de fissure a doivent toutes deux dépasser 2,5(K_Q/σ_YS)². Pour un acier à haute résistance (σ_YS = 1000 MPa) avec K_Q = 60 MPa√m, cela donne 9 mm, de sorte que l'éprouvette C(T) 1T (B = 25 mm, a = 25 mm) convient." },
    localConstants: [
      { symbol: "K_Q", expression: "60.0MPa√m" },
      { symbol: "σ_YS", expression: "1000MPa" },
      { symbol: "B", expression: "25.0mm" },
    ],
    steps: [
      { title: { en: "Required minimum B and a", ja: "必要な最小の B と a", es: "B y a mínimos requeridos", "pt-BR": "B e a mínimos necessários", de: "Erforderliche Mindestwerte für B und a", fr: "B et a minimaux requis" }, expression: "2.5*(K_Q/σ_YS)^2", targetUnit: "mm", formulaLatex: "B,\\ a \\ge 2.5\\left(\\dfrac{K_Q}{\\sigma_{YS}}\\right)^2" },
      { title: { en: "Margin: B / required size", ja: "余裕：B ÷ 必要寸法", es: "Margen: B / tamaño requerido", "pt-BR": "Margem: B / tamanho necessário", de: "Reserve: B / erforderliche Größe", fr: "Marge : B / dimension requise" }, expression: "B/s1", targetUnit: "" },
    ],
  },
  {
    title: { en: "Critical crack length from fracture toughness", ja: "破壊靭性から臨界き裂長さ", es: "Longitud crítica de grieta a partir de la tenacidad a la fractura", "pt-BR": "Comprimento crítico de trinca a partir da tenacidade à fratura", de: "Kritische Risslänge aus der Bruchzähigkeit", fr: "Longueur critique de fissure à partir de la ténacité" },
    description: { en: "K = Yσ√(πa) links the stress, the crack size and the stress intensity. A 2 mm surface crack (Y = 1.12) under 400 MPa gives K ≈ 35 MPa√m. Turning the formula around with the material's K_IC = 60 MPa√m gives the crack length at which the part fractures: about 5.7 mm. That length is what inspection intervals are planned against.", ja: "K = Yσ√(πa) は、応力・き裂の大きさ・応力拡大係数を結ぶ式です。400MPaの応力下にある深さ2mmの表面き裂（Y = 1.12）では K ≈ 35MPa√m。これを材料の K_IC = 60MPa√m で逆に解くと、破壊するき裂長さはおよそ5.7mmです。点検間隔はこの長さを基準に決めます。", es: "K = Yσ√(πa) relaciona el esfuerzo, el tamaño de la grieta y el factor de intensidad de esfuerzos. Una grieta superficial de 2 mm (Y = 1,12) bajo 400 MPa da K ≈ 35 MPa√m. Despejando la fórmula con la K_IC = 60 MPa√m del material se obtiene la longitud de grieta a la que la pieza rompe: unos 5,7 mm. Con esa longitud se planifican los intervalos de inspección.", "pt-BR": "K = Yσ√(πa) relaciona a tensão, o tamanho da trinca e o fator de intensidade de tensão. Uma trinca superficial de 2 mm (Y = 1,12) sob 400 MPa dá K ≈ 35 MPa√m. Resolvendo a fórmula ao contrário com K_IC = 60 MPa√m do material, obtém-se o comprimento de trinca em que a peça fratura: cerca de 5,7 mm. É com esse comprimento que se planejam os intervalos de inspeção.", de: "K = Yσ√(πa) verknüpft die Spannung, die Rissgröße und den Spannungsintensitätsfaktor. Ein 2 mm langer Oberflächenriss (Y = 1,12) unter 400 MPa ergibt K ≈ 35 MPa√m. Stellt man die Formel mit der Bruchzähigkeit K_IC = 60 MPa√m des Werkstoffs um, erhält man die Risslänge, bei der das Bauteil bricht: etwa 5,7 mm. Nach dieser Länge richten sich die Prüfintervalle.", fr: "K = Yσ√(πa) relie la contrainte, la taille de la fissure et le facteur d'intensité de contrainte. Une fissure de surface de 2 mm (Y = 1,12) sous 400 MPa donne K ≈ 35 MPa√m. En inversant la formule avec la ténacité K_IC = 60 MPa√m du matériau, on obtient la longueur de fissure à laquelle la pièce rompt : environ 5,7 mm. C'est sur cette longueur que sont planifiés les intervalles d'inspection." },
    localConstants: [
      { symbol: "Y", expression: "1.12" },
      { symbol: "σ", expression: "400MPa" },
      { symbol: "a", expression: "2.00mm" },
      { symbol: "K_IC", expression: "60.0MPa√m" },
    ],
    steps: [
      { title: { en: "Stress intensity K at the present crack", ja: "現在のき裂の応力拡大係数 K", es: "Factor de intensidad de esfuerzos K en la grieta actual", "pt-BR": "Fator de intensidade de tensão K na trinca atual", de: "Spannungsintensitätsfaktor K am vorhandenen Riss", fr: "Facteur d'intensité de contrainte K pour la fissure actuelle" }, expression: "Y*σ*√(π*a)", targetUnit: "MPa√m", formulaLatex: "K = Y\\sigma\\sqrt{\\pi a}" },
      { title: { en: "Critical crack length a_c", ja: "臨界き裂長さ a_c", es: "Longitud crítica de grieta a_c", "pt-BR": "Comprimento crítico de trinca a_c", de: "Kritische Risslänge a_c", fr: "Longueur critique de fissure a_c" }, expression: "(K_IC/(Y*σ))^2/π", targetUnit: "mm", formulaLatex: "a_c = \\dfrac{1}{\\pi}\\left(\\dfrac{K_{IC}}{Y\\sigma}\\right)^2" },
    ],
  },
];
