import type { NotebookSeed } from "../types";

/**
 * 応力・ひずみ・安全率のカテゴリ。断面や支持条件に依らない「材料そのものの性質」を扱う
 * （はり・柱のように断面形状で決まる計算は source/materials.ts 側に置いている）。
 * 定数の既定値は実在の材料（ASTM A36 相当の炭素鋼: E=200GPa・σ_y=250MPa）から取り、
 * 出てくる数値がそのまま設計の判断材料として読めるようにしてある。
 */
export const ENG_STRESS_SEEDS: NotebookSeed[] = [
  {
    title: { en: "Axial stress & elongation of a tie rod", ja: "引張材の軸応力と伸び", es: "Esfuerzo axial y alargamiento de un tirante", "pt-BR": "Tensão axial e alongamento de um tirante", de: "Zugspannung und Verlängerung eines Zugstabs", fr: "Contrainte axiale et allongement d'un tirant" },
    description: { en: "A 200 mm² tie rod of ASTM A36 structural steel (E = 200 GPa, yield σ_y = 250 MPa) carries 25 kN of tension. The stress comes out at 125 MPa, exactly half the yield strength, and the 2 m rod stretches 1.25 mm.", ja: "断面積200mm²の引張材（ASTM A36相当の構造用鋼: E=200GPa、降伏応力 σ_y=250MPa）に25kNの引張力が働く場合を計算します。応力は125MPa＝降伏応力のちょうど半分、長さ2mの材の伸びは1.25mmになります。", es: "Un tirante de 200 mm² de acero estructural ASTM A36 (E = 200 GPa, límite elástico σ_y = 250 MPa) soporta una tracción de 25 kN. El esfuerzo resulta de 125 MPa, exactamente la mitad del límite elástico, y el tirante de 2 m se alarga 1,25 mm.", "pt-BR": "Um tirante de 200 mm² de aço estrutural ASTM A36 (E = 200 GPa, tensão de escoamento σ_y = 250 MPa) suporta uma tração de 25 kN. A tensão resulta em 125 MPa, exatamente metade da tensão de escoamento, e a barra de 2 m se alonga 1,25 mm.", de: "Ein Zugstab mit 200 mm² Querschnitt aus Baustahl ASTM A36 (E = 200 GPa, Streckgrenze σ_y = 250 MPa) nimmt 25 kN Zugkraft auf. Die Zugspannung beträgt 125 MPa, genau die Hälfte der Streckgrenze, und der 2 m lange Stab verlängert sich um 1,25 mm.", fr: "Un tirant de 200 mm² en acier de construction ASTM A36 (E = 200 GPa, limite d'élasticité σ_y = 250 MPa) reprend une traction de 25 kN. La contrainte vaut 125 MPa, exactement la moitié de la limite d'élasticité, et le tirant de 2 m s'allonge de 1,25 mm." },
    localConstants: [
      { symbol: "F", expression: "25kN" },
      { symbol: "A", expression: "200mm^2" },
      { symbol: "L", expression: "2m" },
      { symbol: "E", expression: "200GPa" },
    ],
    steps: [
      { title: { en: "Axial stress σ", ja: "軸応力 σ", es: "Esfuerzo axial σ", "pt-BR": "Tensão axial σ", de: "Zugspannung σ", fr: "Contrainte axiale σ" }, expression: "F/A", targetUnit: "MPa", formulaLatex: "\\sigma = \\dfrac{F}{A}" },
      { title: { en: "Elongation δ", ja: "伸び δ", es: "Alargamiento δ", "pt-BR": "Alongamento δ", de: "Verlängerung δ", fr: "Allongement δ" }, expression: "F*L/(A*E)", targetUnit: "mm", formulaLatex: "\\delta = \\dfrac{FL}{AE}" },
    ],
  },
  {
    title: { en: "Hooke's law for materials (σ = Eε) & microstrain", ja: "材料のフックの法則（σ = Eε）とマイクロストレイン", es: "Ley de Hooke para materiales (σ = Eε) y microdeformación", "pt-BR": "Lei de Hooke para materiais (σ = Eε) e microdeformação", de: "Hookesches Gesetz für Werkstoffe (σ = Eε) und Mikrodehnung", fr: "Loi de Hooke pour les matériaux (σ = Eε) et microdéformation" },
    description: { en: "This is the material form of Hooke's law: stress and strain are linked by Young's modulus alone, so it describes the steel itself and not one particular part. The spring form F = kx in the school science notebooks is different — its stiffness k changes with every length and cross-section. Strain is dimensionless, so the strain at yield of A36 steel (σ_y = 250 MPa, E = 200 GPa) reads naturally in ppm, which engineers call microstrain (µε).", ja: "こちらは「材料の」フックの法則です。応力とひずみを結ぶのは縦弾性係数（ヤング率）だけなので、部品の形に依らず鋼という材料そのものを表します。理科のノートにある「ばねの伸び」F = kx とは別物で、ばね定数kは長さや断面が変わるたびに変わります。ひずみは無次元なので、A36鋼（σ_y=250MPa、E=200GPa）の降伏時のひずみはppm＝マイクロストレイン（µε）で読むと分かりやすくなります。", es: "Esta es la forma material de la ley de Hooke: el esfuerzo y la deformación solo están ligados por el módulo de Young, de modo que describe al acero como material y no a una pieza concreta. La forma del resorte F = kx de las notas de ciencias escolares es otra cosa: su rigidez k cambia con cada longitud y cada sección. La deformación es adimensional, así que la deformación en el límite elástico del acero A36 (σ_y = 250 MPa, E = 200 GPa) se lee cómodamente en ppm, lo que los ingenieros llaman microdeformación (µε).", "pt-BR": "Esta é a forma material da lei de Hooke: a tensão mecânica e a deformação são ligadas apenas pelo módulo de Young, de modo que ela descreve o aço como material e não uma peça específica. A forma da mola F = kx das notas de ciências da escola é outra coisa: a rigidez k muda a cada comprimento e a cada seção. A deformação é adimensional, então a deformação no escoamento do aço A36 (σ_y = 250 MPa, E = 200 GPa) se lê naturalmente em ppm, o que os engenheiros chamam de microdeformação (µε).", de: "Dies ist die Werkstoffform des hookeschen Gesetzes: Mechanische Spannung und Dehnung sind allein über den Elastizitätsmodul verknüpft, sie beschreibt also den Stahl als Werkstoff und nicht ein bestimmtes Bauteil. Die Federform F = kx aus den Heften der Schulphysik ist etwas anderes – ihre Federkonstante k ändert sich mit jeder Länge und jedem Querschnitt. Die Dehnung ist dimensionslos, daher lässt sich die Dehnung an der Streckgrenze von A36-Stahl (σ_y = 250 MPa, E = 200 GPa) bequem in ppm ablesen, was Ingenieure Mikrodehnung (µε) nennen.", fr: "C'est la forme matérielle de la loi de Hooke : la contrainte et la déformation ne sont reliées que par le module de Young, elle décrit donc l'acier lui-même et non une pièce particulière. La forme du ressort F = kx des notes de sciences de l'école est tout autre chose : sa raideur k change avec chaque longueur et chaque section. La déformation est sans dimension, donc la déformation à la limite d'élasticité de l'acier A36 (σ_y = 250 MPa, E = 200 GPa) se lit commodément en ppm, ce que les ingénieurs appellent microdéformation (µε)." },
    localConstants: [
      { symbol: "E", expression: "200GPa" },
      { symbol: "ε", expression: "0.0012" },
      { symbol: "σ_y", expression: "250MPa" },
    ],
    steps: [
      { title: { en: "Stress from strain σ = Eε", ja: "ひずみから応力 σ = Eε", es: "Esfuerzo normal a partir de la deformación σ = Eε", "pt-BR": "Tensão normal a partir da deformação σ = Eε", de: "Normalspannung aus der Dehnung σ = Eε", fr: "Contrainte normale à partir de la déformation σ = Eε" }, expression: "E*ε", targetUnit: "MPa", formulaLatex: "\\sigma = E\\varepsilon" },
      { title: { en: "Strain at yield, in microstrain", ja: "降伏時のひずみ（マイクロストレイン）", es: "Deformación en el límite elástico, en microdeformación", "pt-BR": "Deformação no escoamento, em microdeformação", de: "Dehnung an der Streckgrenze, in Mikrodehnung", fr: "Déformation à la limite d'élasticité, en microdéformation" }, expression: "σ_y/E", targetUnit: "ppm", formulaLatex: "\\varepsilon = \\dfrac{\\sigma_y}{E}" },
    ],
  },
  {
    title: { en: "Poisson's ratio & lateral contraction", ja: "ポアソン比と横ひずみ", es: "Coeficiente de Poisson y contracción transversal", "pt-BR": "Coeficiente de Poisson e contração transversal", de: "Poissonzahl und Querkontraktion", fr: "Coefficient de Poisson et contraction transversale" },
    description: { en: "A bar stretched along its axis gets thinner across it. Poisson's ratio ν ties the lateral strain to the axial strain (ν ≈ 0.3 for steel, ≈ 0.33 for aluminium). Here a Ø20 mm bar is pulled to 0.001 axial strain, so it loses 6 µm of diameter.", ja: "軸方向に引き伸ばされた棒は、その分だけ横方向に細くなります。ポアソン比νは横ひずみと軸ひずみの比です（鋼で約0.3、アルミで約0.33）。ここでは直径20mmの丸棒を軸ひずみ0.001まで引っ張った場合を計算し、直径が6µm縮むことを確かめます。", es: "Una barra estirada a lo largo de su eje se adelgaza en sentido transversal. El coeficiente de Poisson ν relaciona la deformación transversal con la deformación axial (ν ≈ 0,3 para el acero, ≈ 0,33 para el aluminio). Aquí una barra de Ø20 mm se estira hasta una deformación axial de 0,001, por lo que pierde 6 µm de diámetro.", "pt-BR": "Uma barra esticada ao longo do eixo fica mais fina na direção transversal. O coeficiente de Poisson ν relaciona a deformação transversal com a deformação axial (ν ≈ 0,3 para o aço, ≈ 0,33 para o alumínio). Aqui uma barra de Ø20 mm é tracionada até uma deformação axial de 0,001 e perde 6 µm de diâmetro.", de: "Ein Stab, der in Achsrichtung gedehnt wird, wird quer dazu dünner. Die Poissonzahl ν verknüpft die Querdehnung mit der Längsdehnung (ν ≈ 0,3 bei Stahl, ≈ 0,33 bei Aluminium). Hier wird ein Stab mit Ø20 mm bis zu einer Längsdehnung von 0,001 gezogen und verliert dabei 6 µm Durchmesser.", fr: "Une barre étirée selon son axe s'amincit transversalement. Le coefficient de Poisson ν relie la déformation transversale à la déformation axiale (ν ≈ 0,3 pour l'acier, ≈ 0,33 pour l'aluminium). Ici une barre de Ø20 mm est tirée jusqu'à une déformation axiale de 0,001 et perd donc 6 µm de diamètre." },
    localConstants: [
      { symbol: "ν", expression: "0.3" },
      { symbol: "ε", expression: "0.001" },
      { symbol: "d", expression: "20mm" },
    ],
    steps: [
      { title: { en: "Lateral strain ε_lat", ja: "横ひずみ ε_lat", es: "Deformación transversal ε_lat", "pt-BR": "Deformação transversal ε_lat", de: "Querdehnung ε_lat", fr: "Déformation transversale ε_lat" }, expression: "-ν*ε", targetUnit: "", formulaLatex: "\\varepsilon_{lat} = -\\nu\\varepsilon" },
      { title: { en: "Change in diameter Δd", ja: "直径の変化 Δd", es: "Variación del diámetro Δd", "pt-BR": "Variação do diâmetro Δd", de: "Durchmesseränderung Δd", fr: "Variation du diamètre Δd" }, expression: "-ν*ε*d", targetUnit: "mm", formulaLatex: "\\Delta d = -\\nu\\varepsilon d" },
    ],
  },
  {
    title: { en: "Factor of safety & allowable stress", ja: "安全率と許容応力", es: "Factor de seguridad y esfuerzo admisible", "pt-BR": "Fator de segurança e tensão admissível", de: "Sicherheitsfaktor und zulässige Spannung", fr: "Coefficient de sécurité et contrainte admissible" },
    description: { en: "Two ways of using the same number. Dividing the yield strength of A36 steel (σ_y = 250 MPa) by the stress actually present gives the factor of safety of the part as built; dividing it by a required factor of safety instead gives the allowable stress you are permitted to design to.", ja: "同じ数字の2通りの使い方です。A36鋼の降伏応力（σ_y=250MPa）を実際に生じている応力で割ると、その部材の安全率が出ます。逆に必要な安全率で割ると、設計で超えてはいけない許容応力が出ます。", es: "Dos maneras de usar el mismo número. Al dividir el límite elástico del acero A36 (σ_y = 250 MPa) entre el esfuerzo realmente presente se obtiene el factor de seguridad de la pieza tal como está construida; al dividirlo entre un factor de seguridad exigido se obtiene el esfuerzo admisible con el que está permitido diseñar.", "pt-BR": "Duas maneiras de usar o mesmo número. Dividir a tensão de escoamento do aço A36 (σ_y = 250 MPa) pela tensão realmente presente dá o fator de segurança da peça como construída; dividi-la por um fator de segurança exigido dá a tensão admissível com a qual é permitido projetar.", de: "Zwei Arten, dieselbe Zahl zu verwenden. Teilt man die Streckgrenze von A36-Stahl (σ_y = 250 MPa) durch die tatsächlich vorhandene mechanische Spannung, erhält man den Sicherheitsfaktor des ausgeführten Bauteils; teilt man sie stattdessen durch einen geforderten Sicherheitsfaktor, erhält man die zulässige Spannung, mit der ausgelegt werden darf.", fr: "Deux façons d'utiliser le même nombre. Diviser la limite d'élasticité de l'acier A36 (σ_y = 250 MPa) par la contrainte réellement présente donne le coefficient de sécurité de la pièce telle qu'elle est réalisée ; la diviser par un coefficient de sécurité exigé donne la contrainte admissible avec laquelle il est permis de dimensionner." },
    localConstants: [
      { symbol: "σ_y", expression: "250MPa" },
      { symbol: "σ", expression: "125MPa" },
      { symbol: "n", expression: "2" },
    ],
    steps: [
      { title: { en: "Factor of safety n", ja: "安全率 n", es: "Factor de seguridad n", "pt-BR": "Fator de segurança n", de: "Sicherheitsfaktor n", fr: "Coefficient de sécurité n" }, expression: "σ_y/σ", targetUnit: "", formulaLatex: "n = \\dfrac{\\sigma_y}{\\sigma}" },
      { title: { en: "Allowable stress σ_allow", ja: "許容応力 σ_allow", es: "Esfuerzo admisible σ_allow", "pt-BR": "Tensão admissível σ_allow", de: "Zulässige Spannung σ_allow", fr: "Contrainte admissible σ_allow" }, expression: "σ_y/n", targetUnit: "MPa", formulaLatex: "\\sigma_{allow} = \\dfrac{\\sigma_y}{n}" },
    ],
  },
  {
    title: { en: "Thermal expansion & constrained thermal stress", ja: "熱膨張と拘束による熱応力", es: "Dilatación térmica y esfuerzo térmico por coacción", "pt-BR": "Dilatação térmica e tensão térmica por restrição", de: "Wärmedehnung und Wärmespannung bei behinderter Dehnung", fr: "Dilatation thermique et contrainte thermique en dilatation empêchée" },
    description: { en: "A 6 m steel member (α = 12×10⁻⁶ /K, E = 200 GPa) warmed by 40 K wants to grow 2.88 mm. If both ends are held so it cannot grow at all, that same movement turns into 96 MPa of compressive stress — and note that the stress does not depend on the length at all.", ja: "長さ6mの鋼材（α=12×10⁻⁶ /K、E=200GPa）が40K温まると、2.88mm伸びようとします。両端を完全に拘束して伸びを止めると、その伸びがそのまま96MPaの圧縮応力に変わります。応力の方は長さに全く依らない点に注目してください。", es: "Una pieza de acero de 6 m (α = 12×10⁻⁶ /K, E = 200 GPa) calentada 40 K tiende a alargarse 2,88 mm. Si se sujetan ambos extremos de modo que no pueda alargarse nada, ese mismo movimiento se convierte en 96 MPa de esfuerzo de compresión, y conviene fijarse en que ese esfuerzo no depende en absoluto de la longitud.", "pt-BR": "Uma peça de aço de 6 m (α = 12×10⁻⁶ /K, E = 200 GPa) aquecida em 40 K tende a se alongar 2,88 mm. Se as duas extremidades forem travadas de modo que ela não possa se alongar, esse mesmo movimento vira 96 MPa de tensão de compressão; note que essa tensão não depende em nada do comprimento.", de: "Ein 6 m langes Stahlbauteil (α = 12×10⁻⁶ /K, E = 200 GPa), das um 40 K erwärmt wird, will sich um 2,88 mm ausdehnen. Werden beide Enden so festgehalten, dass es sich überhaupt nicht ausdehnen kann, wird genau diese Bewegung zu 96 MPa Druckspannung – und die Wärmespannung hängt überhaupt nicht von der Länge ab.", fr: "Une pièce en acier de 6 m (α = 12×10⁻⁶ /K, E = 200 GPa) chauffée de 40 K tend à s'allonger de 2,88 mm. Si les deux extrémités sont bloquées de sorte qu'elle ne puisse pas s'allonger du tout, ce même déplacement se transforme en 96 MPa de contrainte de compression, et il faut noter que cette contrainte ne dépend pas du tout de la longueur." },
    localConstants: [
      { symbol: "α", expression: "12e-6/K" },
      { symbol: "ΔT", expression: "40K" },
      { symbol: "E", expression: "200GPa" },
      { symbol: "L", expression: "6m" },
    ],
    steps: [
      { title: { en: "Free expansion δ_T", ja: "自由な伸び δ_T", es: "Dilatación libre δ_T", "pt-BR": "Dilatação livre δ_T", de: "Freie Wärmedehnung δ_T", fr: "Dilatation libre δ_T" }, expression: "α*L*ΔT", targetUnit: "mm", formulaLatex: "\\delta_T = \\alpha L \\Delta T" },
      { title: { en: "Fully constrained stress σ_th", ja: "完全拘束時の熱応力 σ_th", es: "Esfuerzo térmico con coacción total σ_th", "pt-BR": "Tensão térmica com restrição total σ_th", de: "Wärmespannung bei vollständig behinderter Dehnung σ_th", fr: "Contrainte thermique en dilatation totalement empêchée σ_th" }, expression: "E*α*ΔT", targetUnit: "MPa", formulaLatex: "\\sigma_{th} = E\\alpha\\Delta T" },
    ],
  },
  {
    title: { en: "Pin in double shear & bearing stress", ja: "ピンの二面せん断と支圧応力", es: "Pasador a doble cortadura y esfuerzo de aplastamiento", "pt-BR": "Pino em corte duplo e tensão de esmagamento", de: "Bolzen in zweischnittiger Scherung und Lochleibungsspannung", fr: "Axe en double cisaillement et pression diamétrale" },
    description: { en: "A Ø16 mm pin joining a 10 mm plate carries 30 kN. In a double-shear joint the pin is cut by two planes, so each one takes half the load — that is the factor of 2. The bearing stress the pin presses onto the hole wall is a different check with a different area (d×t), and here it is the larger of the two.", ja: "厚さ10mmの板を留める直径16mmのピンに30kNが働く場合です。二面せん断の継手ではピンが2つの面で切られるので、1面あたりの荷重は半分になります（式の2はこれです）。一方、ピンが穴の内壁を押す支圧応力は、面積の取り方（d×t）が異なる別の検定で、この例では支圧応力の方が大きくなります。", es: "Un pasador de Ø16 mm que une una chapa de 10 mm soporta 30 kN. En una unión a doble cortadura el pasador queda cortado por dos planos, así que cada uno toma la mitad de la carga: de ahí el factor 2. El esfuerzo de aplastamiento con el que el pasador presiona la pared del agujero es una comprobación distinta, con otra área (d×t), y aquí resulta ser el mayor de los dos.", "pt-BR": "Um pino de Ø16 mm que une uma chapa de 10 mm suporta 30 kN. Em uma ligação em corte duplo o pino é cortado por dois planos, então cada um recebe metade da carga: é daí que vem o fator 2. A tensão de esmagamento com que o pino pressiona a parede do furo é uma verificação diferente, com outra área (d×t), e aqui ela é a maior das duas.", de: "Ein Bolzen mit Ø16 mm, der ein 10 mm dickes Blech verbindet, nimmt 30 kN auf. Bei einer zweischnittigen Verbindung wird der Bolzen von zwei Ebenen geschnitten, jede nimmt also die halbe Last auf – daher der Faktor 2. Die Lochleibungsspannung, mit der der Bolzen gegen die Lochwand drückt, ist ein anderer Nachweis mit einer anderen Fläche (d×t) und hier der größere der beiden Werte.", fr: "Un axe de Ø16 mm assemblant une tôle de 10 mm reprend 30 kN. Dans un assemblage en double cisaillement, l'axe est coupé par deux plans, chacun reprend donc la moitié de la charge : c'est de là que vient le facteur 2. La pression diamétrale exercée par l'axe sur la paroi du trou est une vérification différente, avec une autre aire (d×t), et c'est ici la plus grande des deux." },
    localConstants: [
      { symbol: "F", expression: "30kN" },
      { symbol: "d", expression: "16mm" },
      { symbol: "t", expression: "10mm" },
      { symbol: "A", expression: "pi*d^2/4" },
    ],
    steps: [
      { title: { en: "Shear stress in double shear τ", ja: "二面せん断のせん断応力 τ", es: "Esfuerzo cortante a doble cortadura τ", "pt-BR": "Tensão de cisalhamento em corte duplo τ", de: "Schubspannung bei zweischnittiger Scherung τ", fr: "Contrainte de cisaillement en double cisaillement τ" }, expression: "F/(2*A)", targetUnit: "MPa", formulaLatex: "\\tau = \\dfrac{F}{2A}" },
      { title: { en: "Bearing stress σ_b", ja: "支圧応力 σ_b", es: "Esfuerzo de aplastamiento σ_b", "pt-BR": "Tensão de esmagamento σ_b", de: "Lochleibungsspannung σ_b", fr: "Pression diamétrale σ_b" }, expression: "F/(d*t)", targetUnit: "MPa", formulaLatex: "\\sigma_b = \\dfrac{F}{dt}" },
    ],
  },
  {
    title: { en: "Principal stresses & maximum shear (Mohr's circle)", ja: "主応力と最大せん断応力（モールの円）", es: "Esfuerzos principales y cortante máximo (círculo de Mohr)", "pt-BR": "Tensões principais e cisalhamento máximo (círculo de Mohr)", de: "Hauptspannungen und maximale Schubspannung (Mohrscher Spannungskreis)", fr: "Contraintes principales et cisaillement maximal (cercle de Mohr)" },
    description: { en: "A point under σx = 120 MPa, σy = 40 MPa and τxy = 30 MPa. Mohr's circle is centred at the average of the two normal stresses with radius R; the principal stresses are the two ends of that circle, and R itself is the maximum shear stress. Rotate the element to that angle and the shear disappears — 130 MPa and 30 MPa are all that is left.", ja: "σx=120MPa、σy=40MPa、τxy=30MPaが働く点を考えます。モールの円は2つの垂直応力の平均を中心とし、半径がRです。主応力はこの円の両端で、半径Rそのものが最大せん断応力になります。この角度まで要素を回転させるとせん断応力が消え、130MPaと30MPaだけが残ります。", es: "Un punto sometido a σx = 120 MPa, σy = 40 MPa y τxy = 30 MPa. El círculo de Mohr está centrado en el promedio de los dos esfuerzos normales y tiene radio R; los esfuerzos principales son los dos extremos de ese círculo, y el propio R es el esfuerzo cortante máximo. Al girar el elemento hasta ese ángulo, el cortante desaparece: solo quedan 130 MPa y 30 MPa.", "pt-BR": "Um ponto submetido a σx = 120 MPa, σy = 40 MPa e τxy = 30 MPa. O círculo de Mohr tem centro na média das duas tensões normais e raio R; as tensões principais são as duas extremidades desse círculo, e o próprio R é a tensão de cisalhamento máxima. Girando o elemento até esse ângulo, o cisalhamento desaparece: sobram apenas 130 MPa e 30 MPa.", de: "Ein Punkt unter σx = 120 MPa, σy = 40 MPa und τxy = 30 MPa. Der Mohrsche Spannungskreis hat seinen Mittelpunkt im Mittelwert der beiden Normalspannungen und den Radius R; die Hauptspannungen sind die beiden Enden dieses Kreises, und R selbst ist die maximale Schubspannung. Dreht man das Element in diesen Winkel, verschwindet die Schubspannung – es bleiben nur 130 MPa und 30 MPa übrig.", fr: "Un point soumis à σx = 120 MPa, σy = 40 MPa et τxy = 30 MPa. Le cercle de Mohr est centré sur la moyenne des deux contraintes normales et a pour rayon R ; les contraintes principales sont les deux extrémités de ce cercle, et R lui-même est la contrainte de cisaillement maximale. En tournant l'élément jusqu'à cet angle, le cisaillement disparaît : il ne reste que 130 MPa et 30 MPa." },
    localConstants: [
      { symbol: "σₓ", expression: "120MPa" },
      { symbol: "σ_y", expression: "40MPa" },
      { symbol: "τ_xy", expression: "30MPa" },
      { symbol: "R", expression: "sqrt(((σₓ-σ_y)/2)^2+τ_xy^2)" },
    ],
    steps: [
      { title: { en: "Major principal stress σ₁", ja: "第1主応力 σ₁", es: "Esfuerzo principal mayor σ₁", "pt-BR": "Tensão principal maior σ₁", de: "Größte Hauptspannung σ₁", fr: "Contrainte principale majeure σ₁" }, expression: "(σₓ+σ_y)/2+R", targetUnit: "MPa", formulaLatex: "\\sigma_1 = \\dfrac{\\sigma_x+\\sigma_y}{2} + R" },
      { title: { en: "Minor principal stress σ₂", ja: "第2主応力 σ₂", es: "Esfuerzo principal menor σ₂", "pt-BR": "Tensão principal menor σ₂", de: "Kleinste Hauptspannung σ₂", fr: "Contrainte principale mineure σ₂" }, expression: "(σₓ+σ_y)/2-R", targetUnit: "MPa", formulaLatex: "\\sigma_2 = \\dfrac{\\sigma_x+\\sigma_y}{2} - R" },
      { title: { en: "Maximum shear stress τ_max", ja: "最大せん断応力 τ_max", es: "Esfuerzo cortante máximo τ_max", "pt-BR": "Tensão de cisalhamento máxima τ_max", de: "Maximale Schubspannung τ_max", fr: "Contrainte de cisaillement maximale τ_max" }, expression: "R", targetUnit: "MPa", formulaLatex: "\\tau_{max} = R" },
    ],
  },
  {
    title: { en: "Stress concentration at a hole", ja: "穴まわりの応力集中", es: "Concentración de esfuerzos en un agujero", "pt-BR": "Concentração de tensões em um furo", de: "Spannungskonzentration am Loch", fr: "Concentration de contraintes au bord d'un trou" },
    description: { en: "A 60 mm wide, 8 mm thick strap with a Ø20 mm hole carries 15 kN. Spreading the load over the remaining net section gives only 46.9 MPa, but the stress crowds around the edge of the hole: with a concentration factor K_t of about 2.4 the real peak is 112.5 MPa. This peak, not the nominal value, is what starts a fatigue crack.", ja: "幅60mm・厚さ8mmの帯板に直径20mmの穴が開き、15kNが働く場合です。穴を除いた正味断面で荷重を均すと46.9MPaにしかなりませんが、応力は穴の縁に集中します。応力集中係数K_tを2.4とすると実際のピークは112.5MPaです。疲労き裂の起点になるのは公称応力ではなくこのピーク値です。", es: "Una pletina de 60 mm de ancho y 8 mm de espesor con un agujero de Ø20 mm soporta 15 kN. Al repartir la carga sobre la sección neta restante solo salen 46,9 MPa, pero el esfuerzo se agolpa en el borde del agujero: con un factor de concentración K_t de aproximadamente 2,4, el pico real es de 112,5 MPa. Lo que inicia una grieta por fatiga es ese pico, no el valor nominal.", "pt-BR": "Uma barra chata de 60 mm de largura e 8 mm de espessura com um furo de Ø20 mm suporta 15 kN. Distribuindo a carga pela seção líquida restante saem apenas 46,9 MPa, mas a tensão se concentra na borda do furo: com um fator de concentração K_t de cerca de 2,4, o pico real é de 112,5 MPa. O que inicia uma trinca por fadiga é esse pico, não o valor nominal.", de: "Ein 60 mm breiter und 8 mm dicker Flachstahl mit einem Loch von Ø20 mm nimmt 15 kN auf. Verteilt man die Last über den verbleibenden Restquerschnitt, ergeben sich nur 46,9 MPa, doch die Zugspannung drängt sich am Lochrand zusammen: mit einer Formzahl K_t von etwa 2,4 liegt die tatsächliche Spitze bei 112,5 MPa. Ein Ermüdungsriss geht von dieser Spitze aus, nicht von der Nennspannung.", fr: "Un fer plat de 60 mm de largeur et 8 mm d'épaisseur percé d'un trou de Ø20 mm reprend 15 kN. En répartissant la charge sur la section nette restante, on n'obtient que 46,9 MPa, mais la contrainte se concentre au bord du trou : avec un coefficient de concentration K_t d'environ 2,4, le pic réel atteint 112,5 MPa. C'est ce pic, et non la valeur nominale, qui amorce une fissure de fatigue." },
    localConstants: [
      { symbol: "F", expression: "15kN" },
      { symbol: "w", expression: "60mm" },
      { symbol: "d", expression: "20mm" },
      { symbol: "t", expression: "8mm" },
      { symbol: "Kₜ", expression: "2.4" },
    ],
    steps: [
      { title: { en: "Nominal stress on the net section σ_nom", ja: "正味断面の公称応力 σ_nom", es: "Esfuerzo nominal en la sección neta σ_nom", "pt-BR": "Tensão nominal na seção líquida σ_nom", de: "Nennspannung im Restquerschnitt σ_nom", fr: "Contrainte nominale sur la section nette σ_nom" }, expression: "F/((w-d)*t)", targetUnit: "MPa", formulaLatex: "\\sigma_{nom} = \\dfrac{F}{(w-d)t}" },
      { title: { en: "Peak stress at the hole σ_max", ja: "穴の縁のピーク応力 σ_max", es: "Esfuerzo pico en el borde del agujero σ_max", "pt-BR": "Tensão de pico na borda do furo σ_max", de: "Spitzenspannung am Lochrand σ_max", fr: "Contrainte maximale au bord du trou σ_max" }, expression: "Kₜ*F/((w-d)*t)", targetUnit: "MPa", formulaLatex: "\\sigma_{max} = K_t\\dfrac{F}{(w-d)t}" },
    ],
  },
];
