import type { NotebookSeed } from "../types";

/**
 * はり・柱のカテゴリ。幅b・高さh・スパンL・等分布荷重wなどの記号はカテゴリ内で使い回し、統一感を持たせている。
 * 既定値はカタログに実在する断面（C24の45×195根太、IPE 200、φ60×5パイプ）と、その材料の
 * 実際の値（構造用鋼S275: E=210GPa・f_y=275MPa／製材C24: E=11GPa・f_m,k=24MPa）を組み合わせてある。
 * 断面と材料が噛み合っていないと、出てくる応力もたわみも設計の判断に使えない数字になるため。
 */
export const MATERIALS_SEEDS: NotebookSeed[] = [
  {
    title: { en: "Timber floor joist check (C24, 45×195)", ja: "木造床根太の検定（C24・45×195）", es: "Comprobación de una vigueta de madera (C24, 45×195)", "pt-BR": "Verificação de uma vigota de madeira (C24, 45×195)", de: "Nachweis eines Deckenbalkens aus Holz (C24, 45×195)", fr: "Vérification d'une solive en bois (C24, 45×195)" },
    description: { en: "A 45×195 mm C24 timber joist (E = 11 GPa, bending strength f_m,k = 24 MPa) spanning 3.6 m carries 2 kN/m. Strength passes easily at 11.4 MPa, under half of f_m,k — but the last step divides the deflection by the usual floor limit of span/300 (12 mm). The ratio comes out above 1, so this joist fails on deflection: the floor would feel bouncy long before it broke. Deflection, not strength, is what sizes most timber floors.", ja: "スパン3.6mに45×195mmのC24製材の根太（E=11GPa、曲げ強度 f_m,k=24MPa）を架け、2kN/mの荷重を受ける場合です。曲げ応力は11.4MPaでf_m,kの半分以下、強度は余裕で満たします。ところが最後の手順でたわみを床の一般的な制限値スパン/300（12mm）で割ると、比が1を超えて不合格になります。壊れるずっと手前で床がふわふわして使えないということです。木造の床の断面は、強度ではなくたわみで決まるのが普通です。", es: "Una vigueta de madera C24 de 45×195 mm (E = 11 GPa, resistencia a flexión f_m,k = 24 MPa) con un vano de 3,6 m soporta 2 kN/m. La resistencia se cumple con holgura: 11,4 MPa, menos de la mitad de f_m,k. Pero el último paso divide la flecha por el límite habitual de los forjados, luz/300 (12 mm), y la relación sale por encima de 1: esta vigueta no cumple a flecha. El suelo se sentiría flexible mucho antes de llegar a romperse. En la mayoría de los forjados de madera es la flecha, y no la resistencia, la que fija la sección.", "pt-BR": "Uma vigota de madeira C24 de 45×195 mm (E = 11 GPa, resistência à flexão f_m,k = 24 MPa) com vão de 3,6 m suporta 2 kN/m. A resistência é atendida com folga: 11,4 MPa, menos da metade de f_m,k. Mas o último passo divide a flecha pelo limite usual dos pisos, vão/300 (12 mm), e a razão fica acima de 1: esta vigota não atende à flecha. O piso pareceria bambo muito antes de chegar a romper. Na maioria dos pisos de madeira é a flecha, e não a resistência, que define a seção.", de: "Ein Deckenbalken aus C24-Holz mit 45×195 mm (E = 11 GPa, Biegefestigkeit f_m,k = 24 MPa) über eine Spannweite von 3,6 m trägt 2 kN/m. Der Festigkeitsnachweis ist mit 11,4 MPa mühelos erfüllt, weniger als die Hälfte von f_m,k. Im letzten Schritt wird die Durchbiegung jedoch durch die übliche Deckengrenze Spannweite/300 (12 mm) geteilt, und das Verhältnis liegt über 1: Der Durchbiegungsnachweis ist damit nicht erfüllt. Der Boden würde lange vor dem Bruch federn. Bei den meisten Holzdecken bestimmt die Durchbiegung den Querschnitt, nicht die Festigkeit.", fr: "Une solive en bois C24 de 45×195 mm (E = 11 GPa, résistance à la flexion f_m,k = 24 MPa) sur une portée de 3,6 m porte 2 kN/m. La résistance est satisfaite largement : 11,4 MPa, moins de la moitié de f_m,k. Mais la dernière étape divise la flèche par la limite habituelle des planchers, portée/300 (12 mm), et le rapport dépasse 1 : cette solive ne satisfait pas la vérification de flèche. Le plancher serait souple bien avant de rompre. Pour la plupart des planchers en bois, c'est la flèche, et non la résistance, qui détermine la section." },
    localConstants: [
      { symbol: "b", expression: "45mm" },
      { symbol: "h", expression: "195mm" },
      { symbol: "L", expression: "3.6m" },
      { symbol: "w", expression: "2kN/m" },
      { symbol: "E", expression: "11GPa" },
      { symbol: "I", expression: "b*h^3/12" },
      { symbol: "Z", expression: "b*h^2/6" },
    ],
    steps: [
      { title: { en: "Maximum bending moment M", ja: "最大曲げモーメント M", es: "Momento flector máximo M", "pt-BR": "Momento fletor máximo M", de: "Maximales Biegemoment M", fr: "Moment fléchissant maximal M" }, expression: "w*L^2/8", targetUnit: "kN*m", formulaLatex: "M = \\dfrac{wL^2}{8}" },
      { title: { en: "Bending stress σ (vs f_m,k = 24 MPa)", ja: "曲げ応力 σ（f_m,k=24MPaと比較）", es: "Esfuerzo de flexión σ (frente a f_m,k = 24 MPa)", "pt-BR": "Tensão de flexão σ (comparada a f_m,k = 24 MPa)", de: "Biegespannung σ (gegenüber f_m,k = 24 MPa)", fr: "Contrainte de flexion σ (par rapport à f_m,k = 24 MPa)" }, expression: "w*L^2/(8*Z)", targetUnit: "MPa", formulaLatex: "\\sigma = \\dfrac{wL^2}{8Z}" },
      { title: { en: "Midspan deflection δ", ja: "スパン中央のたわみ δ", es: "Flecha en el centro del vano δ", "pt-BR": "Flecha no meio do vão δ", de: "Durchbiegung in Feldmitte δ", fr: "Flèche à mi-portée δ" }, expression: "5*w*L^4/(384*E*I)", targetUnit: "mm", formulaLatex: "\\delta = \\dfrac{5wL^4}{384EI}" },
      { title: { en: "Deflection check δ ÷ (L/300) — over 1 means fail", ja: "たわみの検定 δ ÷ (L/300)（1を超えたら不合格）", es: "Comprobación de flecha δ ÷ (L/300) — por encima de 1 no cumple", "pt-BR": "Verificação de flecha δ ÷ (L/300) — acima de 1 não atende", de: "Durchbiegungsnachweis δ ÷ (L/300) — über 1 nicht erfüllt", fr: "Vérification de flèche δ ÷ (L/300) — au-dessus de 1, non satisfait" }, expression: "s3/(L/300)", targetUnit: "", formulaLatex: "\\dfrac{\\delta}{L/300}" },
    ],
  },
  {
    title: { en: "Steel beam IPE 200 under a uniform load", ja: "鋼製はり IPE 200（等分布荷重）", es: "Viga de acero IPE 200 con carga uniformemente distribuida", "pt-BR": "Viga de aço IPE 200 com carga uniformemente distribuída", de: "Stahlträger IPE 200 unter gleichmäßig verteilter Last", fr: "Poutre en acier IPE 200 sous charge uniformément répartie" },
    description: { en: "An IPE 200 rolled section in S275 steel (E = 210 GPa, f_y = 275 MPa) spanning 5 m under 10 kN/m. Section properties come straight off the catalogue in the units it prints them in — I = 1943 cm⁴ and Z = 194 cm³ — and the calculator converts them, which is the real point of this notebook. Stress lands at 161 MPa against f_y = 275 MPa, and the deflection just squeaks under the span/250 limit of 20 mm.", ja: "スパン5mにS275鋼のIPE 200（E=210GPa、f_y=275MPa）を架け、10kN/mを受ける場合です。断面性能はカタログの表記のまま I=1943cm⁴、Z=194cm³ と入力しています。これを電卓側が換算してくれるところがこのノートの要点です。曲げ応力は161MPaでf_y=275MPaに対し余裕があり、たわみはスパン/250＝20mmをぎりぎり満たします。", es: "Un perfil laminado IPE 200 de acero S275 (E = 210 GPa, f_y = 275 MPa) con un vano de 5 m bajo 10 kN/m. Las características de la sección se introducen tal como las imprime el catálogo, en sus propias unidades —I = 1943 cm⁴ y Z = 194 cm³—, y la calculadora se encarga de convertirlas: ese es el verdadero objetivo de este cuaderno. El esfuerzo de flexión queda en 161 MPa frente a f_y = 275 MPa, y la flecha cumple por muy poco el límite luz/250 de 20 mm.", "pt-BR": "Um perfil laminado IPE 200 de aço S275 (E = 210 GPa, f_y = 275 MPa) com vão de 5 m sob 10 kN/m. As propriedades da seção são inseridas exatamente como o catálogo as publica, nas unidades dele — I = 1943 cm⁴ e Z = 194 cm³ —, e a calculadora faz a conversão: esse é o verdadeiro objetivo deste caderno. A tensão de flexão fica em 161 MPa contra f_y = 275 MPa, e a flecha passa raspando no limite vão/250 de 20 mm.", de: "Ein Walzprofil IPE 200 aus Stahl S275 (E = 210 GPa, f_y = 275 MPa) über eine Spannweite von 5 m unter 10 kN/m. Die Querschnittswerte werden genau so eingegeben, wie sie im Katalog stehen — I = 1943 cm⁴ und Z = 194 cm³ —, und der Rechner rechnet sie um: Das ist der eigentliche Sinn dieses Rechenhefts. Die Biegespannung liegt bei 161 MPa gegenüber f_y = 275 MPa, und die Durchbiegung bleibt gerade eben unter der Grenze Spannweite/250 von 20 mm.", fr: "Un profilé laminé IPE 200 en acier S275 (E = 210 GPa, f_y = 275 MPa) sur une portée de 5 m sous 10 kN/m. Les caractéristiques de section sont saisies telles que le catalogue les publie, dans ses propres unités — I = 1943 cm⁴ et Z = 194 cm³ —, et la calculatrice les convertit : c'est là tout l'intérêt de ce carnet. La contrainte de flexion s'établit à 161 MPa face à f_y = 275 MPa, et la flèche passe tout juste sous la limite portée/250 de 20 mm." },
    localConstants: [
      { symbol: "L", expression: "5m" },
      { symbol: "w", expression: "10kN/m" },
      { symbol: "E", expression: "210GPa" },
      { symbol: "I", expression: "1943cm^4" },
      { symbol: "Z", expression: "194cm^3" },
    ],
    steps: [
      { title: { en: "Maximum bending moment M", ja: "最大曲げモーメント M", es: "Momento flector máximo M", "pt-BR": "Momento fletor máximo M", de: "Maximales Biegemoment M", fr: "Moment fléchissant maximal M" }, expression: "w*L^2/8", targetUnit: "kN*m", formulaLatex: "M = \\dfrac{wL^2}{8}" },
      { title: { en: "Bending stress σ (vs f_y = 275 MPa)", ja: "曲げ応力 σ（f_y=275MPaと比較）", es: "Esfuerzo de flexión σ (frente a f_y = 275 MPa)", "pt-BR": "Tensão de flexão σ (comparada a f_y = 275 MPa)", de: "Biegespannung σ (gegenüber f_y = 275 MPa)", fr: "Contrainte de flexion σ (par rapport à f_y = 275 MPa)" }, expression: "w*L^2/(8*Z)", targetUnit: "MPa", formulaLatex: "\\sigma = \\dfrac{wL^2}{8Z}" },
      { title: { en: "Midspan deflection δ (limit L/250 = 20 mm)", ja: "スパン中央のたわみ δ（制限値 L/250＝20mm）", es: "Flecha en el centro del vano δ (límite L/250 = 20 mm)", "pt-BR": "Flecha no meio do vão δ (limite L/250 = 20 mm)", de: "Durchbiegung in Feldmitte δ (Grenzwert L/250 = 20 mm)", fr: "Flèche à mi-portée δ (limite L/250 = 20 mm)" }, expression: "5*w*L^4/(384*E*I)", targetUnit: "mm", formulaLatex: "\\delta = \\dfrac{5wL^4}{384EI}" },
    ],
  },
  {
    title: { en: "Cantilever with an end point load (steel flat bar)", ja: "片持ちはり・先端集中荷重（鋼の平鋼）", es: "Viga en voladizo con carga puntual en el extremo (pletina de acero)", "pt-BR": "Viga em balanço com carga concentrada na extremidade (barra chata de aço)", de: "Kragträger mit Einzellast am freien Ende (Flachstahl)", fr: "Poutre en console avec charge ponctuelle à l'extrémité (fer plat en acier)" },
    description: { en: "A 500 mm long 8×80 mm steel flat bar (S275, E = 210 GPa) bolted flat-side-vertical to a wall, with 1 kN hung on the free end — a shelf bracket or a small machine arm. A cantilever bends far more than a simply supported beam of the same span, and the fixed end is where both the moment and the stress peak.", ja: "長さ500mmの8×80mm平鋼（S275、E=210GPa）を壁に片持ちで取り付け、先端に1kNを吊るす場合です（棚受けや小さな機械アームを想像してください）。片持ちはりは同じスパンの単純ばりよりはるかに大きくたわみ、モーメントも応力も固定端で最大になります。", es: "Una pletina de acero de 8×80 mm y 500 mm de largo (S275, E = 210 GPa) atornillada a una pared con el canto en vertical, con 1 kN colgado del extremo libre: una ménsula de estante o un pequeño brazo de máquina. Un voladizo flecta mucho más que una viga simplemente apoyada del mismo vano, y tanto el momento como el esfuerzo de flexión alcanzan su máximo en el empotramiento.", "pt-BR": "Uma barra chata de aço de 8×80 mm e 500 mm de comprimento (S275, E = 210 GPa) parafusada à parede com a face maior na vertical, com 1 kN pendurado na extremidade livre: um suporte de prateleira ou um pequeno braço de máquina. Uma viga em balanço deforma muito mais do que uma viga simplesmente apoiada de mesmo vão, e tanto o momento quanto a tensão de flexão são máximos no engastamento.", de: "Ein 500 mm langer Flachstahl 8×80 mm (S275, E = 210 GPa), hochkant an eine Wand geschraubt, mit 1 kN am freien Ende — eine Regalkonsole oder ein kleiner Maschinenarm. Ein Kragträger biegt sich weit stärker durch als ein beidseitig gelenkig gelagerter Balken gleicher Spannweite, und sowohl das Biegemoment als auch die Biegespannung erreichen an der Einspannung ihr Maximum.", fr: "Un fer plat en acier de 8×80 mm et 500 mm de long (S275, E = 210 GPa), boulonné sur un mur avec le grand côté à la verticale, et 1 kN suspendu à l'extrémité libre : une équerre d'étagère ou un petit bras de machine. Une poutre en console fléchit bien plus qu'une poutre simplement appuyée de même portée, et le moment comme la contrainte de flexion sont maximaux à l'encastrement." },
    localConstants: [
      { symbol: "P", expression: "1kN" },
      { symbol: "L", expression: "0.5m" },
      { symbol: "b", expression: "8mm" },
      { symbol: "h", expression: "80mm" },
      { symbol: "E", expression: "210GPa" },
      { symbol: "I", expression: "b*h^3/12" },
      { symbol: "Z", expression: "b*h^2/6" },
    ],
    steps: [
      { title: { en: "Moment at the fixed end M", ja: "固定端の曲げモーメント M", es: "Momento en el empotramiento M", "pt-BR": "Momento no engastamento M", de: "Biegemoment an der Einspannung M", fr: "Moment à l'encastrement M" }, expression: "P*L", targetUnit: "N*m", formulaLatex: "M = PL" },
      { title: { en: "Bending stress σ", ja: "曲げ応力 σ", es: "Esfuerzo de flexión σ", "pt-BR": "Tensão de flexão σ", de: "Biegespannung σ", fr: "Contrainte de flexion σ" }, expression: "P*L/Z", targetUnit: "MPa", formulaLatex: "\\sigma = \\dfrac{PL}{Z}" },
      { title: { en: "Tip deflection δ", ja: "先端のたわみ δ", es: "Flecha en el extremo δ", "pt-BR": "Flecha na extremidade δ", de: "Durchbiegung am freien Ende δ", fr: "Flèche à l'extrémité δ" }, expression: "P*L^3/(3*E*I)", targetUnit: "mm", formulaLatex: "\\delta = \\dfrac{PL^3}{3EI}" },
    ],
  },
  {
    title: { en: "Cantilever under a uniform load", ja: "片持ちはり・等分布荷重", es: "Viga en voladizo con carga uniformemente distribuida", "pt-BR": "Viga em balanço com carga uniformemente distribuída", de: "Kragträger unter gleichmäßig verteilter Last", fr: "Poutre en console sous charge uniformément répartie" },
    description: { en: "The same 8×80 mm steel section (S275, E = 210 GPa), now 1.2 m long and carrying 1.5 kN/m spread along it instead of a point load at the tip — a canopy rib or a shelf loaded over its whole length. Compare the coefficients with the point-load case: wL²/2 and wL⁴/(8EI).", ja: "同じ8×80mmの鋼断面（S275、E=210GPa）を長さ1.2mの片持ちとし、先端の集中荷重ではなく1.5kN/mの等分布荷重を受ける場合です（庇の骨組みや、全長にわたって物を載せる棚など）。先端集中荷重の場合と係数を見比べてください（wL²/2 と wL⁴/(8EI)）。", es: "La misma sección de acero de 8×80 mm (S275, E = 210 GPa), ahora de 1,2 m de largo y con 1,5 kN/m repartidos a lo largo en lugar de una carga puntual en el extremo: la costilla de una marquesina o un estante cargado en toda su longitud. Compara los coeficientes con el caso de carga puntual: wL²/2 y wL⁴/(8EI).", "pt-BR": "A mesma seção de aço de 8×80 mm (S275, E = 210 GPa), agora com 1,2 m de comprimento e 1,5 kN/m distribuídos ao longo dela em vez de uma carga concentrada na extremidade: a nervura de uma marquise ou uma prateleira carregada em todo o comprimento. Compare os coeficientes com o caso de carga concentrada: wL²/2 e wL⁴/(8EI).", de: "Derselbe Stahlquerschnitt 8×80 mm (S275, E = 210 GPa), jetzt 1,2 m lang und mit 1,5 kN/m über die Länge verteilt statt einer Einzellast am freien Ende — eine Vordachrippe oder ein über die ganze Länge belastetes Regalbrett. Die Beiwerte sind mit dem Fall der Einzellast zu vergleichen: wL²/2 und wL⁴/(8EI).", fr: "La même section en acier de 8×80 mm (S275, E = 210 GPa), maintenant longue de 1,2 m et portant 1,5 kN/m répartis sur toute sa longueur au lieu d'une charge ponctuelle à l'extrémité : une nervure d'auvent ou une étagère chargée sur toute sa longueur. À comparer avec les coefficients du cas de la charge ponctuelle : wL²/2 et wL⁴/(8EI)." },
    localConstants: [
      { symbol: "w", expression: "1.5kN/m" },
      { symbol: "L", expression: "1.2m" },
      { symbol: "E", expression: "210GPa" },
      { symbol: "I", expression: "341333mm^4" },
      { symbol: "Z", expression: "8533mm^3" },
    ],
    steps: [
      { title: { en: "Moment at the fixed end M", ja: "固定端の曲げモーメント M", es: "Momento en el empotramiento M", "pt-BR": "Momento no engastamento M", de: "Biegemoment an der Einspannung M", fr: "Moment à l'encastrement M" }, expression: "w*L^2/2", targetUnit: "N*m", formulaLatex: "M = \\dfrac{wL^2}{2}" },
      { title: { en: "Bending stress σ", ja: "曲げ応力 σ", es: "Esfuerzo de flexión σ", "pt-BR": "Tensão de flexão σ", de: "Biegespannung σ", fr: "Contrainte de flexion σ" }, expression: "w*L^2/(2*Z)", targetUnit: "MPa", formulaLatex: "\\sigma = \\dfrac{wL^2}{2Z}" },
      { title: { en: "Tip deflection δ", ja: "先端のたわみ δ", es: "Flecha en el extremo δ", "pt-BR": "Flecha na extremidade δ", de: "Durchbiegung am freien Ende δ", fr: "Flèche à l'extrémité δ" }, expression: "w*L^4/(8*E*I)", targetUnit: "mm", formulaLatex: "\\delta = \\dfrac{wL^4}{8EI}" },
    ],
  },
  {
    title: { en: "Euler buckling & slenderness (Ø60×5 steel tube)", ja: "オイラー座屈と細長比（φ60×5 鋼管）", es: "Pandeo de Euler y esbeltez (tubo de acero Ø60×5)", "pt-BR": "Flambagem de Euler e esbeltez (tubo de aço Ø60×5)", de: "Eulersches Knicken und Schlankheitsgrad (Stahlrohr Ø60×5)", fr: "Flambement d'Euler et élancement (tube en acier Ø60×5)" },
    description: { en: "A 3 m pin-ended strut of Ø60×5 steel tube (S275, E = 210 GPa, f_y = 275 MPa; A = 864 mm², I = 329375 mm⁴). Work out the radius of gyration and the slenderness ratio first: Euler's formula is only valid while the critical stress stays below yield, which needs a slenderness above about π√(E/f_y) ≈ 87. At 154 this strut is comfortably slender, and the critical stress of 88 MPa confirms it buckles long before it yields.", ja: "長さ3m・両端ピンのφ60×5鋼管（S275、E=210GPa、f_y=275MPa、A=864mm²、I=329375mm⁴）の圧縮材です。まず断面二次半径と細長比を求めます。オイラーの式が使えるのは座屈応力が降伏応力より小さい範囲、つまり細長比がおよそ π√(E/f_y)≒87 を超えるときだけだからです。この材は細長比154で十分に細長く、座屈応力88MPaという結果も「降伏よりずっと手前で座屈する」ことを裏づけています。", es: "Una barra comprimida de 3 m con los extremos articulados, de tubo de acero Ø60×5 (S275, E = 210 GPa, f_y = 275 MPa; A = 864 mm², I = 329375 mm⁴). Calcula primero el radio de giro y la esbeltez: la fórmula de Euler solo vale mientras el esfuerzo crítico de pandeo se mantenga por debajo del límite elástico, lo que exige una esbeltez superior a π√(E/f_y) ≈ 87 aproximadamente. Con 154, esta barra es holgadamente esbelta, y el esfuerzo crítico de pandeo de 88 MPa confirma que pandea mucho antes de plastificar.", "pt-BR": "Uma barra comprimida de 3 m birrotulada, em tubo de aço Ø60×5 (S275, E = 210 GPa, f_y = 275 MPa; A = 864 mm², I = 329375 mm⁴). Calcule primeiro o raio de giração e o índice de esbeltez: a fórmula de Euler só vale enquanto a tensão crítica de flambagem ficar abaixo da tensão de escoamento, o que exige uma esbeltez acima de cerca de π√(E/f_y) ≈ 87. Com 154, esta barra é folgadamente esbelta, e a tensão crítica de flambagem de 88 MPa confirma que ela flamba muito antes de escoar.", de: "Ein 3 m langer, beidseitig gelenkig gelagerter Druckstab aus Stahlrohr Ø60×5 (S275, E = 210 GPa, f_y = 275 MPa; A = 864 mm², I = 329375 mm⁴). Zuerst sind Trägheitsradius und Schlankheitsgrad zu bestimmen: Die eulersche Formel gilt nur, solange die Knickspannung unter der Streckgrenze bleibt, wofür ein Schlankheitsgrad über etwa π√(E/f_y) ≈ 87 nötig ist. Mit 154 ist dieser Stab reichlich schlank, und die Knickspannung von 88 MPa bestätigt, dass er lange vor dem Fließen knickt.", fr: "Une barre comprimée de 3 m articulée à ses deux extrémités, en tube d'acier Ø60×5 (S275, E = 210 GPa, f_y = 275 MPa ; A = 864 mm², I = 329375 mm⁴). Il faut d'abord calculer le rayon de giration et l'élancement : la formule d'Euler n'est valable que tant que la contrainte critique de flambement reste sous la limite d'élasticité, ce qui exige un élancement supérieur à environ π√(E/f_y) ≈ 87. Avec 154, cette barre est largement élancée, et la contrainte critique de flambement de 88 MPa confirme qu'elle flambe bien avant de plastifier." },
    localConstants: [
      { symbol: "E", expression: "210GPa" },
      { symbol: "A", expression: "864mm^2" },
      { symbol: "I", expression: "329375mm^4" },
      { symbol: "k", expression: "1" },
      { symbol: "L", expression: "3m" },
      { symbol: "r", expression: "sqrt(I/A)" },
    ],
    steps: [
      { title: { en: "Radius of gyration r", ja: "断面二次半径 r", es: "Radio de giro r", "pt-BR": "Raio de giração r", de: "Trägheitsradius r", fr: "Rayon de giration r" }, expression: "r", targetUnit: "mm", formulaLatex: "r = \\sqrt{\\dfrac{I}{A}}" },
      { title: { en: "Slenderness ratio λ (Euler needs λ > ≈87)", ja: "細長比 λ（オイラーの式が使えるのは λ>約87）", es: "Esbeltez λ (Euler exige λ > ≈87)", "pt-BR": "Índice de esbeltez λ (Euler exige λ > ≈87)", de: "Schlankheitsgrad λ (Euler erfordert λ > ≈87)", fr: "Élancement λ (Euler exige λ > ≈87)" }, expression: "k*L/r", targetUnit: "", formulaLatex: "\\lambda = \\dfrac{kL}{r}" },
      { title: { en: "Euler buckling load P_cr", ja: "オイラー座屈荷重 P_cr", es: "Carga de pandeo de Euler P_cr", "pt-BR": "Carga de flambagem de Euler P_cr", de: "Eulersche Knicklast P_cr", fr: "Charge critique de flambement d'Euler P_cr" }, expression: "pi^2*E*I/(k*L)^2", targetUnit: "kN", formulaLatex: "P_{cr} = \\dfrac{\\pi^2 EI}{(kL)^2}" },
      { title: { en: "Critical stress σ_cr (vs f_y = 275 MPa)", ja: "座屈応力 σ_cr（f_y=275MPaと比較）", es: "Esfuerzo crítico de pandeo σ_cr (frente a f_y = 275 MPa)", "pt-BR": "Tensão crítica de flambagem σ_cr (comparada a f_y = 275 MPa)", de: "Knickspannung σ_cr (gegenüber f_y = 275 MPa)", fr: "Contrainte critique de flambement σ_cr (par rapport à f_y = 275 MPa)" }, expression: "pi^2*E*I/((k*L)^2*A)", targetUnit: "MPa", formulaLatex: "\\sigma_{cr} = \\dfrac{\\pi^2 EI}{(kL)^2 A}" },
    ],
  },
  {
    title: { en: "Beam self-weight as a distributed load", ja: "はりの自重を等分布荷重に直す", es: "El peso propio de la viga como carga distribuida", "pt-BR": "O peso próprio da viga como carga distribuída", de: "Eigengewicht des Trägers als verteilte Last", fr: "Le poids propre de la poutre en charge répartie" },
    description: { en: "Density times cross-sectional area gives mass per metre. For the IPE 200 of the earlier notebook (steel ρ = 7850 kg/m³, A = 28.5 cm²) that lands on 22.37 kg/m — the catalogue value for IPE 200 is 22.4 kg/m, a satisfying check that the section area and the density agree. Multiply by g to get the self-weight as a distributed load you can add to w.", ja: "密度に断面積を掛ければ1mあたりの質量が出ます。先のノートで使ったIPE 200（鋼の密度 ρ=7850kg/m³、A=28.5cm²）では22.37kg/mとなり、カタログのIPE 200の値22.4kg/mとぴたりと一致します。断面積と密度が噛み合っていることの気持ちのよい確認になります。これにgを掛ければ、そのままwに足せる自重の等分布荷重になります。", es: "La densidad por el área de la sección da la masa por metro. Para el IPE 200 del cuaderno anterior (acero ρ = 7850 kg/m³, A = 28,5 cm²) salen 22,37 kg/m, y el valor de catálogo del IPE 200 es 22,4 kg/m: una comprobación muy satisfactoria de que el área de la sección y la densidad concuerdan. Multiplicando por g se obtiene el peso propio como carga distribuida, lista para sumarla a w.", "pt-BR": "A densidade vezes a área da seção dá a massa por metro. Para o IPE 200 do caderno anterior (aço ρ = 7850 kg/m³, A = 28,5 cm²) dá 22,37 kg/m, e o valor de catálogo do IPE 200 é 22,4 kg/m: uma verificação bem satisfatória de que a área da seção e a densidade concordam. Multiplicando por g obtém-se o peso próprio como carga distribuída, pronta para ser somada a w.", de: "Dichte mal Querschnittsfläche ergibt die Masse pro Meter. Für das IPE 200 aus dem vorherigen Rechenheft (Stahl ρ = 7850 kg/m³, A = 28,5 cm²) sind das 22,37 kg/m — der Katalogwert für IPE 200 lautet 22,4 kg/m, eine erfreuliche Bestätigung, dass Querschnittsfläche und Dichte zusammenpassen. Multipliziert mit g ergibt sich das Eigengewicht als verteilte Last, die sich direkt zu w addieren lässt.", fr: "La masse volumique multipliée par l'aire de la section donne la masse par mètre. Pour l'IPE 200 du carnet précédent (acier ρ = 7850 kg/m³, A = 28,5 cm²), cela donne 22,37 kg/m — la valeur de catalogue de l'IPE 200 est 22,4 kg/m, une vérification très satisfaisante que l'aire de la section et la masse volumique concordent. En multipliant par g, on obtient le poids propre en charge répartie, prête à être ajoutée à w." },
    localConstants: [
      { symbol: "ρ", expression: "7850kg/m^3" },
      { symbol: "A", expression: "28.5cm^2" },
      { symbol: "g", expression: "9.80665m/s^2" },
      { symbol: "L", expression: "5m" },
    ],
    steps: [
      { title: { en: "Mass per metre m′ (catalogue: 22.4 kg/m)", ja: "1mあたりの質量 m′（カタログ値 22.4kg/m）", es: "Masa por metro m′ (catálogo: 22,4 kg/m)", "pt-BR": "Massa por metro m′ (catálogo: 22,4 kg/m)", de: "Masse pro Meter m′ (Katalog: 22,4 kg/m)", fr: "Masse par mètre m′ (catalogue : 22,4 kg/m)" }, expression: "ρ*A", targetUnit: "kg/m", formulaLatex: "m' = \\rho A" },
      { title: { en: "Self-weight as a distributed load w_g", ja: "自重の等分布荷重 w_g", es: "Peso propio como carga distribuida w_g", "pt-BR": "Peso próprio como carga distribuída w_g", de: "Eigengewicht als verteilte Last w_g", fr: "Poids propre en charge répartie w_g" }, expression: "ρ*A*g", targetUnit: "N/m", formulaLatex: "w_g = \\rho A g" },
      { title: { en: "Total mass of the beam m", ja: "はり全体の質量 m", es: "Masa total de la viga m", "pt-BR": "Massa total da viga m", de: "Gesamtmasse des Trägers m", fr: "Masse totale de la poutre m" }, expression: "ρ*A*L", targetUnit: "kg", formulaLatex: "m = \\rho A L" },
    ],
  },
  {
    title: { en: "Shear stress in a rectangular beam", ja: "矩形断面はりのせん断応力", es: "Esfuerzo cortante en una viga de sección rectangular", "pt-BR": "Tensão de cisalhamento em uma viga de seção retangular", de: "Schubspannung im Rechteckquerschnitt", fr: "Contrainte de cisaillement dans une poutre de section rectangulaire" },
    description: { en: "Shear stress is not spread evenly over the depth of a beam. On a rectangular section it follows a parabola: zero at the top and bottom faces, maximum at the neutral axis, where it reaches exactly 1.5 times the average V/A. That factor of 1.5 is why dividing the shear force by the area on its own understates the real peak by half again.", ja: "せん断応力ははりの高さ方向に一様には分布しません。矩形断面では放物線状に分布し、上下面でゼロ、中立軸で最大となって、平均値V/Aのちょうど1.5倍になります。この1.5倍があるため、せん断力を断面積で割っただけの値では実際のピークを5割も小さく見積もってしまいます。", es: "El esfuerzo cortante no se reparte de manera uniforme en el canto de una viga. En una sección rectangular sigue una parábola: cero en las caras superior e inferior y máximo en el eje neutro, donde alcanza exactamente 1,5 veces el valor medio V/A. Por ese factor 1,5, dividir sin más la fuerza cortante por el área subestima el pico real en un 50 %.", "pt-BR": "A tensão de cisalhamento não se distribui de forma uniforme na altura da viga. Em uma seção retangular ela segue uma parábola: zero nas faces superior e inferior e máxima na linha neutra, onde chega a exatamente 1,5 vez o valor médio V/A. Por causa desse fator 1,5, dividir a força cortante apenas pela área subestima o pico real em 50 %.", de: "Die Schubspannung verteilt sich über die Höhe eines Balkens nicht gleichmäßig. Im Rechteckquerschnitt verläuft sie parabelförmig: null an Ober- und Unterkante, maximal in der neutralen Faser, wo sie genau das 1,5-Fache des Mittelwerts V/A erreicht. Wegen dieses Faktors 1,5 unterschätzt die bloße Division der Querkraft durch die Fläche den tatsächlichen Höchstwert um die Hälfte.", fr: "La contrainte de cisaillement ne se répartit pas uniformément sur la hauteur d'une poutre. Sur une section rectangulaire, elle suit une parabole : nulle sur les faces supérieure et inférieure, maximale sur l'axe neutre, où elle atteint exactement 1,5 fois la valeur moyenne V/A. À cause de ce facteur 1,5, diviser simplement l'effort tranchant par l'aire sous-estime le pic réel de moitié." },
    localConstants: [
      { symbol: "V", expression: "12kN" },
      { symbol: "b", expression: "50mm" },
      { symbol: "h", expression: "150mm" },
      { symbol: "A", expression: "b*h" },
    ],
    steps: [
      { title: { en: "Maximum shear stress τ_max at the neutral axis", ja: "中立軸の最大せん断応力 τ_max", es: "Esfuerzo cortante máximo τ_max en el eje neutro", "pt-BR": "Tensão de cisalhamento máxima τ_max na linha neutra", de: "Maximale Schubspannung τ_max in der neutralen Faser", fr: "Contrainte de cisaillement maximale τ_max sur l'axe neutre" }, expression: "1.5*V/A", targetUnit: "MPa", formulaLatex: "\\tau_{max} = \\dfrac{3V}{2A}" },
    ],
  },
];
